    /*
    * Rollback del DML (DML_25062022_KBAQUE.pks)
    * @author Kevin Baque Puya <kbaque@telconet.ec>
    * @version 1.0 - 25-06-2022
    */
    DROP SEQUENCE NAF47_TNET.SEQ_ARIN_CATALOGO_KATUK_DET;

    DROP SEQUENCE NAF47_TNET.SEQ_ARIN_CATALOGO_KATUK_CAB;

    DROP TABLE NAF47_TNET.ARIN_CATALOGO_KATUK_DET;

    DROP TABLE NAF47_TNET.ARIN_CATALOGO_KATUK_CAB;

    ALTER TABLE NAF47_TNET.ARINDA DROP COLUMN CATALOGO_ID_DET;

    COMMIT;
    /