/** UPDATE INFORMACION **/
UPDATE DB_SSO.ADMI_SERVICIO_SSO 
SET TIPO_AUTENTICACION = 'CAS',
    DEPARTAMENTO_RESPONSABLE = 'Sistemas',
    NOMBRE_RESPONSABLE = 'Jessica Suarez',
    CORREO_RESPONSABLE = 'jmsuarez@telconet.ec',
    AUTORIZAR_CAS = 1
WHERE TIPO_AUTENTICACION IS NULL
AND DEPARTAMENTO_RESPONSABLE IS NULL
AND NOMBRE_RESPONSABLE IS NULL
AND CORREO_RESPONSABLE IS NULL
AND AUTORIZAR_CAS IS NULL;

COMMIT;

/
