/*
 * Insert para contrato digital web.
 */

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'ESTADO_SERVICIOS_CONTRATO_ADENDUM';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET B WHERE B.PARAMETRO_ID= (SELECT A.ID_PARAMETRO
FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'ESTADO_SERVICIOS_CONTRATO_ADENDUM');

COMMIT;
/
