
--Delete para eliminar el parametro para el dia de corte de registro de solicitude de HE.

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID= (SELECT A.ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'DIA_DE_CORTE_HE');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE ID_PARAMETRO= (SELECT A.ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'DIA_DE_CORTE_HE');



COMMIT;

/
