/**
 *
 * Parámetros del query para mover archivos a NFS
 * para el proyecto Gestión Documental
 *	 
 * @author Carlos Julio Pérez Quizhpe <cjperez@telconet.ec>
 * @version 1.0 12-08-2021
 */
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB
(
   ID_PARAMETRO,
   NOMBRE_PARAMETRO,
   DESCRIPCION,
   MODULO,
   PROCESO,
   ESTADO,
   USR_CREACION,
   FE_CREACION,
   IP_CREACION,
   USR_ULT_MOD,
   FE_ULT_MOD,
   IP_ULT_MOD
) 
VALUES
(
   DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
   'QUERIES_PARA_MOVER_ARCHIVOS_A_NUEVO_NFS_GD',
   'QUERIES PARA MOVER ARCHIVOS A NUEVO NFS GD',
   'GESTION DOCUMENTAL',
   'GESTION DOCUMENTAL',
   'Activo',
   'cjperez',
   SYSDATE,
   '127.0.0.1',
   null,
   null,
   null
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
   ID_PARAMETRO_DET,
   PARAMETRO_ID,
   DESCRIPCION,
   VALOR1,
   VALOR2,
   VALOR3,
   VALOR4,
   ESTADO,
   USR_CREACION,
   FE_CREACION,
   IP_CREACION,
   USR_ULT_MOD,
   FE_ULT_MOD,
   IP_ULT_MOD,
   VALOR5,
   EMPRESA_COD,
   VALOR6,
   VALOR7,
   OBSERVACION
) 
VALUES
(
   DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
   (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO='QUERIES_PARA_MOVER_ARCHIVOS_A_NUEVO_NFS_GD'),
   'QUERIES PARA MOVER ARCHIVOS A NUEVO NFS /gd/store/ GESTION DOCUMENTAL',
   'SELECT ID_DOCUMENTO, '''' AS PATH_ADICIONAL,
      7 AS CODIGO_APP, 1 AS CODIGO_PATH,
      TO_CHAR(FE_CREACION, ''rrrr'') ANIO_MOD,
      TO_CHAR(FE_CREACION, ''mm'') MES_MOD,
      TO_CHAR(FE_CREACION, ''dd'') DIA_MOD,
      CONCAT(CONCAT(PATH, ID_DOCUMENTO), ''.pdf'') AS UBICACION_FISICA_DOCUMENTO, 
      TITULO AS NOMBRE_DOCUMENTO, USR_CREACION
   FROM DB_DOCUMENTAL.INFO_DOCUMENTO
   WHERE 
   TRUNC(FE_CREACION) BETWEEN TRUNC(to_date(?,''dd/mm/rrrr'')) AND TRUNC(to_date(?,''dd/mm/rrrr''))
   AND ROWNUM<=5 AND UBICACION_FISICA_DOCUMENTO IS NULL 
   ',
   NULL,
   NULL,
   NULL,
   'Activo',
   'cjperez',
   SYSDATE,
   '127.0.0.1',
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL
);

COMMIT;
/
