/*
 * Creación de la tabla 'INFO_SERVICIO_RECURSO_CAB', encargada de
 * almacenar los recursos de una solucion.
 */
CREATE TABLE DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB
(
  ID_SERVICIO_RECURSO_CAB NUMBER,
  TIPO_RECURSO            VARCHAR2(1000),
  DESCRIPCION_RECURSO     VARCHAR2(1000),
  SERVICIO_ID             NUMBER,
  SOLICITUD_ID            NUMBER,
  CANTIDAD                NUMBER,
  ESTADO                  VARCHAR2(30) NOT NULL,
  USR_CREACION            VARCHAR2(30) NOT NULL,
  FEC_CREACION            TIMESTAMP    NOT NULL,
  IP_CREACION             VARCHAR2(30) NOT NULL,
  USR_ULT_MOD             VARCHAR2(30),
  FEC_ULT_MOD             TIMESTAMP,
  IP_ULT_MOD              VARCHAR2(30),
  CONSTRAINT PK_ID_SERVICIO_RECURSO_CAB PRIMARY KEY (ID_SERVICIO_RECURSO_CAB)
);

--Comentario de la tabla 'INFO_SERVICIO_RECURSO_CAB'.
COMMENT ON TABLE DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB
    IS 'TABLA ENCARGADA DE ALMACENAR LOS RECURSOS DE UNA SOLUCION';

--Comentarios de las columnas de la tabla 'INFO_SERVICIO_RECURSO_CAB'.
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.ID_SERVICIO_RECURSO_CAB IS 'ID DE LA TABLA';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.DESCRIPCION_RECURSO     IS 'DESCRIPCION DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.TIPO_RECURSO   IS 'TIPO DE RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.SERVICIO_ID    IS 'SERVICIO DEL PUNTO CLIENTE';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.SOLICITUD_ID   IS 'REFERENCIA CON EL DETALLE DE LA SOLICITUD';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.CANTIDAD       IS 'AGRUPACION DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.ESTADO         IS 'ESTADO DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.USR_CREACION   IS 'USUARIO QUIEN CREA EL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.FEC_CREACION   IS 'FECHA DE CREACION DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.IP_CREACION    IS 'IP DEL USUARIO QUIEN CREA EL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.USR_ULT_MOD    IS 'USUARIO QUIEN MODIFICA EL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.FEC_ULT_MOD    IS 'FECHA DE MODIFICACION DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB.IP_ULT_MOD     IS 'IP DEL USUARIO QUIEN MODIFICA EL RECURSO DE LA SOLUCION';

--Creación de indices para mayor agilidad en la consulta de la tabla 'INFO_SERVICIO_RECURSO_CAB'.
CREATE INDEX DB_COMERCIAL.IDX_TIPO_RECURSO_RE         ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (TIPO_RECURSO);
CREATE INDEX DB_COMERCIAL.IDX_DESCRIPCION_RECURSO_RE  ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (DESCRIPCION_RECURSO);
CREATE INDEX DB_COMERCIAL.IDX_TIPO_DESCRIPCION_RE     ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (TIPO_RECURSO,DESCRIPCION_RECURSO);
CREATE INDEX DB_COMERCIAL.IDX_SERVICIO_ID_RE          ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (SERVICIO_ID);
CREATE INDEX DB_COMERCIAL.IDX_ESTADO_RE               ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (ESTADO);
CREATE INDEX DB_COMERCIAL.IDX_FEC_CREACION_ASC_RE     ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (FEC_CREACION ASC);
CREATE INDEX DB_COMERCIAL.IDX_FEC_CREACION_DESC_RE    ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (FEC_CREACION DESC);
CREATE INDEX DB_COMERCIAL.IDX_USR_CREACION_RE         ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (USR_CREACION);
CREATE INDEX DB_COMERCIAL.IDX_SERVICIO_USR_RE         ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (SERVICIO_ID,USR_CREACION);
CREATE INDEX DB_COMERCIAL.IDX_SERVICIO_FEC_RE         ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (SERVICIO_ID,FEC_CREACION);
CREATE INDEX DB_COMERCIAL.IDX_SERVICIO_FEC_USR_RE     ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (SERVICIO_ID,USR_CREACION,FEC_CREACION);

/*
 * Creación de la tabla 'INFO_SERVICIO_RECURSO_DET', encargada de
 * almacenar el detalle de los recursos de una solucion.
 */
CREATE TABLE DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET
(
  ID_SERVICIO_RECURSO_DET NUMBER,
  SERVICIO_RECURSO_CAB_ID NUMBER,
  ELEMENTO_ID             NUMBER,
  CANTIDAD                NUMBER,
  REF_RECURSO_DET_ID      NUMBER,
  DESCRIPCION             VARCHAR2(3000),
  ESTADO                  VARCHAR2(30) NOT NULL,
  USR_CREACION            VARCHAR2(30) NOT NULL,
  FEC_CREACION            TIMESTAMP    NOT NULL,
  IP_CREACION             VARCHAR2(30) NOT NULL,
  USR_ULT_MOD             VARCHAR2(30),
  FEC_ULT_MOD             TIMESTAMP,
  IP_ULT_MOD              VARCHAR2(30),
  CONSTRAINT PK_ID_SERVICIO_RECURSO_DET PRIMARY KEY (ID_SERVICIO_RECURSO_DET),
  CONSTRAINT FK_SERVICIO_RECURSO_CAB_ID FOREIGN KEY (SERVICIO_RECURSO_CAB_ID)
    REFERENCES DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB (ID_SERVICIO_RECURSO_CAB),
  CONSTRAINT FK_REF_RECURSO_DET_ID FOREIGN KEY (REF_RECURSO_DET_ID)
    REFERENCES DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET (ID_SERVICIO_RECURSO_DET)
);

--Comentario de la tabla 'INFO_SERVICIO_RECURSO_DET'.
COMMENT ON TABLE DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET
    IS 'TABLA ENCARGADA DE ALMACENAR EL DETALLE DE LOS RECURSOS DE UNA SOLUCION';

--Comentarios de las columnas de la tabla 'INFO_SERVICIO_RECURSO_DET'.
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.ID_SERVICIO_RECURSO_DET  IS 'ID DE LA TABLA';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.SERVICIO_RECURSO_CAB_ID  IS 'REFERENCIA A LA TABLA INFO_SERVICIO_RECURSO_CAB';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.ELEMENTO_ID              IS 'REFERENCIA A LA TABLA INFO_ELEMENTO';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.CANTIDAD                 IS 'CANTIDAD DE APROVICIONAMIENTO DEL RECURSO';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.REF_RECURSO_DET_ID       IS 'REFERENCIA A LA TABLA INFO_SERVICIO_RECURSO_DET';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.ESTADO                   IS 'ESTADO DEL DETALLE DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.USR_CREACION             IS 'USUARIO QUIEN CREA EL DETALLE DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.FEC_CREACION             IS 'FECHA DE CREACION DEL DETALLE DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.IP_CREACION              IS 'IP DEL USUARIO QUIEN CREA EL DETALLE DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.USR_ULT_MOD              IS 'USUARIO QUIEN MODIFICA EL DETALLE DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.FEC_ULT_MOD              IS 'FECHA DE MODIFICACION DEL DEALLE DEL RECURSO DE LA SOLUCION';
COMMENT ON COLUMN DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET.IP_ULT_MOD               IS 'IP DEL USUARIO QUIEN MODIFICA EL DETALLE DEL RECURSO DE LA SOLUCION';

--Creación de indices para mayor agilidad en la consulta de la tabla 'INFO_SERVICIO_RECURSO_DET'.
CREATE INDEX DB_COMERCIAL.IDX_ELEMENTO_ID_RED        ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET (ELEMENTO_ID);
CREATE INDEX DB_COMERCIAL.IDX_ESTADO_RED             ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET (ESTADO);
CREATE INDEX DB_COMERCIAL.IDX_FEC_CREACION_ASC_RED   ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET (FEC_CREACION ASC);
CREATE INDEX DB_COMERCIAL.IDX_FEC_CREACION_DESC_RED  ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET (FEC_CREACION DESC);
CREATE INDEX DB_COMERCIAL.IDX_USR_CREACION_RED       ON DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET (USR_CREACION);

/
