/*
  =======================================================
  =========== SCRIPT DE REVERSO - ESTRUCTURAS ===========
  =======================================================
*/

DROP TABLE DB_COMERCIAL.INFO_SOLUCION_REFERENCIA;
DROP TABLE DB_COMERCIAL.INFO_SOLUCION_DET;
DROP TABLE DB_COMERCIAL.INFO_SOLUCION_CAB;
DROP TABLE DB_COMERCIAL.INFO_SERVICIO_RECURSO_DET;
DROP TABLE DB_COMERCIAL.INFO_SERVICIO_RECURSO_CAB;

/
