CREATE OR REPLACE PROCEDURE NAF47_TNET.P_MARCAR_ARTI_CONSUMIBLE AS 

/**
 * Procedimiento que marca los art�culos consumibles en la tabla NAF47_TNET.ARINDA
 * 
 * @author afayala <afayala@telconet.ec>
 * @version 1.0 03/01/2020 
 * 
 */

CURSOR C_ARTICULO IS
SELECT  ARTI_NO, NO_CIA
FROM NAF47_TNET.CONSUMIBLES; 

Lv_ArtiNo CONSUMIBLES.ARTI_NO%TYPE;
Lv_NoCia  CONSUMIBLES.NO_CIA%TYPE;
Lv_ArtUs  VARCHAR2(15);

BEGIN
  OPEN C_ARTICULO;
  LOOP
    FETCH C_ARTICULO INTO Lv_ArtiNo,Lv_NoCia;
    EXIT WHEN C_ARTICULO%NOTFOUND;
    Lv_ArtUs := SUBSTR(REGEXP_REPLACE(Lv_ArtiNo,'10','US',1,1),1,20);
    
    UPDATE NAF47_TNET.ARINDA SET IND_CONSUMIBLE='S' 
    WHERE NO_ARTI = Lv_ArtiNo AND NO_CIA = Lv_NoCia;
    
    UPDATE NAF47_TNET.ARINDA SET IND_CONSUMIBLE='S' 
    WHERE NO_ARTI = Lv_ArtUs AND NO_CIA = Lv_NoCia;
    
    COMMIT;

  END LOOP;
  CLOSE C_ARTICULO;
END P_MARCAR_ARTI_CONSUMIBLE;
/