CREATE   OR REPLACE VIEW "DB_FINANCIERO"."VISTA_DOCUMENTOS_CORTE_MASIVO" ("PUNTO_ID", "ID_DOCUMENTO", "ID_TIPO_DOCUMENTO", "CODIGO_TIPO_DOCUMENTO", "USR_CREACION_DOCUMENTO", "FE_CREACION_DOCUMENTO") AS 
  SELECT
    /*+ INDEX_SS(DOCUMENTO_FINANCIERO_CAB) */
    DOCUMENTO_FINANCIERO_CAB.PUNTO_ID,
    DOCUMENTO_FINANCIERO_CAB.ID_DOCUMENTO,
    TIPO_DOCUMENTO_FINANCIERO.ID_TIPO_DOCUMENTO,
    TIPO_DOCUMENTO_FINANCIERO.CODIGO_TIPO_DOCUMENTO,
    DOCUMENTO_FINANCIERO_CAB.USR_CREACION                       AS USR_CREACION_DOCUMENTO,
    TO_CHAR(DOCUMENTO_FINANCIERO_CAB.FE_CREACION, 'YYYY-MM-DD') AS FE_CREACION_DOCUMENTO
  FROM DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB DOCUMENTO_FINANCIERO_CAB
  INNER JOIN DB_FINANCIERO.ADMI_TIPO_DOCUMENTO_FINANCIERO TIPO_DOCUMENTO_FINANCIERO
  ON (TIPO_DOCUMENTO_FINANCIERO.CODIGO_TIPO_DOCUMENTO = 'FAC'
  AND DOCUMENTO_FINANCIERO_CAB.USR_CREACION          IN
    (SELECT PARAM_DET1.VALOR4
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB PARAM_CAB1
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET PARAM_DET1
    ON PARAM_DET1.PARAMETRO_ID        = PARAM_CAB1.ID_PARAMETRO
    WHERE PARAM_CAB1.NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_MD'
    AND PARAM_CAB1.ESTADO             = 'Activo'
    AND PARAM_DET1.VALOR1             = 'CORTE_MASIVO'
    AND PARAM_DET1.VALOR2             = 'USR_CREACION_IN_POR_TIPO_DE_DOCUMENTO'
    AND PARAM_DET1.VALOR3             = 'FAC'
    AND PARAM_DET1.ESTADO             = 'Activo'
    )
  OR TIPO_DOCUMENTO_FINANCIERO.CODIGO_TIPO_DOCUMENTO = 'FACP'
  AND DOCUMENTO_FINANCIERO_CAB.USR_CREACION NOT     IN
    (SELECT PARAM_DET2.VALOR4
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB PARAM_CAB2
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET PARAM_DET2
    ON PARAM_DET2.PARAMETRO_ID        = PARAM_CAB2.ID_PARAMETRO
    WHERE PARAM_CAB2.NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_MD'
    AND PARAM_CAB2.ESTADO             = 'Activo'
    AND PARAM_DET2.VALOR1             = 'CORTE_MASIVO'
    AND PARAM_DET2.VALOR2             = 'USR_CREACION_NOT_IN_POR_TIPO_DE_DOCUMENTO'
    AND PARAM_DET2.VALOR3             = 'FACP'
    AND PARAM_DET2.ESTADO             = 'Activo'
    )
  OR TIPO_DOCUMENTO_FINANCIERO.CODIGO_TIPO_DOCUMENTO = 'NDI'
  AND EXISTS
    (SELECT DOCUMENTO_CARACT.ID_DOCUMENTO_CARACTERISTICA
    FROM DB_FINANCIERO.INFO_DOCUMENTO_CARACTERISTICA DOCUMENTO_CARACT
    INNER JOIN DB_COMERCIAL.ADMI_CARACTERISTICA CARACT
    ON CARACT.ID_CARACTERISTICA             = DOCUMENTO_CARACT.CARACTERISTICA_ID
    WHERE CARACT.DESCRIPCION_CARACTERISTICA = 'PROCESO_DIFERIDO'
    AND DOCUMENTO_CARACT.VALOR              = 'S'
    AND DOCUMENTO_CARACT.DOCUMENTO_ID       = DOCUMENTO_FINANCIERO_CAB.ID_DOCUMENTO
    AND ROWNUM                              = 1
    ))
  AND TIPO_DOCUMENTO_FINANCIERO.ID_TIPO_DOCUMENTO                  = DOCUMENTO_FINANCIERO_CAB.TIPO_DOCUMENTO_ID
  WHERE UPPER(DOCUMENTO_FINANCIERO_CAB.ESTADO_IMPRESION_FACT) NOT IN ('CERRADO', 'PENDIENTE', 'ANULADO', 'RECHAZADO', 
                                                                      'RECHAZADA', 'INACTIVO', 'ELIMINADO');