CREATE FORCE EDITIONABLE VIEW "DB_FINANCIERO"."VISTA_IVA_CUENTA_RESUM_SFI" ("PUNTO_ID", "TOTAL_BIENES", "TOTAL_SERVICIOS", "TOTAL_IVA_SERVICIOS", "TOTAL_IVA_BIENES") AS 
  SELECT ESTADO_CUENTA.PUNTO_ID, 
	   ABS(SUM(ESTADO_CUENTA.TOTAL_BIENES))        TOTAL_BIENES, 
	   ABS(SUM(ESTADO_CUENTA.TOTAL_SERVICIOS))     TOTAL_SERVICIOS, 
	   ABS(SUM(ESTADO_CUENTA.TOTAL_IVA_SERVICIOS)) TOTAL_IVA_SERVICIOS, 
	   ABS(SUM(ESTADO_CUENTA.TOTAL_IVA_BIENES))    TOTAL_IVA_BIENES
    FROM(
	    SELECT IDFC.PUNTO_ID,
		   ROUND(IDFC.SUBTOTAL_SERVICIOS,  2) AS TOTAL_SERVICIOS,
		   ROUND(IDFC.IMPUESTOS_SERVICIOS, 2) AS TOTAL_IVA_SERVICIOS,
		   ROUND(IDFC.SUBTOTAL_BIENES,     2) AS TOTAL_BIENES,
		   ROUND(IDFC.IMPUESTOS_BIENES,    2) AS TOTAL_IVA_BIENES
	    FROM DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB IDFC
	    WHERE IDFC.ESTADO_IMPRESION_FACT IN ('Activo') 
	      AND IDFC.TIPO_DOCUMENTO_ID NOT IN (6,8)
          AND IDFC.ID_DOCUMENTO NOT IN (SELECT IDC.DOCUMENTO_ID
                                        FROM DB_FINANCIERO.INFO_DOCUMENTO_CARACTERISTICA IDC,
                                             DB_COMERCIAL.ADMI_CARACTERISTICA AC
                                        WHERE 
                                        IDC.DOCUMENTO_ID          = IDFC.ID_DOCUMENTO
                                        AND IDC.CARACTERISTICA_ID = AC.ID_CARACTERISTICA
                                        AND AC.DESCRIPCION_CARACTERISTICA IN ('POR_CONTRATO_FISICO','POR_CONTRATO_DIGITAL')
                                        AND AC.ESTADO = 'Activo'
                                        AND IDFC.ESTADO_IMPRESION_FACT = 'Activo'
                                        ) 
	) ESTADO_CUENTA
    GROUP BY ESTADO_CUENTA.PUNTO_ID;