CREATE FORCE EDITIONABLE VIEW "DB_FINANCIERO"."VISTA_FACTURAS_ABIERTAS" ("PUNTO_ID", "FACTURAS_ABIERTAS") AS 
  SELECT T_DOC_FINANCIERO_TIPO_DOC.PUNTO_ID,
    COUNT(DISTINCT T_DOC_FINANCIERO_TIPO_DOC.ID_DOCUMENTO) AS FACTURAS_ABIERTAS
  FROM
    (SELECT DOCUMENTO_FINANCIERO_CAB.PUNTO_ID,
      DOCUMENTO_FINANCIERO_CAB.ID_DOCUMENTO,
      CASE UPPER(TIPO_DOCUMENTO_FINANCIERO.CODIGO_TIPO_DOCUMENTO)
        WHEN 'NDI'
        THEN NVL(
          (SELECT DOCUMENTO_CARACT.VALOR
          FROM DB_FINANCIERO.INFO_DOCUMENTO_CARACTERISTICA DOCUMENTO_CARACT
          INNER JOIN DB_COMERCIAL.ADMI_CARACTERISTICA CARACT
          ON CARACT.ID_CARACTERISTICA             = DOCUMENTO_CARACT.CARACTERISTICA_ID
          WHERE CARACT.DESCRIPCION_CARACTERISTICA = 'PROCESO_DIFERIDO'
          AND DOCUMENTO_CARACT.VALOR              = 'S'
          AND DOCUMENTO_CARACT.DOCUMENTO_ID       = DOCUMENTO_FINANCIERO_CAB.ID_DOCUMENTO
          AND ROWNUM                              = 1
          ), 'N')
        ELSE DOCUMENTO_FINANCIERO_CAB.RECURRENTE
      END AS PERMITE_CONTEO
    FROM DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB DOCUMENTO_FINANCIERO_CAB
    INNER JOIN DB_FINANCIERO.ADMI_TIPO_DOCUMENTO_FINANCIERO TIPO_DOCUMENTO_FINANCIERO
    ON TIPO_DOCUMENTO_FINANCIERO.ID_TIPO_DOCUMENTO                   = DOCUMENTO_FINANCIERO_CAB.TIPO_DOCUMENTO_ID
    WHERE UPPER(DOCUMENTO_FINANCIERO_CAB.ESTADO_IMPRESION_FACT) NOT IN ('CERRADO', 'PENDIENTE', 'ANULADO', 'RECHAZADO', 'RECHAZADA', 
                                                                        'INACTIVO', 'ELIMINADO')
    AND UPPER(TIPO_DOCUMENTO_FINANCIERO.CODIGO_TIPO_DOCUMENTO)      IN ('FAC', 'FACP', 'NDI')
    ) T_DOC_FINANCIERO_TIPO_DOC
  WHERE PERMITE_CONTEO = 'S'
  GROUP BY T_DOC_FINANCIERO_TIPO_DOC.PUNTO_ID;