CREATE FORCE EDITIONABLE VIEW "DB_FINANCIERO"."VISTA_CLIENTES_REPORTE_BURO" ("ID_PERSONA", "TIPO_IDENTIFICACION", "TIPO_DOCUMENTO", "IDENTIFICACION_CLIENTE", "NOMBRE_CLIENTE", "SALDO", "ESTADO", "EMPRESA_COD") AS 
  SELECT ipe.ID_PERSONA,
       ipe.TIPO_IDENTIFICACION,
       CASE WHEN ipe.TIPO_IDENTIFICACION = 'CED' THEN 'C'
            WHEN ipe.TIPO_IDENTIFICACION = 'RUC' THEN 'R'
            ELSE 'E'
       END AS TIPO_DOCUMENTO,
       ipe.IDENTIFICACION_CLIENTE,
       FNCK_CONSULTS.F_GET_NOMBRE_APELLIDOS_PERSONA(ipe.ID_PERSONA) AS NOMBRE_CLIENTE,
       SUM(vecr.SALDO) AS SALDO,
       ip.ESTADO,
       ier.EMPRESA_COD
FROM DB_FINANCIERO.VISTA_ESTADO_CUENTA_RESUMIDO vecr
JOIN DB_COMERCIAL.INFO_PUNTO ip
ON ip.ID_PUNTO = vecr.PUNTO_ID
JOIN DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL iper
ON iper.ID_PERSONA_ROL = ip.PERSONA_EMPRESA_ROL_ID
JOIN DB_COMERCIAL.INFO_EMPRESA_ROL ier
ON ier.ID_EMPRESA_ROL = iper.EMPRESA_ROL_ID
JOIN DB_COMERCIAL.INFO_PERSONA ipe
ON ipe.ID_PERSONA = iper.PERSONA_ID
WHERE vecr.SALDO > 0.01
  AND ip.ESTADO IN ('Activo', 'Cancelado', 'Trasladado', 'In-Corte','Anulado','Eliminado')
GROUP BY ipe.ID_PERSONA,
         ipe.TIPO_IDENTIFICACION,
         ipe.IDENTIFICACION_CLIENTE,
         FNCK_CONSULTS.F_GET_NOMBRE_APELLIDOS_PERSONA(ipe.ID_PERSONA),
         ip.ESTADO,
         ier.EMPRESA_COD
ORDER BY ipe.ID_PERSONA;