
--DROP PARA ELIMINAR TRIGGER DE LA TABLA LISTADO_HORAS_HE

DROP TRIGGER DB_HORAS_EXTRAS.BEFORE_LISTADO_HORAS_HE;

---DROP PARA ELIMINAR SECUENCIA DE LA TABLA LISTADO_HORAS_HE DEL ESQUEMA DB_HORAS_EXTRAS.

DROP SEQUENCE DB_HORAS_EXTRAS.SEQ_LISTADO_HORAS_HE;

--DROP PARA ELIMINAR TABLA LISTADO_HORAS_HE DEL ESQUEMA DB_HORAS_EXTRAS.

DROP TABLE DB_HORAS_EXTRAS.LISTADO_HORAS_HE;

/
