/**
 * DEBE EJECUTARSE EN DB_HORAS_EXTRAS.
 * @author Ivan Mata <imata@telconet.ec>
 * @version 1.0 15-07-2020 - Versión Inicial.
 */

/** Trigger auditoria tabla INFO_DOCUMENTO_HORAS_EXTRAS **/
CREATE OR REPLACE TRIGGER DB_HORAS_EXTRAS.BEFORE_INFO_DOC_HORAS_EXTRA
  BEFORE UPDATE ON DB_HORAS_EXTRAS.INFO_DOCUMENTO_HORAS_EXTRAS FOR EACH ROW

BEGIN
  :NEW.USR_MODIFICACION := NVL(:NEW.USR_MODIFICACION,USER);
  :NEW.FE_MODIFICACION  := NVL(:NEW.FE_MODIFICACION,SYSDATE);
  :NEW.IP_CREACION      := NVL(:NEW.IP_CREACION,NVL(SYS_CONTEXT('USER','IP_ADDRESS'),'127.0.0.1'));
END;

/
