/**
 * DEBE EJECUTARSE EN DB_HORAS_EXTRAS.
 * @author Ivan Mata <imata@telconet.ec>
 * @version 1.0 28-08-2020 - Versión Inicial.
 */

/** Trigger auditoria tabla INFO_HORAS_SOLICITUD_EMPLEADO **/
CREATE OR REPLACE TRIGGER DB_HORAS_EXTRAS.BEFORE_INFO_HORAS_SOLI_EMPLE
  BEFORE UPDATE ON DB_HORAS_EXTRAS.INFO_HORAS_SOLICITUD_EMPLEADO FOR EACH ROW

BEGIN
  :NEW.USR_MODIFICACION := NVL(:NEW.USR_MODIFICACION,USER);
  :NEW.FE_MODIFICACION  := NVL(:NEW.FE_MODIFICACION,SYSDATE);
  :NEW.IP_CREACION      := NVL(:NEW.IP_CREACION,NVL(SYS_CONTEXT('USER','IP_ADDRESS'),'127.0.0.1'));
END;

/

