CREATE OR REPLACE VIEW "DB_INFRAESTRUCTURA"."VISTA_ELEMENTOS" ("ID_TIPO_ELEMENTO", "NOMBRE_TIPO_ELEMENTO", "ID_ELEMENTO", "NOMBRE_ELEMENTO", "IP", "ID_JURISDICCION", "NOMBRE_JURISDICCION", "ID_CANTON", "NOMBRE_CANTON", "ID_MARCA_ELEMENTO", "NOMBRE_MARCA_ELEMENTO", "ID_MODELO_ELEMENTO", "NOMBRE_MODELO_ELEMENTO", "ESTADO", "EMPRESA_COD", "ID_ELEMENTO_B", "NOMBRE_ELEMENTO_B", "LATITUD", "LONGITUD", "SERIE_FISICA") AS 
  SELECT ID_TIPO_ELEMENTO,
  NOMBRE_TIPO_ELEMENTO,
  ID_ELEMENTO,
  NOMBRE_ELEMENTO,
  IP,
  ID_JURISDICCION,
  NOMBRE_JURISDICCION,
  ID_CANTON,
  NOMBRE_CANTON,
  ID_MARCA_ELEMENTO,
  NOMBRE_MARCA_ELEMENTO,
  ID_MODELO_ELEMENTO,
  NOMBRE_MODELO_ELEMENTO,
  ESTADO,
  EMPRESA_COD,
  MIN(ID_ELEMENTO_B) ID_ELEMENTO_B,
  MIN(NOMBRE_ELEMENTO_B) NOMBRE_ELEMENTO_B,
  LATITUD,
  LONGITUD,
  SERIE_FISICA
FROM
  (SELECT DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO.ID_TIPO_ELEMENTO,
    DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO.NOMBRE_TIPO_ELEMENTO,
    DB_INFRAESTRUCTURA.INFO_ELEMENTO.ID_ELEMENTO,
    DB_INFRAESTRUCTURA.INFO_ELEMENTO.NOMBRE_ELEMENTO,
    DB_INFRAESTRUCTURA.INFO_IP.IP,
    DB_INFRAESTRUCTURA.ADMI_JURISDICCION.ID_JURISDICCION,
    DB_INFRAESTRUCTURA.ADMI_JURISDICCION.NOMBRE_JURISDICCION,
    DB_GENERAL.ADMI_CANTON.ID_CANTON,
    DB_GENERAL.ADMI_CANTON.NOMBRE_CANTON,
    DB_INFRAESTRUCTURA.ADMI_MARCA_ELEMENTO.ID_MARCA_ELEMENTO,
    DB_INFRAESTRUCTURA.ADMI_MARCA_ELEMENTO.NOMBRE_MARCA_ELEMENTO,
    DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO.ID_MODELO_ELEMENTO,
    DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO.NOMBRE_MODELO_ELEMENTO,
    DB_INFRAESTRUCTURA.INFO_ELEMENTO.ESTADO,
    DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA.EMPRESA_COD,
    INFO_ELEMENTO_B.ID_ELEMENTO ID_ELEMENTO_B,
    INFO_ELEMENTO_B.NOMBRE_ELEMENTO NOMBRE_ELEMENTO_B,
    DB_INFRAESTRUCTURA.INFO_UBICACION.LATITUD_UBICACION LATITUD,
    DB_INFRAESTRUCTURA.INFO_UBICACION.LONGITUD_UBICACION LONGITUD,
    DB_INFRAESTRUCTURA.INFO_ELEMENTO.SERIE_FISICA
  FROM DB_GENERAL.ADMI_CANTON,
    DB_GENERAL.ADMI_PARROQUIA,
    DB_INFRAESTRUCTURA.INFO_UBICACION,
    DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA,
    DB_INFRAESTRUCTURA.ADMI_CANTON_JURISDICCION,
    DB_INFRAESTRUCTURA.ADMI_JURISDICCION,
    DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO,
    DB_INFRAESTRUCTURA.ADMI_MARCA_ELEMENTO,
    DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO,
    DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO,
    DB_COMERCIAL.INFO_OFICINA_GRUPO,
    ( DB_INFRAESTRUCTURA.INFO_ELEMENTO
  LEFT JOIN DB_INFRAESTRUCTURA.INFO_IP
  ON ( DB_INFRAESTRUCTURA.INFO_ELEMENTO.ID_ELEMENTO = DB_INFRAESTRUCTURA.INFO_IP.ELEMENTO_ID
  AND DB_INFRAESTRUCTURA.INFO_IP.ESTADO             = 'Activo')
  LEFT JOIN DB_INFRAESTRUCTURA.INFO_RELACION_ELEMENTO
  ON ( DB_INFRAESTRUCTURA.INFO_ELEMENTO.ID_ELEMENTO    = DB_INFRAESTRUCTURA.INFO_RELACION_ELEMENTO.ELEMENTO_ID_B
  AND DB_INFRAESTRUCTURA.INFO_RELACION_ELEMENTO.ESTADO = 'Activo')
  LEFT JOIN DB_INFRAESTRUCTURA.INFO_ELEMENTO INFO_ELEMENTO_B
  ON ( DB_INFRAESTRUCTURA.INFO_RELACION_ELEMENTO.ELEMENTO_ID_A    = INFO_ELEMENTO_B.ID_ELEMENTO
  AND DB_INFRAESTRUCTURA.INFO_ELEMENTO_B.ESTADO                   = 'Activo') )
  WHERE DB_GENERAL.ADMI_CANTON.ID_CANTON                          = DB_GENERAL.ADMI_PARROQUIA.CANTON_ID
  AND DB_GENERAL.ADMI_PARROQUIA.ID_PARROQUIA                      = DB_INFRAESTRUCTURA.INFO_UBICACION.PARROQUIA_ID
  AND DB_INFRAESTRUCTURA.INFO_UBICACION.ID_UBICACION              = DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA.UBICACION_ID
  AND DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA.ELEMENTO_ID  = DB_INFRAESTRUCTURA.INFO_ELEMENTO.ID_ELEMENTO
  AND DB_GENERAL.ADMI_CANTON.ID_CANTON                            = DB_INFRAESTRUCTURA.ADMI_CANTON_JURISDICCION.CANTON_ID
  AND DB_INFRAESTRUCTURA.ADMI_CANTON_JURISDICCION.JURISDICCION_ID = DB_INFRAESTRUCTURA.ADMI_JURISDICCION.ID_JURISDICCION
  AND DB_INFRAESTRUCTURA.ADMI_JURISDICCION.OFICINA_ID             = DB_COMERCIAL.INFO_OFICINA_GRUPO.ID_OFICINA
  AND DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA.EMPRESA_COD  = DB_COMERCIAL.INFO_OFICINA_GRUPO.EMPRESA_ID
  AND DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO.ID_TIPO_ELEMENTO      = DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO.TIPO_ELEMENTO_ID
  AND DB_INFRAESTRUCTURA.ADMI_MARCA_ELEMENTO.ID_MARCA_ELEMENTO    = DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO.MARCA_ELEMENTO_ID
  AND DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO.ID_MODELO_ELEMENTO  = DB_INFRAESTRUCTURA.INFO_ELEMENTO.MODELO_ELEMENTO_ID
  AND DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO.ELEMENTO_ID        = DB_INFRAESTRUCTURA.INFO_ELEMENTO.ID_ELEMENTO
  AND DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO.EMPRESA_COD        = DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA.EMPRESA_COD
  AND DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO.ESTADO             = 'Activo'
  AND DB_INFRAESTRUCTURA.ADMI_CANTON_JURISDICCION.ESTADO         <> 'Eliminado'
  AND DB_INFRAESTRUCTURA.ADMI_JURISDICCION.ESTADO                <> 'Eliminado'
  AND DB_COMERCIAL.INFO_OFICINA_GRUPO.ESTADO                      = 'Activo'   
  )
GROUP BY ID_TIPO_ELEMENTO,
  NOMBRE_TIPO_ELEMENTO,
  ID_ELEMENTO,
  NOMBRE_ELEMENTO,
  IP,
  ID_JURISDICCION,
  NOMBRE_JURISDICCION,
  ID_CANTON,
  NOMBRE_CANTON,
  ID_MARCA_ELEMENTO,
  NOMBRE_MARCA_ELEMENTO,
  ID_MODELO_ELEMENTO,
  NOMBRE_MODELO_ELEMENTO,
  ESTADO,
  EMPRESA_COD,
  LATITUD,
  LONGITUD,
  SERIE_FISICA;