--Eliminar types
DROP TYPE DB_COMERCIAL.DATOS_SECUENCIA;
DROP TYPE DB_COMERCIAL.DATOS_TARJETA_TYPE;
DROP TYPE DB_COMERCIAL.FORMA_PAGO_TYPE;
DROP TYPE DB_COMERCIAL.DATOS_APROBAR_ADENDUM_TYPE;
DROP TYPE DB_COMERCIAL.Pcl_ServEncontrado_Type;

/