 

--SE ELIMINA NUEVA COLUMNA EN LA TABLA INFO_CERTIFICADO_DOCUMENTO 
ALTER TABLE  DB_FIRMAELECT.INFO_CERTIFICADO_DOCUMENTO DROP (OBSERVACION); 
ALTER TABLE  DB_FIRMAELECT.INFO_CERTIFICADO_DOCUMENTO DROP (INTENTOS); 
COMMIT;
/