--ROLLBACK
--####################################

--SE ELIMINAN TABLAS

DROP TABLE DB_COMERCIAL.INFO_DETALLE_SOL_PLANIF_HIST;
DROP TABLE DB_COMERCIAL.INFO_DETALLE_SOL_PLANIF;
DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_DETALLE_SOL_PLANIF_HI;
DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_DETALLE_SOL_PLANIF;

--SE ELIMINA TIPO SOLICITUD
DELETE FROM DB_COMERCIAL.ADMI_TIPO_SOLICITUD WHERE DESCRIPCION_SOLICITUD = 'SOLICITUD INSPECCION' AND USR_CREACION = 'amontero';

--SE ELIMINAN CARACTERISTICAS
DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'LOGIN_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'NUMERO_PROPUESTA_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'NOMBRE_PROYECTO_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'NUMERO_COTIZACION_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'LONGITUD_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'LATITUD_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'DIRECCION_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'NOMBRES_CONTACTO_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'TELEFONO_CONTACTO_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'CIUDAD_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'NOMBRE_CLIENTE_INSPECCION' AND USR_CREACION = 'amontero';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'PRODUCTO_INSPECCION' AND USR_CREACION = 'amontero';

--SE ELIMINAN MOTIVOS

DELETE FROM DB_GENERAL.ADMI_MOTIVO WHERE
RELACION_SISTEMA_ID = 
     (SELECT ID_RELACION_SISTEMA FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA 
     WHERE MODULO_ID = 137  AND 
     ACCION_ID = (SELECT ID_ACCION FROM DB_SEGURIDAD.SIST_ACCION WHERE NOMBRE_ACCION = 'getMotivosDetenerInspeccion'))
 AND USR_CREACION = 'amontero';

DELETE FROM DB_GENERAL.ADMI_MOTIVO WHERE
RELACION_SISTEMA_ID = 
     (SELECT ID_RELACION_SISTEMA FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA 
     WHERE MODULO_ID = 137  AND 
     ACCION_ID = (SELECT ID_ACCION FROM DB_SEGURIDAD.SIST_ACCION WHERE NOMBRE_ACCION = 'getMotivosReplanificarInspeccion'))
 AND USR_CREACION = 'amontero';

DELETE FROM DB_GENERAL.ADMI_MOTIVO WHERE
RELACION_SISTEMA_ID = 
     (SELECT ID_RELACION_SISTEMA FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA 
     WHERE MODULO_ID = 137  AND 
     ACCION_ID = (SELECT ID_ACCION FROM DB_SEGURIDAD.SIST_ACCION WHERE NOMBRE_ACCION = 'getMotivosRechazarInspeccion'))
 AND USR_CREACION = 'amontero';

 DELETE FROM DB_GENERAL.ADMI_MOTIVO WHERE
RELACION_SISTEMA_ID = 
     (SELECT ID_RELACION_SISTEMA FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA 
     WHERE MODULO_ID = 137  AND 
     ACCION_ID = (SELECT ID_ACCION FROM DB_SEGURIDAD.SIST_ACCION WHERE NOMBRE_ACCION = 'getMotivosAnularInspeccion'))
 AND USR_CREACION = 'amontero';

 DELETE FROM DB_GENERAL.ADMI_MOTIVO WHERE
RELACION_SISTEMA_ID = 
     (SELECT ID_RELACION_SISTEMA FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA 
     WHERE MODULO_ID = 137  AND 
     ACCION_ID = (SELECT ID_ACCION FROM DB_SEGURIDAD.SIST_ACCION WHERE NOMBRE_ACCION = 'getMotivosReplanificarInspeccion'))
 AND USR_CREACION = 'amontero';

 DELETE FROM DB_GENERAL.ADMI_MOTIVO WHERE
RELACION_SISTEMA_ID = 
     (SELECT ID_RELACION_SISTEMA FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA 
     WHERE MODULO_ID = 137  AND 
     ACCION_ID = (SELECT ID_ACCION FROM DB_SEGURIDAD.SIST_ACCION WHERE NOMBRE_ACCION = 'getMotivosRechazarSolicitudInspeccion'))
 AND USR_CREACION = 'amontero';


--SE ELIMINAN RELACION SISTEMA


--SE ELIMINAN ACCIONES



--SE ELIMINAN PARAMETROS

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID =
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'TAREA_PROGRAMAR_INSPECCION');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'TAREA_PROGRAMAR_INSPECCION';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID =
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'TAREAS_ASOCIADAS_INSPECCION');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'TAREAS_ASOCIADAS_INSPECCION';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID =
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'ESTADOS_PERMITIDOS_GESTIONAR_INSPECCION');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'ESTADOS_PERMITIDOS_GESTIONAR_INSPECCION';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID =
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'ROLES_PERMITIDOS_GESTIONAR_INSPECCION');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'ROLES_PERMITIDOS_GESTIONAR_INSPECCION';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID =
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'TIPOS_SOLICITUD_GRID_PLANIFICACION_COORDINAR');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'TIPOS_SOLICITUD_GRID_PLANIFICACION_COORDINAR';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID =
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'CARACTERISTICAS_OBLIGATORIAS_EN_WS_SOLICITUD_INSPECCION');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'CARACTERISTICAS_OBLIGATORIAS_EN_WS_SOLICITUD_INSPECCION';
/