
--SE AGREGA NUEVA COLUMNA EN LA TABLA INFO_CERTIFICADO_DOCUMENTO 
ALTER TABLE  DB_FIRMAELECT.INFO_CERTIFICADO_DOCUMENTO ADD (OBSERVACION CLOB ); 
ALTER TABLE  DB_FIRMAELECT.INFO_CERTIFICADO_DOCUMENTO ADD (INTENTOS NUMBER ); 
 
COMMIT;
/