BEGIN 
dbms_scheduler.create_job('"JOB_ELIMINAR_NOTIF_MASIVA_AUTO"',
job_type=>'PLSQL_BLOCK', job_action=>
'BEGIN
                             DB_COMUNICACION.CUKG_TRANSACTIONS.P_ELIMINA_ENVIO_MASIVO_AUT;
                           END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('12-OCT-2017 10.57.27.392939000 PM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=MINUTELY;INTERVAL=30'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Job que elimina automaticamente los env�os masivos'
);
sys.dbms_scheduler.set_attribute('"JOB_ELIMINAR_NOTIF_MASIVA_AUTO"','NLS_ENV','NLS_LANGUAGE=''SPANISH'' NLS_TERRITORY=''SPAIN'' NLS_CURRENCY=''�'' NLS_ISO_CURRENCY=''SPAIN'' NLS_NUMERIC_CHARACTERS='',.'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD/MM/RR'' NLS_DATE_LANGUAGE=''SPANISH'' NLS_SORT=''SPANISH'' NLS_TIME_FORMAT=''HH24:MI:SSXFF'' NLS_TIMESTAMP_FORMAT=''DD/MM/RR HH24:MI:SSXFF'' NLS_TIME_TZ_FORMAT=''HH24:MI:SSXFF TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD/MM/RR HH24:MI:SSXFF TZR'' NLS_DUAL_CURRENCY=''�'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
