
BEGIN 
dbms_scheduler.create_job('"JOB_ACTUALIZA_AUDIT_ELEMENTOS"',
job_type=>'STORED_PROCEDURE', job_action=>
'DB_COMUNICACION.CUKG_TRANSACTIONS.P_ACTUALIZA_AUDIT_ELEMENTOS'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('23-OCT-2017 06.12.54.000000000 PM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=DAILY;BYHOUR=0;BYMINUTE=0;BYSECOND=0'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Proceso que se ejecuta una vez al d��a para poder evaluar nuevamente a un elemento'
);
sys.dbms_scheduler.set_attribute('"JOB_ACTUALIZA_AUDIT_ELEMENTOS"','NLS_ENV','NLS_LANGUAGE=''AMERICAN'' NLS_TERRITORY=''AMERICA'' NLS_CURRENCY=''$'' NLS_ISO_CURRENCY=''AMERICA'' NLS_NUMERIC_CHARACTERS=''.,'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD-MON-RR'' NLS_DATE_LANGUAGE=''AMERICAN'' NLS_SORT=''BINARY'' NLS_TIME_FORMAT=''HH.MI.SSXFF AM'' NLS_TIMESTAMP_FORMAT=''DD-MON-RR HH.MI.SSXFF AM'' NLS_TIME_TZ_FORMAT=''HH.MI.SSXFF AM TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD-MON-RR HH.MI.SSXFF AM TZR'' NLS_DUAL_CURRENCY=''$'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.set_attribute('"JOB_ACTUALIZA_AUDIT_ELEMENTOS"','logging_level',DBMS_SCHEDULER.LOGGING_FULL);
dbms_scheduler.enable('"JOB_ACTUALIZA_AUDIT_ELEMENTOS"');
COMMIT; 
END; 
/ 
