/* Formatted on 5/2/2023 10:02:50 AM (QP5 v5.336) */
CREATE OR REPLACE FORCE VIEW DB_FINANCIERO.VISTA_IVA_CUENTA_RESUMIDO
(
    PUNTO_ID,
    TOTAL_BIENES,
    TOTAL_SERVICIOS,
    TOTAL_IVA_SERVICIOS,
    TOTAL_IVA_BIENES
)
BEQUEATH DEFINER
AS
      SELECT ESTADO_CUENTA.PUNTO_ID,
             ABS (SUM (ESTADO_CUENTA.TOTAL_BIENES))
                 TOTAL_BIENES,
             ABS (SUM (ESTADO_CUENTA.TOTAL_SERVICIOS))
                 TOTAL_SERVICIOS,
             ABS (SUM (ESTADO_CUENTA.TOTAL_IVA_SERVICIOS))
                 TOTAL_IVA_SERVICIOS,
             ABS (SUM (ESTADO_CUENTA.TOTAL_IVA_BIENES))
                 TOTAL_IVA_BIENES
        FROM (SELECT DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB.PUNTO_ID,
                     ROUND (
                         DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB.SUBTOTAL_SERVICIOS,
                         2)    AS TOTAL_SERVICIOS,
                     ROUND (
                         DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB.IMPUESTOS_SERVICIOS,
                         2)    AS TOTAL_IVA_SERVICIOS,
                     ROUND (
                         DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB.SUBTOTAL_BIENES,
                         2)    AS TOTAL_BIENES,
                     ROUND (
                         DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB.IMPUESTOS_BIENES,
                         2)    AS TOTAL_IVA_BIENES
                FROM DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB
               WHERE     DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB.estado_impresion_fact IN
                             ('Activo')
                     AND TIPO_DOCUMENTO_ID NOT IN (6, 8)) ESTADO_CUENTA
    GROUP BY ESTADO_CUENTA.PUNTO_ID;
/
