/*
 * Ejecutar bloque anonimo para el update de las tablets que no tienen publishId.
 */

DECLARE
	CURSOR C_ELEMENTOS_TABLETS
	IS
	  SELECT IE.*
	  FROM DB_INFRAESTRUCTURA.INFO_ELEMENTO IE,
	  DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO AME,
	  DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO ATE
	  WHERE IE.MODELO_ELEMENTO_ID = AME.ID_MODELO_ELEMENTO
	    AND AME.TIPO_ELEMENTO_ID = ATE.ID_TIPO_ELEMENTO
	    AND ATE.NOMBRE_TIPO_ELEMENTO = 'TABLET'
	    AND IE.SERIE_LOGICA IS NULL
	    AND IE.ESTADO = 'Activo';
	   
	CURSOR C_CARACT_BY_ELEMENTO(Cn_IdElemento NUMBER, Cv_Caract VARCHAR2)
	IS
	  SELECT IDE.* 
	  FROM DB_INFRAESTRUCTURA.INFO_DETALLE_ELEMENTO IDE
	  WHERE IDE.ELEMENTO_ID = Cn_IdElemento
		AND IDE.DETALLE_NOMBRE = Cv_Caract;
	   
	CURSOR C_PUBLISH_ID_BY_TABLET(Cv_Imei  VARCHAR2)
	IS
	  SELECT GM.PUBLISH_ID
	  FROM DB_MONITOREO.GPS_MONITOREO GM
	  WHERE GM.IMEI = Cv_Imei
	    AND GM.PUBLISH_ID != ' '
	    AND GM.PUBLISH_ID IS NOT NULL
	  GROUP BY GM.PUBLISH_ID;
	 
	Lc_CaractElementoMonitori      C_CARACT_BY_ELEMENTO%rowtype;
BEGIN
   FOR i in C_ELEMENTOS_TABLETS LOOP
     FOR j in C_PUBLISH_ID_BY_TABLET(i.NOMBRE_ELEMENTO) LOOP
      -- Actualizar el publishId
      UPDATE DB_INFRAESTRUCTURA.INFO_ELEMENTO
	  SET SERIE_LOGICA = j.PUBLISH_ID
	  WHERE ID_ELEMENTO = i.ID_ELEMENTO;
	  -- Verificar caract ES_MONITORIZADO
	  OPEN C_CARACT_BY_ELEMENTO(i.ID_ELEMENTO, 'ES_MONITORIZADO');
      FETCH C_CARACT_BY_ELEMENTO INTO Lc_CaractElementoMonitori;
      CLOSE C_CARACT_BY_ELEMENTO;
      
      IF Lc_CaractElementoMonitori.ID_DETALLE_ELEMENTO IS NULL THEN
      	INSERT INTO DB_INFRAESTRUCTURA.INFO_DETALLE_ELEMENTO (
      			ID_DETALLE_ELEMENTO,
      			ELEMENTO_ID,
      			DETALLE_NOMBRE,
      			DETALLE_VALOR,
      			DETALLE_DESCRIPCION,
      			USR_CREACION,
      			FE_CREACION,
      			IP_CREACION,
      			REF_DETALLE_ELEMENTO_ID,
      			ESTADO)
        VALUES (
        		DB_INFRAESTRUCTURA.SEQ_INFO_DETALLE_ELEMENTO.nextval,
       			i.ID_ELEMENTO,
       			'ES_MONITORIZADO',
       			'S',
       			'ES_MONITORIZADO',
       			'mpluas',
       			sysdate,
       			'127.0.0.1',
       			null,
       			'Activo'
       			);
      ELSE
      	IF Lc_CaractElementoMonitori.ESTADO != 'Activo' THEN
      	  UPDATE DB_INFRAESTRUCTURA.INFO_DETALLE_ELEMENTO
	  	  SET DETALLE_VALOR = 'S',
	  	  ESTADO = 'Activo',
	  	  DETALLE_DESCRIPCION = 'ES_MONITORIZADO',
	  	  IP_CREACION = '127.0.0.1',
	  	  FE_CREACION = SYSDATE,
	  	  USR_CREACION = 'mpluas'
	  	  WHERE ID_DETALLE_ELEMENTO = Lc_CaractElementoMonitori.ID_DETALLE_ELEMENTO;
      	END IF;
      END IF;
      COMMIT;
	  EXIT;
     END LOOP;
   END LOOP;
END;

/
