/*
 * SCRIPT DCL DEL ESQUEMA DB_COMERCIAL. 
 * https://www.techonthenet.com/oracle/grant_revoke.php
 */
GRANT INSERT,UPDATE,SELECT ON DB_COMERCIAL.INFO_PUNTO_CLAUSULA TO DB_DOCUMENTO;
GRANT INSERT,UPDATE,SELECT ON DB_COMERCIAL.INFO_PUNTO_CLAUSULA_RESP TO DB_DOCUMENTO;
GRANT ALL ON DB_COMERCIAL.SEQ_INFO_PUNTO_CLAUSULA TO DB_DOCUMENTO;
GRANT ALL ON DB_COMERCIAL.SEQ_INFO_PUNTO_CLAUSULA_RESP TO DB_DOCUMENTO;
/
