/*
 * SCRIPT DCL DEL ESQUEMA DB_COMERCIAL. 
 * SE AGREGAR PERMISOS DE EJECUCION DE TABLAS DEL ESQUEMA DB_COMUNICACION 
 *  AL ESQUEMA DB_SOPORTE
 */
GRANT EXECUTE ON DB_COMERCIAL.CMKG_SOLICITUD_TRANSACCION TO DB_SOPORTE;
GRANT DELETE ON DB_COMUNICACION.INFO_DOCUMENTO TO DB_SOPORTE;
GRANT DELETE ON DB_COMUNICACION.INFO_DOCUMENTO_RELACION TO DB_SOPORTE;
/
