/*
 * SCRIPT DCL DE REVERSO DEL ESQUEMA DB_COMERCIAL. 
 */
REVOKE REFERENCES ON DB_COMERCIAL.INFO_EMPRESA_GRUPO FROM DB_DOCUMENTO;
REVOKE SELECT  ON DB_COMERCIAL.INFO_EMPRESA_GRUPO FROM DB_DOCUMENTO;


/
