
DELETE FROM NAF47_TNET.INFO_DOCUMENTO;

DELETE FROM NAF47_TNET.ADMI_TIPO_DOCUMENTO;

DELETE FROM NAF47_TNET.ADMI_HALLAZGO;

DELETE FROM NAF47_TNET.ADMI_TIPO_SANCION;

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET 
WHERE PARAMETRO_ID = (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO = 'Activo');
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB 
WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL';
COMMIT;
/
