
INSERT INTO NAF47_TNET.ADMI_TIPO_SANCION(ID_TIPO_SANCION,TIPO_SANCION,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_TIPO_SANCION.NEXTVAL,'Leve','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_TIPO_SANCION(ID_TIPO_SANCION,TIPO_SANCION,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_TIPO_SANCION.NEXTVAL,'Grave','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'No justifica fibra','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'No justifica equipos','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'No justifica materiales','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'Mal etiquetado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'Sin Etiqueta','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'Sanción departamental','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'No usa uniforme','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'FO mal ingresada','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'Fibra mal tendida','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'Equipos mal instalado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Leve'),'FO pandeada','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Americano mal realizado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Dúplex mal colocados','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'EPP´S campo','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'FO mal pasada en fijador con gancho','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Herraje mal colocado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Patchcord Fibra mal peinado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Patchcord UTP mal peinado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Mantenimiento eléctrico mal realizado','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Mini manga fuera de estándar mal colocada','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'No usa fijador con gancho','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'No usa kit de acometida','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Incumple normas de bioseguridad','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'No apertura bitácora','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Sanción departamental','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Negligencia y descuido en el trabajo','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_HALLAZGO(ID_HALLAZGO,TIPO_SANCION_ID,HALLAZGO,DEPARTAMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_HALLAZGO.NEXTVAL,(SELECT ID_TIPO_SANCION FROM NAF47_TNET.ADMI_TIPO_SANCION WHERE TIPO_SANCION='Grave'),'Hilos mal Peinados en Casetera','OPERACIONES URBANAS','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO NAF47_TNET.ADMI_TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO,TIPO_DOCUMENTO,ESTADO,COD_EMPRESA,USR_CREACION,IP_CREACION,FE_CREACION)
VALUES(NAF47_TNET.SEQ_ADMI_TIPO_DOCUMENTO.NEXTVAL,'Memo','Activo',10,'kbaque','127.0.0.1',sysdate);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB (
    ID_PARAMETRO,
    NOMBRE_PARAMETRO,
    DESCRIPCION,
    MODULO,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
) VALUES (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
    'PARAMETROS_GESTION_PERSONAL',
    'PARAMETROS AUXILIARES QUE INTERACTUAN CON GESTION DE PERSONAL',
    'COMERCIAL',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_CONSULTA',
    'kbaque',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'psuarez',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'jcnavarro',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'marias',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'wparrales',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'kcatagua',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'molmedo',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'jvelez',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'etroya',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'mamoran',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'jpilay',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'gmartinez',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'vsalinas',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'sduenas',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'lquingalombo',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_EMPRESA',
    'mllumitasig',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'cdmera',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'vredroban',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'ejaraujo',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'caldaz',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'srojas',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'jfranco',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'larias',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'paherrera',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD,
    OBSERVACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'PARAMETROS_GESTION_PERSONAL' AND ESTADO      = 'Activo'),
    'ROL_INGRESO_DEPARTAMENTO',
    'jrendon',
    'Permitido',
    'Activo',
    'kbaque',
    SYSDATE,
    '127.0.0.1',
    10,
    'PARAMETROS QUE PERMITEN EL INGRESO A LAS OPCIONES DEL APLICATIVO GESTION PERSONAL: VALOR1=LOGIN DE LA PERSONA EN SESION, VALOR2=BANDERA SI PERMITE'
);
COMMIT;
/
