create or replace function            FI_OBTENER_LIBRO(NOMBRE IN OUT VARCHAR2

) return VARCHAR2 is
  
  CURSOR NOMBRE_LIBRO IS
  SELECT NOMBRE
  FROM TI_LIBRO
  WHERE ID_LIBRO=ID_LIBRO;
  
  NOMBRELIBRO      TI_LIBRO.NOMBRE%TYPE;
  
  V_EXIST          BOOLEAN;
begin
   
  OPEN NOMBRE_LIBRO;
  FETCH NOMBRE_LIBRO INTO NOMBRELIBRO;
  V_EXIST:=NOMBRE_LIBRO%FOUND;
  CLOSE NOMBRE_LIBRO;
  IF NOT V_EXIST THEN
     NOMBRELIBRO:=NULL;
  END IF;
  return(NOMBRELIBRO);
  
end FI_OBTENER_LIBRO;