CREATE OR REPLACE TRIGGER DB_SOPORTE.BEFORE_ADMI_SEGUI_ECUCERT
BEFORE UPDATE ON DB_SOPORTE.ADMI_SEGUIMIENTO_ECUCERT 
FOR EACH ROW  
BEGIN 
  :NEW.USR_ULT_MOD := USER; 
  :NEW.FE_ULT_MOD := SYSDATE;
END;


/