BEGIN 
dbms_scheduler.create_job('"JOB_INV_PEDIDO_MASIVO_INS"',
job_type=>'PLSQL_BLOCK', job_action=>
'begin NAF47_TNET.INKG_TRANSACCIONES_PEDIDOS.P_EJECUTAR_JOB; end;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('08-FEB-2022 12.00.00.000000000 AM -05:00','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'Freq=Hourly'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Proceso autom�tico generaci�n de pedido automaticos.'
);
sys.dbms_scheduler.set_attribute('"JOB_INV_PEDIDO_MASIVO_INS"','NLS_ENV','NLS_LANGUAGE=''SPANISH'' NLS_TERRITORY=''SPAIN'' NLS_CURRENCY=''�'' NLS_ISO_CURRENCY=''SPAIN'' NLS_NUMERIC_CHARACTERS='',.'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD/MM/RR'' NLS_DATE_LANGUAGE=''SPANISH'' NLS_SORT=''SPANISH'' NLS_TIME_FORMAT=''HH24:MI:SSXFF'' NLS_TIMESTAMP_FORMAT=''DD/MM/RR HH24:MI:SSXFF'' NLS_TIME_TZ_FORMAT=''HH24:MI:SSXFF TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD/MM/RR HH24:MI:SSXFF TZR'' NLS_DUAL_CURRENCY=''�'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.enable('"JOB_INV_PEDIDO_MASIVO_INS"');
COMMIT; 
END; 
/ 
