 /**
  * Documentación para hacer rollback planes que se toman para los parametros de facturacion detallada y sus relaciones
  * insercion de parametro para solcitud de retiro de equipos
  *  
  * @author Andre Lazo <alazo@telconet.ec>
  * @version 1.0 29-03-2023
  */




--DELETE ADMI_PRODUCTO_CARACTERISTICA 'VISUALIZAR_EN_MOVIL'
DELETE DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
WHERE PRODUCTO_ID = (SELECT ID_PRODUCTO FROM DB_COMERCIAL.ADMI_PRODUCTO WHERE DESCRIPCION_PRODUCTO='EQUIPOS VARIOS' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='alazo')
AND CARACTERISTICA_ID = ( SELECT ID_CARACTERISTICA FROM DB_COMERCIAL.ADMI_CARACTERISTICA
      WHERE DESCRIPCION_CARACTERISTICA = 'VISUALIZAR_EN_MOVIL' AND ESTADO = 'Activo' );

--DELETE ADMI_PRODUCTO_CARACTERISTICA 'TIPO DE EQUIPO'
DELETE DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
WHERE PRODUCTO_ID = (SELECT ID_PRODUCTO FROM DB_COMERCIAL.ADMI_PRODUCTO WHERE DESCRIPCION_PRODUCTO='EQUIPOS VARIOS' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='alazo')
AND CARACTERISTICA_ID = ( SELECT ID_CARACTERISTICA FROM DB_COMERCIAL.ADMI_CARACTERISTICA
      WHERE DESCRIPCION_CARACTERISTICA = 'TIPO DE EQUIPO' AND ESTADO = 'Activo' );


--DELETE TODO RELACIONADO PLAN 

DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'ecuanet' and 
plan_id=(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='EQV01' AND NOMBRE_PLAN='FUENTE DE PODER' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');


DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='CPEH' AND NOMBRE_PLAN='CPE Huawei' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='RSTA' AND NOMBRE_PLAN='ROSETA (Huawei)' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');


DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'telcos_adultomayor' and 
plan_id=(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='EQV01' AND NOMBRE_PLAN='FUENTE DE PODER' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');


DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'telcos_adultomayor' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='CPEH' AND NOMBRE_PLAN='CPE Huawei' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'telcos_adultomayor' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='RSTA' AND NOMBRE_PLAN='ROSETA (Huawei)' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'telcos_adultomayor' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='INS' AND NOMBRE_PLAN='INSTALACION' AND EMPRESA_COD=33 AND ESTADO='Inactivo' AND USR_CREACION='migracion_md');

DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='DINST' AND NOMBRE_PLAN='PROMO SUSCRIPCIONX3M' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='migracion_md');

DELETE FROM DB_COMERCIAL.info_plan_caracteristica
where usr_creacion = 'telcos_adultomayor' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='DINST' AND NOMBRE_PLAN='PROMO SUSCRIPCIONX3M' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='migracion_md');



DELETE FROM DB_COMERCIAL.info_plan_det
where usr_creacion = 'ecuanet' and 
plan_id=(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='EQV01' AND NOMBRE_PLAN='FUENTE DE PODER' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');


DELETE FROM DB_COMERCIAL.info_plan_det
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='CPEH' AND NOMBRE_PLAN='CPE Huawei' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_det
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='RSTA' AND NOMBRE_PLAN='ROSETA (Huawei)' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_det
where usr_creacion = 'migracion_md' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='INS' AND NOMBRE_PLAN='INSTALACION' AND EMPRESA_COD=33 AND ESTADO='Inactivo' AND USR_CREACION='migracion_md');

DELETE FROM DB_COMERCIAL.info_plan_det
where usr_creacion = 'migracion_md' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='DINST' AND NOMBRE_PLAN='PROMO SUSCRIPCIONX3M' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='migracion_md');


DELETE FROM DB_COMERCIAL.info_plan_historial
where usr_creacion = 'ecuanet' and 
plan_id=(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='EQV01' AND NOMBRE_PLAN='FUENTE DE PODER' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');


DELETE FROM DB_COMERCIAL.info_plan_historial
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='CPEH' AND NOMBRE_PLAN='CPE Huawei' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_historial
where usr_creacion = 'ecuanet' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='RSTA' AND NOMBRE_PLAN='ROSETA (Huawei)' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet');

DELETE FROM DB_COMERCIAL.info_plan_historial
where usr_creacion = 'migracion_md' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='INS' AND NOMBRE_PLAN='INSTALACION' AND EMPRESA_COD=33 AND ESTADO='Inactivo' AND USR_CREACION='migracion_md');

DELETE FROM DB_COMERCIAL.info_plan_historial
where usr_creacion = 'migracion_md' and 
plan_id=
(SELECT ID_PLAN FROM DB_COMERCIAL.INFO_PLAN_CAB WHERE CODIGO_PLAN='DINST' AND NOMBRE_PLAN='PROMO SUSCRIPCIONX3M' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='migracion_md');




DELETE FROM DB_COMERCIAL.info_plan_cab
WHERE CODIGO_PLAN='EQV01' AND NOMBRE_PLAN='FUENTE DE PODER' 
AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet';


DELETE FROM DB_COMERCIAL.info_plan_cab
WHERE CODIGO_PLAN='CPEH' AND NOMBRE_PLAN='CPE Huawei'
 AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet';

DELETE FROM DB_COMERCIAL.info_plan_cab
 WHERE CODIGO_PLAN='RSTA' AND NOMBRE_PLAN='ROSETA (Huawei)' 
 AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='ecuanet';

DELETE FROM DB_COMERCIAL.info_plan_cab
WHERE CODIGO_PLAN='INS' AND NOMBRE_PLAN='INSTALACION' 
AND EMPRESA_COD=33 AND ESTADO='Inactivo' AND USR_CREACION='migracion_md';


DELETE FROM DB_COMERCIAL.info_plan_cab
WHERE CODIGO_PLAN='DINST' AND NOMBRE_PLAN='PROMO SUSCRIPCIONX3M' 
AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='migracion_md';


--DELETE ADMI_PRODUCTO_CARACTERISTICA
DELETE DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
WHERE PRODUCTO_ID = (SELECT ID_PRODUCTO FROM DB_COMERCIAL.ADMI_PRODUCTO WHERE DESCRIPCION_PRODUCTO='EQUIPOS VARIOS' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='alazo');


--DELETE DEL PRODUCTO

DELETE FROM DB_COMERCIAL.ADMI_PRODUCTO
WHERE DESCRIPCION_PRODUCTO='EQUIPOS VARIOS' AND EMPRESA_COD=33 AND ESTADO='Activo' AND USR_CREACION='alazo';

COMMIT;
/



