DELETE FROM DB_SOPORTE.ADMI_PROCESO_EMPRESA P
WHERE P.EMPRESA_COD = 33 AND P.usr_creacion ='wbajana';

DELETE FROM DB_SOPORTE.ADMI_SINTOMA S
WHERE S.EMPRESA_COD = 33 AND S.usr_creacion ='wbajana';

COMMIT;

/
