/**
 * Scripts para el reverso de las tareas relacionadas al producto SAFE ENTRY
 *
 * @author Leonardo Mero <lemero@telconet.ec>
 * @version 1.0 09-12-2022
 */


--Se elimina la tarea para el retiro de equipos ELECTRICO
DELETE
FROM DB_SOPORTE.ADMI_PROCESO_EMPRESA
WHERE PROCESO_ID =
  (SELECT ID_PROCESO
  FROM DB_SOPORTE.ADMI_PROCESO
  WHERE NOMBRE_PROCESO = 'TAREAS DE ELECTRICO - RETIRO DE EQUIPOS'
  AND ESTADO           = 'Activo'
  );
DELETE
FROM DB_SOPORTE.ADMI_TAREA
WHERE PROCESO_ID =
  (SELECT ID_PROCESO
  FROM DB_SOPORTE.ADMI_PROCESO
  WHERE NOMBRE_PROCESO = 'TAREAS DE ELECTRICO - RETIRO DE EQUIPOS'
  AND ESTADO           = 'Activo'
  )
AND NOMBRE_TAREA = 'RETIRO DE EQUIPOS SAFE ENTRY'
AND ESTADO       = 'Activo';
DELETE
FROM DB_SOPORTE.ADMI_PROCESO
WHERE NOMBRE_PROCESO = 'TAREAS DE ELECTRICO - RETIRO DE EQUIPOS'
AND ESTADO           = 'Activo';

--Se elimina la tarea para el retiro de las bases de hormigón de la torre SAFE ENTRY, los bolardos y mástiles
DELETE
FROM DB_SOPORTE.ADMI_PROCESO_EMPRESA
WHERE PROCESO_ID =
  (SELECT ID_PROCESO
  FROM DB_SOPORTE.ADMI_PROCESO
  WHERE NOMBRE_PROCESO = 'TAREAS DE OBRAS CIVILES - RETIRO DE BASES'
  AND ESTADO           = 'Activo'
  );
DELETE
FROM DB_SOPORTE.ADMI_TAREA
WHERE PROCESO_ID =
  (SELECT ID_PROCESO
  FROM DB_SOPORTE.ADMI_PROCESO
  WHERE NOMBRE_PROCESO = 'TAREAS DE OBRAS CIVILES - RETIRO DE BASES'
  AND ESTADO           = 'Activo'
  )
AND NOMBRE_TAREA = 'RETIRO BASES OC'
AND ESTADO       = 'Activo';
DELETE
FROM DB_SOPORTE.ADMI_PROCESO
WHERE NOMBRE_PROCESO = 'TAREAS DE OBRAS CIVILES - RETIRO DE BASES'
AND ESTADO           = 'Activo';


--Rollback visualizacion de la fibra
UPDATE DB_SOPORTE.ADMI_TAREA
SET REQUIERE_FIBRA = NULL
WHERE ID_TAREA  =
  (SELECT ID_TAREA
  FROM DB_SOPORTE.ADMI_TAREA
  WHERE NOMBRE_TAREA = 'SEGUIDAD ELECTRONICA- IMPLEMENTACION SAFE ENTRY'
  );

COMMIT;
/