DECLARE

    CURSOR C_PROCESOS_MD IS
        SELECT p.proceso_id FROM DB_SOPORTE.ADMI_PROCESO_EMPRESA P WHERE P.EMPRESA_COD = 18
        AND P.ESTADO = 'Activo';
        
    CURSOR C_VAL_EX_PROCESO_EN(cn_procesoId NUMBER) IS
        SELECT COUNT(P.PROCESO_ID) FROM DB_SOPORTE.admi_proceso_empresa P 
        WHERE p.proceso_id = cn_procesoId AND p.empresa_cod = 33;

    CURSOR C_SINTOMA_MD IS
        SELECT SIM.NOMBRE_SINTOMA, SIM.DESCRIPCION_SINTOMA, SIM.TIPO_CASO_ID FROM DB_SOPORTE.ADMI_SINTOMA SIM 
        WHERE SIM.EMPRESA_COD = 18
        AND SIM.ESTADO = 'Activo';
        
    LN_VAL_EX_PROCESO_EN NUMBER;
    LN_SEQUENCIA NUMBER;
  
BEGIN
    
    IF (C_PROCESOS_MD%ISOPEN) THEN CLOSE C_PROCESOS_MD; END IF;
    IF (C_VAL_EX_PROCESO_EN%ISOPEN) THEN CLOSE C_VAL_EX_PROCESO_EN; END IF;
    IF (C_SINTOMA_MD%ISOPEN) THEN CLOSE C_SINTOMA_MD; END IF;

    FOR I IN C_PROCESOS_MD LOOP
        
        IF (C_VAL_EX_PROCESO_EN%ISOPEN) THEN CLOSE C_VAL_EX_PROCESO_EN; END IF;
        OPEN C_VAL_EX_PROCESO_EN(I.PROCESO_ID);
        FETCH C_VAL_EX_PROCESO_EN INTO LN_VAL_EX_PROCESO_EN;
        
        IF(LN_VAL_EX_PROCESO_EN = 0) THEN
            INSERT INTO DB_SOPORTE.ADMI_PROCESO_EMPRESA(ID_PROCESO_EMPRESA,PROCESO_ID,EMPRESA_COD,ESTADO,USR_CREACION,FE_CREACION)
            VALUES (DB_SOPORTE.SEQ_ADMI_PROCESO_EMPRESA.NEXTVAL, I.PROCESO_ID, 33, 'Activo', 'wbajana', SYSDATE);
            DBMS_OUTPUT.PUT_LINE('Se inserto 1 vez');
        END IF;

    END LOOP;
    
    COMMIT;
  
    FOR I IN C_SINTOMA_MD LOOP
        INSERT INTO DB_SOPORTE.ADMI_SINTOMA(ID_SINTOMA, NOMBRE_SINTOMA, DESCRIPCION_SINTOMA, ESTADO, USR_CREACION, FE_CREACION, USR_ULT_MOD, FE_ULT_MOD, EMPRESA_COD, TIPO_CASO_ID)
        VALUES (DB_SOPORTE.SEQ_ADMI_SINTOMA.NEXTVAL, I.NOMBRE_SINTOMA, I.DESCRIPCION_SINTOMA, 'Activo', 'wbajana', SYSDATE, 'wbajana', SYSDATE, '33', I.TIPO_CASO_ID);
    END LOOP;
  
    COMMIT;
    
END;
    
