CREATE  FORCE VIEW "NAF47_TNET"."ACOPLA_NAF" ("CUENTA_ACOPLA", "DESCRI_ACOPLA", "CUENTA_NAF", "DESCRI_NAF") AS 
  SELECT "CUENTA_ACOPLA",
           "DESCRI_ACOPLA",
           "CUENTA_NAF",
           "DESCRI_NAF"
      FROM NAF47_TNET.ACOPLA_NAF@GPOETNET;