CREATE  FORCE VIEW "NAF47_TNET"."ACT_DAV_TEMP" ("DESCRIPCION_COMERCIAL", "CODIGO", "CARACTERISITICAS") AS 
  SELECT "DESCRIPCION_COMERCIAL", "CODIGO", "CARACTERISITICAS"
      FROM NAF47_TNET.ACT_DAV_TEMP@GPOETNET;