CREATE  FORCE VIEW "NAF47_TNET"."ADMI_PROYECTO_REGION" ("ID_PROYECTO_REGION", "PROYECTO_ID", "REGION_ID", "ESTADO", "FE_CREACION", "USR_CREACION", "FE_ULT_MOD", "USR_ULT_MOD") AS 
  SELECT "ID_PROYECTO_REGION",
           "PROYECTO_ID",
           "REGION_ID",
           "ESTADO",
           "FE_CREACION",
           "USR_CREACION",
           "FE_ULT_MOD",
           "USR_ULT_MOD"
      FROM NAF47_TNET.ADMI_PROYECTO_REGION@GPOETNET;