CREATE  FORCE VIEW "NAF47_TNET"."ARAF_REGULA_CTA_PUENTE" ("NO_CIA", "TIPO", "CUENTA", "CENTRO_COSTO", "PORCENTAJE") AS 
  SELECT "NO_CIA",
           "TIPO",
           "CUENTA",
           "CENTRO_COSTO",
           "PORCENTAJE"
      FROM NAF47_TNET.ARAF_REGULA_CTA_PUENTE@GPOETNET;