CREATE  FORCE VIEW "NAF47_TNET"."ARANCELARTICULO" ("NO_CIA", "NO_ARTI", "COD_ARANCEL", "PRINCIPAL") AS 
  SELECT "NO_CIA",
           "NO_ARTI",
           "COD_ARANCEL",
           "PRINCIPAL"
      FROM NAF47_TNET.ARANCELARTICULO@GPOETNET;