CREATE  FORCE VIEW "NAF47_TNET"."ARCCRD_CONFIRMACION" ("NO_CIA", "CENTRO", "NO_SECUENCIA", "SECUENCIA_LOTE", "TIPO_DOC", "NO_FACTU", "MONTO", "DIVIDENDO", "IND_RETENCION", "NO_LINEA_RETENCION") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "NO_SECUENCIA",
           "SECUENCIA_LOTE",
           "TIPO_DOC",
           "NO_FACTU",
           "MONTO",
           "DIVIDENDO",
           "IND_RETENCION",
           "NO_LINEA_RETENCION"
      FROM NAF47_TNET.ARCCRD_CONFIRMACION@GPOETNET;