CREATE  FORCE VIEW "NAF47_TNET"."ARCCCC" ("NO_CIA", "GRUPO", "NO_CLIENTE", "CENTRO") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "NO_CLIENTE",
           "CENTRO"
      FROM NAF47_TNET.ARCCCC@GPOETNET;