CREATE  FORCE VIEW "NAF47_TNET"."ARCCMOTIVOS" ("NO_CIA", "MOTIVO", "DESC_MOTIVO", "CAMBIO_ESTADO_CLI", "PROTESTO_CK") AS 
  SELECT "NO_CIA",
           "MOTIVO",
           "DESC_MOTIVO",
           "CAMBIO_ESTADO_CLI",
           "PROTESTO_CK"
      FROM NAF47_TNET.ARCCMOTIVOS@GPOETNET;