CREATE  FORCE VIEW "NAF47_TNET"."ARCCSA_SUBCLIENTE" ("NO_CIA", "GRUPO", "NO_CLIENTE", "ANO", "MES", "MONEDA", "SALDO", "SUBCLIENTE") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "NO_CLIENTE",
           "ANO",
           "MES",
           "MONEDA",
           "SALDO",
           "SUBCLIENTE"
      FROM NAF47_TNET.ARCCSA_SUBCLIENTE@GPOETNET;