CREATE  FORCE VIEW "NAF47_TNET"."ARCC_MOT_RECHAZO" ("NO_CIA", "MOTIVO", "DESCRIPCION", "ESTADO") AS 
  SELECT "NO_CIA",
           "MOTIVO",
           "DESCRIPCION",
           "ESTADO"
      FROM NAF47_TNET.ARCC_MOT_RECHAZO@GPOETNET;