CREATE  FORCE VIEW "NAF47_TNET"."ARCCTE" ("NO_CIA", "TIPO_DOC", "COD_ESTADO", "DESCRIPCION", "TIPO_ESTADO") AS 
  SELECT "NO_CIA",
           "TIPO_DOC",
           "COD_ESTADO",
           "DESCRIPCION",
           "TIPO_ESTADO"
      FROM NAF47_TNET.ARCCTE@GPOETNET;