CREATE  FORCE VIEW "NAF47_TNET"."ARCC_DEPOSITO_CONFIRMACION" ("NO_CIA", "CENTRO", "SECUENCIA_DEPOSITO", "TOTAL", "FECHA", "NO_DEPOSITO", "NO_BANCO", "NO_CTA", "NO_VENDEDOR") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "SECUENCIA_DEPOSITO",
           "TOTAL",
           "FECHA",
           "NO_DEPOSITO",
           "NO_BANCO",
           "NO_CTA",
           "NO_VENDEDOR"
      FROM NAF47_TNET.ARCC_DEPOSITO_CONFIRMACION@GPOETNET;