CREATE  FORCE VIEW "NAF47_TNET"."ARCCMS_SUBCLIENTE" ("NO_CIA", "GRUPO", "NO_CLIENTE", "MONEDA", "SALDO_MAX", "FECHA_MAX", "SALDO_ACTUAL", "SUBCLIENTE") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "NO_CLIENTE",
           "MONEDA",
           "SALDO_MAX",
           "FECHA_MAX",
           "SALDO_ACTUAL",
           "SUBCLIENTE"
      FROM NAF47_TNET.ARCCMS_SUBCLIENTE@GPOETNET;