CREATE  FORCE VIEW "NAF47_TNET"."ARCC_DIVIDENDOS" ("NO_CIA", "CENTRO", "TIPO_DOC", "NO_DOCU", "DIVIDENDO", "VALOR", "SALDO", "FECHA_VENCE", "VALOR_APLICA", "TSTAMP") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "TIPO_DOC",
           "NO_DOCU",
           "DIVIDENDO",
           "VALOR",
           "SALDO",
           "FECHA_VENCE",
           "VALOR_APLICA",
           "TSTAMP"
      FROM NAF47_TNET.ARCC_DIVIDENDOS@GPOETNET;