CREATE  FORCE VIEW "NAF47_TNET"."ARCCRD_DIVIDENDOS" ("NO_CIA", "TIPO_DOC", "NO_DOCU", "TIPO_REFE", "NO_REFE", "MONTO_REFE", "DIVIDENDO", "TSTAMP", "SALDO_PRORRATEADO", "FEC_APLIC") AS 
  SELECT "NO_CIA",
           "TIPO_DOC",
           "NO_DOCU",
           "TIPO_REFE",
           "NO_REFE",
           "MONTO_REFE",
           "DIVIDENDO",
           "TSTAMP",
           "SALDO_PRORRATEADO",
           "FEC_APLIC"
      FROM NAF47_TNET.ARCCRD_DIVIDENDOS@GPOETNET;