CREATE  FORCE VIEW "NAF47_TNET"."ARCC_AUTORIZA_FECHA_VENCE" ("NO_CIA", "CENTRO", "USUARIO", "MONTO_MAXIMO") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "USUARIO",
           "MONTO_MAXIMO"
      FROM NAF47_TNET.ARCC_AUTORIZA_FECHA_VENCE@GPOETNET;