CREATE  FORCE VIEW "NAF47_TNET"."ARCCRD_DIVIDENDOS_MANUAL" ("NO_CIA", "TIPO_DOC", "NO_DOCU", "TIPO_REFE", "NO_REFE", "MONTO_REFE", "DIVIDENDO", "TSTAMP") AS 
  SELECT "NO_CIA",
           "TIPO_DOC",
           "NO_DOCU",
           "TIPO_REFE",
           "NO_REFE",
           "MONTO_REFE",
           "DIVIDENDO",
           "TSTAMP"
      FROM NAF47_TNET.ARCCRD_DIVIDENDOS_MANUAL@GPOETNET;