CREATE  FORCE VIEW "NAF47_TNET"."ARCCTARJETA_CREDITO" ("NO_CIA", "CODIGO", "DESCRIPCION", "BANCO", "PORC_COMISION", "GRUPO_CLIENTE", "NO_CLIENTE", "TIPO_DOC_CXC", "CTA_COMISION") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "BANCO",
           "PORC_COMISION",
           "GRUPO_CLIENTE",
           "NO_CLIENTE",
           "TIPO_DOC_CXC",
           "CTA_COMISION"
      FROM NAF47_TNET.ARCCTARJETA_CREDITO@GPOETNET;