CREATE  FORCE VIEW "NAF47_TNET"."ARCCTR" ("NO_CIA", "NO_TALONARIO", "NO_DESDE", "NO_HASTA", "SERIE", "TIPO_CUSTODIO", "COD_CUSTODIO") AS 
  SELECT "NO_CIA",
           "NO_TALONARIO",
           "NO_DESDE",
           "NO_HASTA",
           "SERIE",
           "TIPO_CUSTODIO",
           "COD_CUSTODIO"
      FROM NAF47_TNET.ARCCTR@GPOETNET;