CREATE  FORCE VIEW "NAF47_TNET"."ARCC_CARTERA_VENCIDA" ("NO_CIA", "CENTRO", "CONCEPTO", "DOCUMENTO", "PORCENTAJE", "SALDO", "ACUMULADO", "TIPO_SALDO", "TOTAL_DOC") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "CONCEPTO",
           "DOCUMENTO",
           "PORCENTAJE",
           "SALDO",
           "ACUMULADO",
           "TIPO_SALDO",
           "TOTAL_DOC"
      FROM NAF47_TNET.ARCC_CARTERA_VENCIDA@GPOETNET;