CREATE  FORCE VIEW "NAF47_TNET"."ARCCPCK" ("NO_CIA", "CTA_TRANSITORIA_NOM", "TIPO_DOCND", "TIPO_DOCDP", "IND_GENERA_BANCOS", "TIPO_DOCMULTA") AS 
  SELECT "NO_CIA",
           "CTA_TRANSITORIA_NOM",
           "TIPO_DOCND",
           "TIPO_DOCDP",
           "IND_GENERA_BANCOS",
           "TIPO_DOCMULTA"
      FROM NAF47_TNET.ARCCPCK@GPOETNET;