

CREATE  FORCE VIEW "NAF47_TNET"."ARCCDIVIDENDO" ("NO_CIA", "DD_DIVIDENDO", "DD_CUOTAS", "CODIGO") AS 
  SELECT "NO_CIA",
           "DD_DIVIDENDO",
           "DD_CUOTAS",
           "CODIGO"
      FROM NAF47_TNET.ARCCDIVIDENDO@GPOETNET;