CREATE  FORCE VIEW "NAF47_TNET"."ARCCPLAZOS" ("NO_CIA", "CODIGO", "DESCRIPCION", "PLAZO", "DIVIDENDO", "ESTADO", "TIME_STAMP") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "PLAZO",
           "DIVIDENDO",
           "ESTADO",
           "TIME_STAMP"
      FROM NAF47_TNET.ARCCPLAZOS@GPOETNET;