CREATE  FORCE VIEW "NAF47_TNET"."ARCCTEMPORAL" ("NO_CIA", "NO_CENTRO", "GRUPO", "NO_CLIENTE", "MONTO", "SUBCLIENTE") AS 
  SELECT "NO_CIA",
           "NO_CENTRO",
           "GRUPO",
           "NO_CLIENTE",
           "MONTO",
           "SUBCLIENTE"
      FROM NAF47_TNET.ARCCTEMPORAL@GPOETNET;