CREATE  FORCE VIEW "NAF47_TNET"."ARCGCAI" ("NO_CIA", "ANO", "MES", "INDICE_ECONOMICO", "PROCESADO_CONTA", "PROCESADO_ACTIVOS") AS 
  SELECT "NO_CIA",
           "ANO",
           "MES",
           "INDICE_ECONOMICO",
           "PROCESADO_CONTA",
           "PROCESADO_ACTIVOS"
      FROM NAF47_TNET.ARCGCAI@GPOETNET;