CREATE  FORCE VIEW "NAF47_TNET"."ARCGCT_C" ("NO_CIA", "MODULO", "SUB_MODULO", "ANO_PROCE", "MES_PROCE", "FEC_ARRANQUE") AS 
  SELECT "NO_CIA",
           "MODULO",
           "SUB_MODULO",
           "ANO_PROCE",
           "MES_PROCE",
           "FEC_ARRANQUE"
      FROM NAF47_TNET.ARCGCT_C@GPOETNET;