CREATE  FORCE VIEW "NAF47_TNET"."ARCGMRT" ("NO_CIA", "CODIGO_RELACION", "MODULO", "NATURALEZA", "CONDICION_TRIBUTARIA_TER") AS 
  SELECT "NO_CIA",
           "CODIGO_RELACION",
           "MODULO",
           "NATURALEZA",
           "CONDICION_TRIBUTARIA_TER"
      FROM NAF47_TNET.ARCGMRT@GPOETNET;