CREATE  FORCE VIEW "NAF47_TNET"."ARCGGI" ("NO_CIA", "CODIGO_GRUPO", "DESCRIPCION", "PLAZO_ENTREGA_DIAS") AS 
  SELECT "NO_CIA",
           "CODIGO_GRUPO",
           "DESCRIPCION",
           "PLAZO_ENTREGA_DIAS"
      FROM NAF47_TNET.ARCGGI@GPOETNET;