CREATE  FORCE VIEW "NAF47_TNET"."ARCGCD" ("NO_CIA", "COD_DIARIO", "DESCRIPCION", "DESCRIPCION_MIGRA", "USA_MIGRA") AS 
  SELECT "NO_CIA",
           "COD_DIARIO",
           "DESCRIPCION",
           "DESCRIPCION_MIGRA",
           "USA_MIGRA"
      FROM NAF47_TNET.ARCGCD@GPOETNET;