CREATE  FORCE VIEW "NAF47_TNET"."ARCGTC" ("CLASE_CAMBIO", "FECHA", "TIPO_CAMBIO", "TIPO_CAMBIO_VENTA") AS 
  SELECT "CLASE_CAMBIO",
           "FECHA",
           "TIPO_CAMBIO",
           "TIPO_CAMBIO_VENTA"
      FROM NAF47_TNET.ARCGTC@GPOETNET;