CREATE  FORCE VIEW "NAF47_TNET"."ARCGTAI" ("NO_CIA", "CODIGO_AJUSTE", "INDICE_ECONOMICO", "COD_DIARIO") AS 
  SELECT "NO_CIA",
           "CODIGO_AJUSTE",
           "INDICE_ECONOMICO",
           "COD_DIARIO"
      FROM NAF47_TNET.ARCGTAI@GPOETNET;