CREATE  FORCE VIEW "NAF47_TNET"."ARCGHIMP" ("NO_CIA", "CLAVE", "ID_SEC", "FEC_DESDE", "PORCENTAJE") AS 
  SELECT "NO_CIA",
           "CLAVE",
           "ID_SEC",
           "FEC_DESDE",
           "PORCENTAJE"
      FROM NAF47_TNET.ARCGHIMP@GPOETNET;