CREATE  FORCE VIEW "NAF47_TNET"."ARCKCARGA_EXCEL_OTROSMOV" ("NO_CIA", "FECHA", "NO_FISICO", "COMENTARIO", "MONTO", "ID_CUENTA_CONTABLE", "ID_CENTRO_COSTO", "USUARIO_CREA") AS 
  SELECT "NO_CIA",
           "FECHA",
           "NO_FISICO",
           "COMENTARIO",
           "MONTO",
           "ID_CUENTA_CONTABLE",
           "ID_CENTRO_COSTO",
           "USUARIO_CREA"
      FROM NAF47_TNET.ARCKCARGA_EXCEL_OTROSMOV@GPOETNET;