CREATE  FORCE VIEW "NAF47_TNET"."ARCKTD" ("NO_CIA", "TIPO_DOC", "DESCRIP", "TIPO_MOV", "TIPO_COMPROBANTE", "FORMULARIO_CTRL", "NO_FISICO_REQUERIDO") AS 
  SELECT "NO_CIA",
           "TIPO_DOC",
           "DESCRIP",
           "TIPO_MOV",
           "TIPO_COMPROBANTE",
           "FORMULARIO_CTRL",
           "NO_FISICO_REQUERIDO"
      FROM NAF47_TNET.ARCKTD@GPOETNET;