CREATE  FORCE VIEW "NAF47_TNET"."ARCPGR" ("NO_CIA", "GRUPO", "DESCRIPCION", "CTA_PROVE", "CTA_DPP", "CTA_PROVE_DOL", "CTA_DPP_DOL", "CTA_ANTICIPO", "CUENTA_INVENTARIO") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "DESCRIPCION",
           "CTA_PROVE",
           "CTA_DPP",
           "CTA_PROVE_DOL",
           "CTA_DPP_DOL",
           "CTA_ANTICIPO",
           "CUENTA_INVENTARIO"
      FROM NAF47_TNET.ARCPGR@GPOETNET;