
CREATE  FORCE VIEW "NAF47_TNET"."ARCPMP_USUARIOS" ("NO_CIA", "NO_PROVE", "NO_EMPLE", "IND_PRINCIPAL") AS 
  SELECT "NO_CIA",
           "NO_PROVE",
           "NO_EMPLE",
           "IND_PRINCIPAL"
      FROM NAF47_TNET.ARCPMP_USUARIOS@GPOETNET;