CREATE  FORCE VIEW "NAF47_TNET"."ARCPREPORTE_SALDOS_ANTICIPOS" ("NO_CIA", "USUARIO", "CONSULTA", "SECUENCIA", "DATO") AS 
  SELECT "NO_CIA",
           "USUARIO",
           "CONSULTA",
           "SECUENCIA",
           "DATO"
      FROM NAF47_TNET.ARCPREPORTE_SALDOS_ANTICIPOS@GPOETNET;