CREATE  FORCE VIEW "NAF47_TNET"."ARCPCBP" ("NO_CIA", "NO_PROVE", "BANCO", "CTA_BANCARIA", "PRINCIPAL", "TIPO_CUENTA", "ID_BANCO_PROV") AS 
  SELECT "NO_CIA",
           "NO_PROVE",
           "BANCO",
           "CTA_BANCARIA",
           "PRINCIPAL",
           "TIPO_CUENTA",
           "ID_BANCO_PROV"
      FROM NAF47_TNET.ARCPCBP@GPOETNET;