CREATE  FORCE VIEW "NAF47_TNET"."ARCPCL" ("CLASE", "DESCRIP", "GLOSA_CHEQUE", "ACEPTA_CENTRO") AS 
  SELECT "CLASE",
           "DESCRIP",
           "GLOSA_CHEQUE",
           "ACEPTA_CENTRO"
      FROM NAF47_TNET.ARCPCL@GPOETNET;