
CREATE  FORCE VIEW "NAF47_TNET"."ARCPEQUIVALENCIA" ("NO_CIA", "COD_BCO_PRI", "COD_BCO_NAF", "COD_EQUI", "ESTADO", "USER_CREA", "TSTAMP") AS 
  SELECT "NO_CIA",
           "COD_BCO_PRI",
           "COD_BCO_NAF",
           "COD_EQUI",
           "ESTADO",
           "USER_CREA",
           "TSTAMP"
      FROM NAF47_TNET.ARCPEQUIVALENCIA@GPOETNET;