CREATE  FORCE VIEW "NAF47_TNET"."ARCPPR" ("NO_CIA", "IND_FORMA_RET", "TIPO_DOC_ND_RET", "FORMULARIO_BOLETAS", "BENEFICIARIO_RET", "TIPO_DOC_NC_RET") AS 
  SELECT "NO_CIA",
           "IND_FORMA_RET",
           "TIPO_DOC_ND_RET",
           "FORMULARIO_BOLETAS",
           "BENEFICIARIO_RET",
           "TIPO_DOC_NC_RET"
      FROM NAF47_TNET.ARCPPR@GPOETNET;