CREATE  FORCE VIEW "NAF47_TNET"."ARCSEAF" ("NO_CIA", "TIPO_ASIENTO", "COD_ASIENTO", "DESCRIPCION", "GLOSA", "ACTIVO", "T_DEBITOS", "T_CREDITOS") AS 
  SELECT "NO_CIA",
           "TIPO_ASIENTO",
           "COD_ASIENTO",
           "DESCRIPCION",
           "GLOSA",
           "ACTIVO",
           "T_DEBITOS",
           "T_CREDITOS"
      FROM NAF47_TNET.ARCSEAF@GPOETNET;