CREATE  FORCE VIEW "NAF47_TNET"."ARFALOTE_PICKING" ("NO_CIA", "NO_DOCU", "BODEGA", "NO_ARTI", "NO_LOTE", "UBICACION", "FECHA_VENCE", "CANT_SOLICITADA", "UNIDADES", "DISPONIBLES") AS 
  SELECT "NO_CIA",
           "NO_DOCU",
           "BODEGA",
           "NO_ARTI",
           "NO_LOTE",
           "UBICACION",
           "FECHA_VENCE",
           "CANT_SOLICITADA",
           "UNIDADES",
           "DISPONIBLES"
      FROM NAF47_TNET.ARFALOTE_PICKING@GPOETNET;