CREATE  FORCE VIEW "NAF47_TNET"."ARFA_RUTAS_DESPACHO" ("NO_CIA", "CENTRO", "COD_RUTA", "DESCRIPCION", "NO_EMPLE", "IND_ACTIVO", "TIME_STAMP") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "COD_RUTA",
           "DESCRIPCION",
           "NO_EMPLE",
           "IND_ACTIVO",
           "TIME_STAMP"
      FROM NAF47_TNET.ARFA_RUTAS_DESPACHO@GPOETNET;