CREATE  FORCE VIEW "NAF47_TNET"."ARFA_DEV_MOVIL" ("NO_CIA", "GRUPO", "NO_CLIENTE", "SUB_CLIENTE", "NO_VENDEDOR", "FECHA", "NUMERO_SECUENCIAL", "IND_PROCESADO") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "NO_CLIENTE",
           "SUB_CLIENTE",
           "NO_VENDEDOR",
           "FECHA",
           "NUMERO_SECUENCIAL",
           "IND_PROCESADO"
      FROM NAF47_TNET.ARFA_DEV_MOVIL@GPOETNET;