
CREATE  FORCE VIEW "NAF47_TNET"."ARFA_RUTA_ZONA" ("NO_CIA", "RUTA", "ZONA", "ESTADO", "FECHA_REGISTRO", "USUARIO", "TIME_STAMP") AS 
  SELECT "NO_CIA",
           "RUTA",
           "ZONA",
           "ESTADO",
           "FECHA_REGISTRO",
           "USUARIO",
           "TIME_STAMP"
      FROM NAF47_TNET.ARFA_RUTA_ZONA@GPOETNET;