CREATE  FORCE VIEW "NAF47_TNET"."ARFABULTOS" ("NO_CIA", "NO_FACTU", "BULTO", "PESO") AS 
  SELECT "NO_CIA",
           "NO_FACTU",
           "BULTO",
           "PESO"
      FROM NAF47_TNET.ARFABULTOS@GPOETNET;