CREATE  FORCE VIEW "NAF47_TNET"."ARFAMARGEN" ("NO_CIA", "CENTRO", "NO_ARTI", "DIVISION_COMERCIAL", "MARGEN_MINIMO") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "NO_ARTI",
           "DIVISION_COMERCIAL",
           "MARGEN_MINIMO"
      FROM NAF47_TNET.ARFAMARGEN@GPOETNET;