CREATE  FORCE VIEW "NAF47_TNET"."ARFA_VENTA_DIRECTA" ("NO_CIA", "CENTROD", "TIPO_DOC", "USUARIO", "FORMULARIO") AS 
  SELECT "NO_CIA",
           "CENTROD",
           "TIPO_DOC",
           "USUARIO",
           "FORMULARIO"
      FROM NAF47_TNET.ARFA_VENTA_DIRECTA@GPOETNET;