CREATE  FORCE VIEW "NAF47_TNET"."ARFAFT" ("NO_CIA", "CENTROD", "CENTROF", "TIPO_DOC", "FORMULARIO") AS 
  SELECT "NO_CIA",
           "CENTROD",
           "CENTROF",
           "TIPO_DOC",
           "FORMULARIO"
      FROM NAF47_TNET.ARFAFT@GPOETNET;