CREATE  FORCE VIEW "NAF47_TNET"."ARFA_DISTRIB_GRUPO" ("NO_CIA", "DIVISION", "SUBDIVISION", "GRUPO", "NO_CLIENTE", "NO_SUB_CLIENTE", "TIPO_CLIENTE", "ESTADO", "TSTAMP") AS 
  SELECT "NO_CIA",
           "DIVISION",
           "SUBDIVISION",
           "GRUPO",
           "NO_CLIENTE",
           "NO_SUB_CLIENTE",
           "TIPO_CLIENTE",
           "ESTADO",
           "TSTAMP"
      FROM NAF47_TNET.ARFA_DISTRIB_GRUPO@GPOETNET;