CREATE  FORCE VIEW "NAF47_TNET"."ARFA_TRANSP_CANTONES" ("NO_CIA", "NO_TRANSPORTE", "PAIS", "PROVINCIA", "CANTON", "TIME_STAMP", "USUARIO") AS 
  SELECT "NO_CIA",
           "NO_TRANSPORTE",
           "PAIS",
           "PROVINCIA",
           "CANTON",
           "TIME_STAMP",
           "USUARIO"
      FROM NAF47_TNET.ARFA_TRANSP_CANTONES@GPOETNET;