CREATE  FORCE VIEW "NAF47_TNET"."ARFA_DIV_COMERCIAL" ("NO_CIA", "CENTRO", "DIVISION", "DESCRIPCION", "CENTRO_COSTO", "MIN_DIAS_INACTIVO", "SERIE") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "DIVISION",
           "DESCRIPCION",
           "CENTRO_COSTO",
           "MIN_DIAS_INACTIVO",
           "SERIE"
      FROM NAF47_TNET.ARFA_DIV_COMERCIAL@GPOETNET;