CREATE  FORCE VIEW "NAF47_TNET"."ARFA_FORMA_PAGO" ("NO_CIA", "FORMA_PAGO", "DESCRIPCION", "USUARIO_CREA", "FECHA_CREACION", "ESTADO") AS 
  SELECT "NO_CIA",
           "FORMA_PAGO",
           "DESCRIPCION",
           "USUARIO_CREA",
           "FECHA_CREACION",
           "ESTADO"
      FROM NAF47_TNET.ARFA_FORMA_PAGO@GPOETNET;