
CREATE  FORCE VIEW "NAF47_TNET"."ARGECAN" ("PAIS", "PROVINCIA", "CANTON", "DESCRIPCION", "DIAS_ENTREGA", "CIUDAD_SRI") AS 
  SELECT "PAIS",
           "PROVINCIA",
           "CANTON",
           "DESCRIPCION",
           "DIAS_ENTREGA",
           "CIUDAD_SRI"
      FROM NAF47_TNET.ARGECAN@GPOETNET;