CREATE  FORCE VIEW "NAF47_TNET"."ARGETB" ("BANCO", "DESCRIPCION", "CODIGO_TERCERO", "CODIGO_BANCO", "RESTA_COMISION") AS 
  SELECT "BANCO",
           "DESCRIPCION",
           "CODIGO_TERCERO",
           "CODIGO_BANCO",
           "RESTA_COMISION"
      FROM NAF47_TNET.ARGETB@GPOETNET;