CREATE  FORCE VIEW "NAF47_TNET"."ARGEBAR" ("PAIS", "PROVINCIA", "CANTON", "DISTRITO", "BARRIO", "DESCRIPCION") AS 
  SELECT "PAIS",
           "PROVINCIA",
           "CANTON",
           "DISTRITO",
           "BARRIO",
           "DESCRIPCION"
      FROM NAF47_TNET.ARGEBAR@GPOETNET;