CREATE  FORCE VIEW "NAF47_TNET"."ARGEPAI" ("PAIS", "DESCRIPCION", "PAIS_CAE", "ID_TIPO_PAGO", "CODIGO_SRI", "ID_TIPO_REGIMEN", "DENOMINACION", "DOBLE_TRIBUTACION") AS 
  SELECT "PAIS",
           "DESCRIPCION",
           "PAIS_CAE",
           "ID_TIPO_PAGO",
           "CODIGO_SRI",
           "ID_TIPO_REGIMEN",
           "DENOMINACION",
           "DOBLE_TRIBUTACION"
      FROM NAF47_TNET.ARGEPAI@GPOETNET;