CREATE  FORCE VIEW "NAF47_TNET"."ARGEEG" ("LBL_NIVEL1", "LBL_NIVEL1_PL", "LBL_NIVEL2", "LBL_NIVEL2_PL", "LBL_NIVEL3", "LBL_NIVEL3_PL", "LBL_NIVEL4", "LBL_NIVEL4_PL") AS 
  SELECT "LBL_NIVEL1",
           "LBL_NIVEL1_PL",
           "LBL_NIVEL2",
           "LBL_NIVEL2_PL",
           "LBL_NIVEL3",
           "LBL_NIVEL3_PL",
           "LBL_NIVEL4",
           "LBL_NIVEL4_PL"
      FROM NAF47_TNET.ARGEEG@GPOETNET;