CREATE  FORCE VIEW "NAF47_TNET"."ARGETID" ("CODIGO", "DESCRIPCION", "ETIQUETA", "FORMATO", "DIGITO_VERIF", "SRI_IDENT", "TIPO_IDENTIFICACION_SRI") AS 
  SELECT "CODIGO",
           "DESCRIPCION",
           "ETIQUETA",
           "FORMATO",
           "DIGITO_VERIF",
           "SRI_IDENT",
           "TIPO_IDENTIFICACION_SRI"
      FROM NAF47_TNET.ARGETID@GPOETNET;