CREATE  FORCE VIEW "NAF47_TNET"."ARGECT" ("CODIGO_CONDICION", "DESCRIPCION", "NATURAL", "JURIDICA", "CONTRIBUYENTE_ESPECIAL", "SIN_LUCRO", "EXTRANJEROS") AS 
  SELECT "CODIGO_CONDICION",
           "DESCRIPCION",
           "NATURAL",
           "JURIDICA",
           "CONTRIBUYENTE_ESPECIAL",
           "SIN_LUCRO",
           "EXTRANJEROS"
      FROM NAF47_TNET.ARGECT@GPOETNET;