CREATE  FORCE VIEW "NAF47_TNET"."ARGEPRO" ("PAIS", "PROVINCIA", "DESCRIPCION", "PROVINCIA_SRI") AS 
  SELECT "PAIS",
           "PROVINCIA",
           "DESCRIPCION",
           "PROVINCIA_SRI"
      FROM NAF47_TNET.ARGEPRO@GPOETNET;