CREATE  FORCE VIEW "NAF47_TNET"."ARGEAC" ("SECTOR", "ACTIVIDAD", "DESCRIPCION", "PAIS", "PROVINCIA", "CANTON") AS 
  SELECT "SECTOR",
           "ACTIVIDAD",
           "DESCRIPCION",
           "PAIS",
           "PROVINCIA",
           "CANTON"
      FROM NAF47_TNET.ARGEAC@GPOETNET;