CREATE  FORCE VIEW "NAF47_TNET"."ARGEIMPO_TXT" ("ID", "TIME_STAMP", "NUM_LINEA", "HILERA") AS 
  SELECT "ID",
           "TIME_STAMP",
           "NUM_LINEA",
           "HILERA"
      FROM NAF47_TNET.ARGEIMPO_TXT@GPOETNET;