
CREATE  FORCE VIEW "NAF47_TNET"."ARGERG" ("NO_CIA", "NO_AUTORIZACION", "COD_TERCERO_PROVEEDOR_SW", "NO_LICENCIA", "FECHA_AUTORIZACION", "IND_RETENEDOR") AS 
  SELECT "NO_CIA",
           "NO_AUTORIZACION",
           "COD_TERCERO_PROVEEDOR_SW",
           "NO_LICENCIA",
           "FECHA_AUTORIZACION",
           "IND_RETENEDOR"
      FROM NAF47_TNET.ARGERG@GPOETNET;