
CREATE  FORCE VIEW "NAF47_TNET"."ARIMHISTORICO_PRECIO" ("NO_CIA", "NO_PROVE", "NO_ARTI", "PRECIO_ANTERIOR", "PRECIO_NUEVO", "USUARIO", "FECHA_RIGE") AS 
  SELECT "NO_CIA",
           "NO_PROVE",
           "NO_ARTI",
           "PRECIO_ANTERIOR",
           "PRECIO_NUEVO",
           "USUARIO",
           "FECHA_RIGE"
      FROM NAF47_TNET.ARIMHISTORICO_PRECIO@GPOETNET;