CREATE  FORCE VIEW "NAF47_TNET"."ARIMREPFAC" ("NO_FISICO", "NO_ARTI", "CANTIDAD", "NO_EMBARQUE") AS 
  SELECT "NO_FISICO",
           "NO_ARTI",
           "CANTIDAD",
           "NO_EMBARQUE"
      FROM NAF47_TNET.ARIMREPFAC@GPOETNET;