CREATE  FORCE VIEW "NAF47_TNET"."ARIMIMPCALCULO" ("NO_CIA", "NO_EMBARQUE", "NO_ARTI", "ARTI_PROVE", "DESCRIPCION", "CANTIDAD", "IMPUESTO", "TARIFA", "CANT_PARCIAL") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "NO_ARTI",
           "ARTI_PROVE",
           "DESCRIPCION",
           "CANTIDAD",
           "IMPUESTO",
           "TARIFA",
           "CANT_PARCIAL"
      FROM NAF47_TNET.ARIMIMPCALCULO@GPOETNET;