CREATE  FORCE VIEW "NAF47_TNET"."ARIMPEDIDO" ("NO_CIA", "CODIGO_ARTICULO", "CANTIDAD_PEDIDA_USUARIO") AS 
  SELECT "NO_CIA", "CODIGO_ARTICULO", "CANTIDAD_PEDIDA_USUARIO"
      FROM NAF47_TNET.ARIMPEDIDO@GPOETNET;