
CREATE  FORCE VIEW "NAF47_TNET"."ARIMCONEMBARQUE" ("NO_CIA", "NO_EMBARQUE", "TIPO_CONTENEDOR", "NO_CONTENEDOR") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "TIPO_CONTENEDOR",
           "NO_CONTENEDOR"
      FROM NAF47_TNET.ARIMCONEMBARQUE@GPOETNET;