CREATE  FORCE VIEW "NAF47_TNET"."ARIMDETPEDNOINV" ("NO_CIA", "NO_PEDIDO", "NO_ARTI", "DESCRIPCION", "CANTIDAD_PEDIDA") AS 
  SELECT "NO_CIA",
           "NO_PEDIDO",
           "NO_ARTI",
           "DESCRIPCION",
           "CANTIDAD_PEDIDA"
      FROM NAF47_TNET.ARIMDETPEDNOINV@GPOETNET;