CREATE  FORCE VIEW "NAF47_TNET"."ARIMEMPAQUE" ("NO_CIA", "CODIGO", "DESCRIPCION", "MODULO") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "MODULO"
      FROM NAF47_TNET.ARIMEMPAQUE@GPOETNET;