CREATE  FORCE VIEW "NAF47_TNET"."ARIMLINEASGASTO" ("NO_CIA", "NUM_FAC", "CODIGO", "NO_ARTI") AS 
  SELECT "NO_CIA",
           "NUM_FAC",
           "CODIGO",
           "NO_ARTI"
      FROM NAF47_TNET.ARIMLINEASGASTO@GPOETNET;