
CREATE  FORCE VIEW "NAF47_TNET"."ARIMDIANAVIERA" ("NO_CIA", "CODIGO", "DIA_EMBARQUE", "TIPO_TRANS", "CODIGO_PUERTO", "LEAD_TIME", "PRINCIPAL") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DIA_EMBARQUE",
           "TIPO_TRANS",
           "CODIGO_PUERTO",
           "LEAD_TIME",
           "PRINCIPAL"
      FROM NAF47_TNET.ARIMDIANAVIERA@GPOETNET;