
CREATE  FORCE VIEW "NAF47_TNET"."ARIMARANCEL_ANTERIOR" ("COD_ARANCEL", "POR_ARANCEL", "DESCRIPCION", "DIGITO", "SEGURO", "FLETE") AS 
  SELECT "COD_ARANCEL",
           "POR_ARANCEL",
           "DESCRIPCION",
           "DIGITO",
           "SEGURO",
           "FLETE"
      FROM NAF47_TNET.ARIMARANCEL_ANTERIOR@GPOETNET;