CREATE  FORCE VIEW "NAF47_TNET"."ARIMTIPOCARGASUELTA" ("NO_CIA", "TIPO_CARGA_SUELTA", "DESCRIPCION") AS 
  SELECT "NO_CIA", "TIPO_CARGA_SUELTA", "DESCRIPCION"
      FROM NAF47_TNET.ARIMTIPOCARGASUELTA@GPOETNET;