CREATE  FORCE VIEW "NAF47_TNET"."ARIMCONTENEDOR" ("NO_CIA", "CODIGO", "DESCRIPCION", "CUBICAJE", "PESO") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "CUBICAJE",
           "PESO"
      FROM NAF47_TNET.ARIMCONTENEDOR@GPOETNET;