CREATE  FORCE VIEW "NAF47_TNET"."ARIMTF" ("NO_CIA", "TIPO_FAC", "DESCRIPCION", "IND_ESTIMADO", "USUARIO_CXP", "IND_ARTI", "COD_DIARIO", "IND_REPLICAR", "IND_ACTIVO") AS 
  SELECT "NO_CIA",
           "TIPO_FAC",
           "DESCRIPCION",
           "IND_ESTIMADO",
           "USUARIO_CXP",
           "IND_ARTI",
           "COD_DIARIO",
           "IND_REPLICAR",
           "IND_ACTIVO"
      FROM NAF47_TNET.ARIMTF@GPOETNET;