
CREATE  FORCE VIEW "NAF47_TNET"."ARIMENCOSTEO" ("NO_CIA", "NO_EMBARQUE", "FECHA_CREACION", "USUARIO_CREACION") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "FECHA_CREACION",
           "USUARIO_CREACION"
      FROM NAF47_TNET.ARIMENCOSTEO@GPOETNET;