CREATE  FORCE VIEW "NAF47_TNET"."ARIMCARGASUELTA" ("NO_CIA", "NO_EMBARQUE", "TIPO_CARGA_SUELTA", "NO_CONTENEDOR", "CANTIDAD", "CUBICAJE", "PESO") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "TIPO_CARGA_SUELTA",
           "NO_CONTENEDOR",
           "CANTIDAD",
           "CUBICAJE",
           "PESO"
      FROM NAF47_TNET.ARIMCARGASUELTA@GPOETNET;