CREATE  FORCE VIEW "NAF47_TNET"."ARIM_RESTRIC_ARANCEL" ("NO_CIA", "COD_RES", "TIPO", "RESTRIC", "ESTADO") AS 
  SELECT "NO_CIA",
           "COD_RES",
           "TIPO",
           "RESTRIC",
           "ESTADO"
      FROM NAF47_TNET.ARIM_RESTRIC_ARANCEL@GPOETNET;