CREATE  FORCE VIEW "NAF47_TNET"."ARIMDETEMBFAC" ("NO_CIA", "NO_EMBARQUE", "NO_PROVE", "NO_ORDEN", "NUM_FACTU", "EMBARQUE", "CERTIFICADO_INSPECCION") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "NO_PROVE",
           "NO_ORDEN",
           "NUM_FACTU",
           "EMBARQUE",
           "CERTIFICADO_INSPECCION"
      FROM NAF47_TNET.ARIMDETEMBFAC@GPOETNET;