
CREATE  FORCE VIEW "NAF47_TNET"."ARIM_AUDIT_RECOSTEO" ("NO_CIA", "NO_EMBARQUE", "FECHA", "USUARIO") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "FECHA",
           "USUARIO"
      FROM NAF47_TNET.ARIM_AUDIT_RECOSTEO@GPOETNET;