CREATE  FORCE VIEW "NAF47_TNET"."ARIMPUERTO_EMBARQUE" ("CODIGO_PUERTO", "DESCRIPCION", "CODIGO_CAE", "PAIS_CAE") AS 
  SELECT "CODIGO_PUERTO",
           "DESCRIPCION",
           "CODIGO_CAE",
           "PAIS_CAE"
      FROM NAF47_TNET.ARIMPUERTO_EMBARQUE@GPOETNET;