
CREATE  FORCE VIEW "NAF47_TNET"."ARIMHISCALCULO" ("NO_CIA", "NO_EMBARQUE", "NUM_FAC", "SER_PROVE", "TIPO_CAMBIO", "FECHA") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "NUM_FAC",
           "SER_PROVE",
           "TIPO_CAMBIO",
           "FECHA"
      FROM NAF47_TNET.ARIMHISCALCULO@GPOETNET;