CREATE  FORCE VIEW "NAF47_TNET"."ARIMFACNOCALCULO" ("NO_CIA", "NO_EMBARQUE", "NUM_FAC", "SER_PROVE") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "NUM_FAC",
           "SER_PROVE"
      FROM NAF47_TNET.ARIMFACNOCALCULO@GPOETNET;