CREATE  FORCE VIEW "NAF47_TNET"."ARIMLINGASTO" ("NO_CIA", "NUM_FAC", "CODIGO", "NO_ARTI", "ARTI_PROVE") AS 
  SELECT "NO_CIA",
           "NUM_FAC",
           "CODIGO",
           "NO_ARTI",
           "ARTI_PROVE"
      FROM NAF47_TNET.ARIMLINGASTO@GPOETNET;