CREATE  FORCE VIEW "NAF47_TNET"."ARIMFO_ARTI" ("NO_CIA", "NUM_FACO", "NO_ARTI", "MONTO_REFE") AS 
  SELECT "NO_CIA",
           "NUM_FACO",
           "NO_ARTI",
           "MONTO_REFE"
      FROM NAF47_TNET.ARIMFO_ARTI@GPOETNET;