

CREATE  FORCE VIEW "NAF47_TNET"."ARIMTIPOCARTACREDITO" ("NO_CIA", "TIPO_CARTA_CREDITO", "DESCRIPCION") AS 
  SELECT "NO_CIA", "TIPO_CARTA_CREDITO", "DESCRIPCION"
      FROM NAF47_TNET.ARIMTIPOCARTACREDITO@GPOETNET;