CREATE  FORCE VIEW "NAF47_TNET"."ARIMARANCEL_SALVAG" ("NO_CIA", "COD_ARANCEL", "COD_PAIS", "SALVAG") AS 
  SELECT "NO_CIA",
           "COD_ARANCEL",
           "COD_PAIS",
           "SALVAG"
      FROM NAF47_TNET.ARIMARANCEL_SALVAG@GPOETNET;