
CREATE  FORCE VIEW "NAF47_TNET"."ARIMTIPOFORMAPAGO" ("NO_CIA", "CODIGO", "DESCRIPCION", "MODULO", "APLICA_CARTA_CRED") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "MODULO",
           "APLICA_CARTA_CRED"
      FROM NAF47_TNET.ARIMTIPOFORMAPAGO@GPOETNET;