CREATE  FORCE VIEW "NAF47_TNET"."ARIMCLAVES" ("NO_CIA", "CLAVE", "NOMBRE", "ACTIVO", "USUARIO") AS 
  SELECT "NO_CIA",
           "CLAVE",
           "NOMBRE",
           "ACTIVO",
           "USUARIO"
      FROM NAF47_TNET.ARIMCLAVES@GPOETNET;