CREATE  FORCE VIEW "NAF47_TNET"."ARIMREFE_NOTACREDITO" ("NO_CIA", "TIPO_FAC", "NUM_FAC", "TIPO_REFE", "NUM_REFE", "MONTO_REFE", "MONTO_REFE_OM", "MONTO_REFE_GASTO", "MONTO_REFE_GASTO_OM") AS 
  SELECT "NO_CIA",
           "TIPO_FAC",
           "NUM_FAC",
           "TIPO_REFE",
           "NUM_REFE",
           "MONTO_REFE",
           "MONTO_REFE_OM",
           "MONTO_REFE_GASTO",
           "MONTO_REFE_GASTO_OM"
      FROM NAF47_TNET.ARIMREFE_NOTACREDITO@GPOETNET;