CREATE  FORCE VIEW "NAF47_TNET"."ARIN_PERFIL_OBJETO" ("ID_PERFIL_OBJETO", "PERFIL_ID", "ID_OBJETO", "EMPRESA_OBJETO_ID", "ESTADO", "USR_CREACION", "FE_CREACION", "USR_ULT_MOD", "FE_ULT_MOD") AS 
  SELECT "ID_PERFIL_OBJETO",
           "PERFIL_ID",
           "ID_OBJETO",
           "EMPRESA_OBJETO_ID",
           "ESTADO",
           "USR_CREACION",
           "FE_CREACION",
           "USR_ULT_MOD",
           "FE_ULT_MOD"
      FROM NAF47_TNET.ARIN_PERFIL_OBJETO@GPOETNET;