CREATE  FORCE VIEW "NAF47_TNET"."ARINBOGUIA_REMI" ("NO_CIA", "CODIGO", "TIPO_TRANSFERENCIA", "TIPO_FACTURA", "CODIGO_BLOCK", "ACTIVO") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "TIPO_TRANSFERENCIA",
           "TIPO_FACTURA",
           "CODIGO_BLOCK",
           "ACTIVO"
      FROM NAF47_TNET.ARINBOGUIA_REMI@GPOETNET;