CREATE  FORCE VIEW "NAF47_TNET"."ARINSUBDIV" ("NO_CIA", "DIVISION", "SUBDIVISION", "DESCRIPCION", "TIME_STAMP", "ESTADO") AS 
  SELECT "NO_CIA",
           "DIVISION",
           "SUBDIVISION",
           "DESCRIPCION",
           "TIME_STAMP",
           "ESTADO"
      FROM NAF47_TNET.ARINSUBDIV@GPOETNET;