CREATE  FORCE VIEW "NAF47_TNET"."ARINSOL_DETTRA" ("NO_CIA", "NO_DOCU", "NO_ARTI", "CANTIDAD", "COSTO", "FECHA_INSERT", "USUARIO_INSERT", "FECHA_UPDATE", "USUARIO_UPDATE") AS 
  SELECT "NO_CIA",
           "NO_DOCU",
           "NO_ARTI",
           "CANTIDAD",
           "COSTO",
           "FECHA_INSERT",
           "USUARIO_INSERT",
           "FECHA_UPDATE",
           "USUARIO_UPDATE"
      FROM NAF47_TNET.ARINSOL_DETTRA@GPOETNET;