CREATE  FORCE VIEW "NAF47_TNET"."ARINCCL" ("TIPO_CLASIF", "COD_CLASIF", "COD_CLASIF_PADRE", "NIVEL", "DESCRIPCION", "TSTAMP", "ULTIMO_NIVEL") AS 
  SELECT "TIPO_CLASIF",
           "COD_CLASIF",
           "COD_CLASIF_PADRE",
           "NIVEL",
           "DESCRIPCION",
           "TSTAMP",
           "ULTIMO_NIVEL"
      FROM NAF47_TNET.ARINCCL@GPOETNET;