CREATE  FORCE VIEW "NAF47_TNET"."ARIN_TIPO_CARACTERISTICA" ("SECUENCIA", "DESCRIPCION", "ESTADO", "USUARIO_CREACION", "FECHA_CREACION", "USUARIO_MODIFICACION", "FECHA_MODIFICACION") AS 
  SELECT "SECUENCIA",
           "DESCRIPCION",
           "ESTADO",
           "USUARIO_CREACION",
           "FECHA_CREACION",
           "USUARIO_MODIFICACION",
           "FECHA_MODIFICACION"
      FROM NAF47_TNET.ARIN_TIPO_CARACTERISTICA@GPOETNET;