CREATE  FORCE VIEW "NAF47_TNET"."ARINGMROI_TMP" ("FECHA1", "FECHA2", "CLASE", "CATEGORIA", "NO_ARTI", "ULTIMO_COSTO", "INVENTARIO_INICIAL", "INVENTARIO_FINAL") AS 
  SELECT "FECHA1",
           "FECHA2",
           "CLASE",
           "CATEGORIA",
           "NO_ARTI",
           "ULTIMO_COSTO",
           "INVENTARIO_INICIAL",
           "INVENTARIO_FINAL"
      FROM NAF47_TNET.ARINGMROI_TMP@GPOETNET;