CREATE  FORCE VIEW "NAF47_TNET"."ARINPARAMGEN" ("NO_CIA", "VARIABLE", "DESCRIPCION", "VALOR", "PROCESA_MANUAL") AS 
  SELECT "NO_CIA",
           "VARIABLE",
           "DESCRIPCION",
           "VALOR",
           "PROCESA_MANUAL"
      FROM NAF47_TNET.ARINPARAMGEN@GPOETNET;