CREATE  FORCE VIEW "NAF47_TNET"."ARINDP" ("NO_CIA", "TIPO", "DESCRIPCION", "INCLUYE_IMP", "TSTAMP") AS 
  SELECT "NO_CIA",
           "TIPO",
           "DESCRIPCION",
           "INCLUYE_IMP",
           "TSTAMP"
      FROM NAF47_TNET.ARINDP@GPOETNET;