CREATE  FORCE VIEW "NAF47_TNET"."ARINTCL" ("TIPO_CLASIF", "DESCRIPCION", "MASCARA", "IND_JERARQUICO", "IND_MOV_ULTIMO_NIVEL", "TSTAMP") AS 
  SELECT "TIPO_CLASIF",
           "DESCRIPCION",
           "MASCARA",
           "IND_JERARQUICO",
           "IND_MOV_ULTIMO_NIVEL",
           "TSTAMP"
      FROM NAF47_TNET.ARINTCL@GPOETNET;