CREATE  FORCE VIEW "NAF47_TNET"."ARINENC_SUGERID" ("NO_CIA", "NO_DOCU", "FECHA", "NO_PROVE", "FECHA_PEDIDO", "FECHA_NO_REVISADO", "ESTADO") AS 
  SELECT "NO_CIA",
           "NO_DOCU",
           "FECHA",
           "NO_PROVE",
           "FECHA_PEDIDO",
           "FECHA_NO_REVISADO",
           "ESTADO"
      FROM NAF47_TNET.ARINENC_SUGERID@GPOETNET;