CREATE  FORCE VIEW "NAF47_TNET"."ARIN_PARAMETRO" ("ID_PARAMETRO", "EMPRESA_ID", "DESCRIPCION", "CLASE", "ESTADO", "USR_CREACION", "FE_CREACION", "IP_CREACION", "USR_ULT_MOD", "FE_ULT_MOD") AS 
  SELECT "ID_PARAMETRO",
           "EMPRESA_ID",
           "DESCRIPCION",
           "CLASE",
           "ESTADO",
           "USR_CREACION",
           "FE_CREACION",
           "IP_CREACION",
           "USR_ULT_MOD",
           "FE_ULT_MOD"
      FROM NAF47_TNET.ARIN_PARAMETRO@GPOETNET;