CREATE  FORCE VIEW "NAF47_TNET"."ARIN_CARACTERISTICA_ARTICULO" ("NO_CIA", "NO_ARTICULO", "ID_CARACTERISTICA", "ESTADO", "USUARIO_CREACION", "FECHA_CREACION", "USUARIO_MODIFICACION", "FECHA_MODIFICACION") AS 
  SELECT "NO_CIA",
           "NO_ARTICULO",
           "ID_CARACTERISTICA",
           "ESTADO",
           "USUARIO_CREACION",
           "FECHA_CREACION",
           "USUARIO_MODIFICACION",
           "FECHA_MODIFICACION"
      FROM NAF47_TNET.ARIN_CARACTERISTICA_ARTICULO@GPOETNET;