CREATE  FORCE VIEW "NAF47_TNET"."ARIN_ARTI_RECU_PRE_TMP" ("ID_EMPRESA", "ID_ARTICULO", "ID_REGION", "REGLA", "BODEGA", "STOCK_MINIMO", "STOCK_MAXIMO", "MOTIVO") AS 
  SELECT "ID_EMPRESA","ID_ARTICULO","ID_REGION","REGLA","BODEGA","STOCK_MINIMO","STOCK_MAXIMO","MOTIVO"
FROM NAF47_TNET.ARIN_ARTI_RECU_PRE_TMP@GPOETNET;