CREATE  FORCE VIEW "NAF47_TNET"."ARINIA" ("NO_CIA", "NO_ARTI", "CLAVE", "AFECTA_COMPRA", "AFECTA_VENTA") AS 
  SELECT "NO_CIA",
           "NO_ARTI",
           "CLAVE",
           "AFECTA_COMPRA",
           "AFECTA_VENTA"
      FROM NAF47_TNET.ARINIA@GPOETNET;