CREATE  FORCE VIEW "NAF47_TNET"."ARINULTCOSTO" ("NO_CIA", "ANIO", "MES", "NO_ARTI", "ULTIMO_COSTO") AS 
  SELECT "NO_CIA",
           "ANIO",
           "MES",
           "NO_ARTI",
           "ULTIMO_COSTO"
      FROM NAF47_TNET.ARINULTCOSTO@GPOETNET;