CREATE  FORCE VIEW "NAF47_TNET"."ARIN_UNIFICAR_ARTICULO" ("NO_CIA", "NO_ARTI", "DESC_NO_ARTI", "NO_ARTI_UNIFICADO", "DESC_NO_ARTI_UNIFICADO", "FE_CREACION", "ESTADO", "USUARIO_PROCESO", "FE_PROCESO") AS 
  SELECT "NO_CIA",
           "NO_ARTI",
           "DESC_NO_ARTI",
           "NO_ARTI_UNIFICADO",
           "DESC_NO_ARTI_UNIFICADO",
           "FE_CREACION",
           "ESTADO",
           "USUARIO_PROCESO",
           "FE_PROCESO"
      FROM NAF47_TNET.ARIN_UNIFICAR_ARTICULO@GPOETNET;