CREATE  FORCE VIEW "NAF47_TNET"."ARIN_REUBICACION" ("NO_CIA", "CENTRO", "BODEGA", "UBC_ANTERIOR", "UBC_NUEVA", "NO_ARTI", "SERIE", "USUARIO", "FECHA_REASIGNA") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "BODEGA",
           "UBC_ANTERIOR",
           "UBC_NUEVA",
           "NO_ARTI",
           "SERIE",
           "USUARIO",
           "FECHA_REASIGNA"
      FROM NAF47_TNET.ARIN_REUBICACION@GPOETNET;