CREATE  FORCE VIEW "NAF47_TNET"."ARINDET_SOLICITUD" ("NO_CIA", "NO_DOCU", "NO_ARTI", "CANTIDAD") AS 
  SELECT "NO_CIA",
           "NO_DOCU",
           "NO_ARTI",
           "CANTIDAD"
      FROM NAF47_TNET.ARINDET_SOLICITUD@GPOETNET;