CREATE  FORCE VIEW "NAF47_TNET"."ARINSUBDIV_TEMP" ("NO_CIA", "MARCA", "DIVISION", "DIVISION_ANT", "SUBDIVISION", "SUBDIVISION1", "SUBDIVISION2", "DESCRIPCION") AS 
  SELECT "NO_CIA",
           "MARCA",
           "DIVISION",
           "DIVISION_ANT",
           "SUBDIVISION",
           "SUBDIVISION1",
           "SUBDIVISION2",
           "DESCRIPCION"
      FROM NAF47_TNET.ARINSUBDIV_TEMP@GPOETNET;