
CREATE  FORCE VIEW "NAF47_TNET"."ARINPARAMETROS_GMROI" ("NO_CIA", "PORCENTAJE", "CODIGO", "TIPO") AS 
  SELECT "NO_CIA",
           "PORCENTAJE",
           "CODIGO",
           "TIPO"
      FROM NAF47_TNET.ARINPARAMETROS_GMROI@GPOETNET;