
CREATE  FORCE VIEW "NAF47_TNET"."ARINIC" ("NO_CIA", "CLASE", "CLAVE", "AFECTA_COMPRA", "AFECTA_VENTA") AS 
  SELECT "NO_CIA",
           "CLASE",
           "CLAVE",
           "AFECTA_COMPRA",
           "AFECTA_VENTA"
      FROM NAF47_TNET.ARINIC@GPOETNET;