CREATE  FORCE VIEW "NAF47_TNET"."ARIN_PERFIL_EMPLEADO" ("ID_PERFIL_EMPLEADO", "PERFIL_ID", "ID_EMPLEADO", "EMPRESA_EMPLEADO_ID", "ESTADO", "USR_CREACION", "FE_CREACION", "USR_ULT_MOD", "FE_ULT_MOD") AS 
  SELECT "ID_PERFIL_EMPLEADO",
           "PERFIL_ID",
           "ID_EMPLEADO",
           "EMPRESA_EMPLEADO_ID",
           "ESTADO",
           "USR_CREACION",
           "FE_CREACION",
           "USR_ULT_MOD",
           "FE_ULT_MOD"
      FROM NAF47_TNET.ARIN_PERFIL_EMPLEADO@GPOETNET;