CREATE  FORCE VIEW "NAF47_TNET"."ARIN_CATALOGO_KATUK_CAB" ("ID_CATALOGO", "NOMBRE", "NIVEL", "TIPO", "CODIGO", "ESTADO", "FECHA_CREACION", "USUARIO_CREACION", "FECHA_ACTUALIZA", "USUARIO_ACTUALIZA") AS 
  SELECT "ID_CATALOGO","NOMBRE","NIVEL","TIPO","CODIGO","ESTADO","FECHA_CREACION","USUARIO_CREACION","FECHA_ACTUALIZA","USUARIO_ACTUALIZA"
FROM NAF47_TNET.ARIN_CATALOGO_KATUK_CAB@GPOETNET;