CREATE  FORCE VIEW "NAF47_TNET"."ARINCA" ("NO_CIA", "CODIGO", "DESCRIPCION", "CONTROL_ESTAD", "APLICA_IMPUESTO", "PORC_INV_SEGURIDAD", "IND_MAT_PUB") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "CONTROL_ESTAD",
           "APLICA_IMPUESTO",
           "PORC_INV_SEGURIDAD",
           "IND_MAT_PUB"
      FROM NAF47_TNET.ARINCA@GPOETNET;