CREATE  FORCE VIEW "NAF47_TNET"."ARINCAT" ("NO_CIA", "CLASE", "CODIGO", "DESCRIPCION") AS 
  SELECT "NO_CIA",
           "CLASE",
           "CODIGO",
           "DESCRIPCION"
      FROM NAF47_TNET.ARINCAT@GPOETNET;