CREATE  FORCE VIEW "NAF47_TNET"."ARINII" ("ID_RAZON", "TIPO_MOV", "INTERFACE", "DESCRIPCION") AS 
  SELECT "ID_RAZON",
           "TIPO_MOV",
           "INTERFACE",
           "DESCRIPCION"
      FROM NAF47_TNET.ARINII@GPOETNET;