CREATE  FORCE VIEW "NAF47_TNET"."ARINENCOPCIONPRODUCCION" ("NO_CIA", "CODIGO", "NO_ARTI", "ARMAR", "OBSERVACION", "FECHA", "USUARIO", "ESTADO", "TIMESTAMP") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "NO_ARTI",
           "ARMAR",
           "OBSERVACION",
           "FECHA",
           "USUARIO",
           "ESTADO",
           "TIMESTAMP"
      FROM NAF47_TNET.ARINENCOPCIONPRODUCCION@GPOETNET;