CREATE  FORCE VIEW "NAF47_TNET"."ARINDET_SUGERID" ("NO_CIA", "NO_DOCU", "BODEGA", "NO_ARTI", "SUGERIDO", "CONFIRMADO", "NO_LINEA", "CRITICIDAD") AS 
  SELECT "NO_CIA",
           "NO_DOCU",
           "BODEGA",
           "NO_ARTI",
           "SUGERIDO",
           "CONFIRMADO",
           "NO_LINEA",
           "CRITICIDAD"
      FROM NAF47_TNET.ARINDET_SUGERID@GPOETNET;