CREATE  FORCE VIEW "NAF47_TNET"."ARIN_ARTICULOS_GUIA" ("NO_CIA", "NO_ARTI", "DESCRIPCION", "SECUENCIA", "FECHA_CREACION", "USUARIO_CREACION", "FECHA_ACTUALIZACION", "USUARIO_ACTUALIZACION", "ESTADO") AS 
  SELECT "NO_CIA",
           "NO_ARTI",
           "DESCRIPCION",
           "SECUENCIA",
           "FECHA_CREACION",
           "USUARIO_CREACION",
           "FECHA_ACTUALIZACION",
           "USUARIO_ACTUALIZACION",
           "ESTADO"
      FROM NAF47_TNET.ARIN_ARTICULOS_GUIA@GPOETNET;