CREATE  FORCE VIEW "NAF47_TNET"."ARINDETREORDEN_RESP" ("NO_CIA", "ORDEN_TRABAJO", "OPCION", "NO_ARTI", "PORC_DISTRIBUCION", "CANTIDAD") AS 
  SELECT "NO_CIA",
           "ORDEN_TRABAJO",
           "OPCION",
           "NO_ARTI",
           "PORC_DISTRIBUCION",
           "CANTIDAD"
      FROM NAF47_TNET.ARINDETREORDEN_RESP@GPOETNET;