CREATE  FORCE VIEW "NAF47_TNET"."ARINDETOPCIONPRODUCCION" ("NO_CIA", "CODIGO", "OPCION", "NO_ARTI", "PORC_DISTRIBUCION", "CANTIDAD") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "OPCION",
           "NO_ARTI",
           "PORC_DISTRIBUCION",
           "CANTIDAD"
      FROM NAF47_TNET.ARINDETOPCIONPRODUCCION@GPOETNET;