CREATE  FORCE VIEW "NAF47_TNET"."ARINENCREOR_LOTE" ("NO_CIA", "CENTRO", "NO_DOCU", "BODEGA", "NO_ARTI", "NO_LOTE", "UBICACION", "CANTIDAD", "FECHA_VENCE") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "NO_DOCU",
           "BODEGA",
           "NO_ARTI",
           "NO_LOTE",
           "UBICACION",
           "CANTIDAD",
           "FECHA_VENCE"
      FROM NAF47_TNET.ARINENCREOR_LOTE@GPOETNET;