CREATE  FORCE VIEW "NAF47_TNET"."ARIN_ARTI_RECU_TMP" ("ID_EMPRESA", "ID_ARTICULO", "ID_REGION", "CANTIDAD_MINIMA", "CANTIDAD_MAXIMA", "MOTIVO") AS 
  SELECT "ID_EMPRESA","ID_ARTICULO","ID_REGION","CANTIDAD_MINIMA","CANTIDAD_MAXIMA","MOTIVO"
FROM NAF47_TNET.ARIN_ARTI_RECU_TMP@GPOETNET;