CREATE  FORCE VIEW "NAF47_TNET"."ARPLCL" ("CLASE_EMP", "DESCRIPCION", "GRUPO_CLASE", "VALOR", "COD_EXCLUYENTE") AS 
  SELECT "CLASE_EMP",
           "DESCRIPCION",
           "GRUPO_CLASE",
           "VALOR",
           "COD_EXCLUYENTE"
      FROM NAF47_TNET.ARPLCL@GPOETNET;