CREATE  FORCE VIEW "NAF47_TNET"."ARPLGCB" ("NO_CIA", "ID_CTA", "ID_CTA_GRUPO", "ESTADO", "USUARIO_CREA", "FECHA_CREA", "USUARIO_ACTUALIZA", "FECHA_ACTUALIZA") AS 
  SELECT "NO_CIA",
           "ID_CTA",
           "ID_CTA_GRUPO",
           "ESTADO",
           "USUARIO_CREA",
           "FECHA_CREA",
           "USUARIO_ACTUALIZA",
           "FECHA_ACTUALIZA"
      FROM NAF47_TNET.ARPLGCB@GPOETNET;