CREATE  FORCE VIEW "NAF47_TNET"."ARPLREGF" ("FORMULA_ID", "DESCRIPCION", "IND_CALCULO", "PAIS", "NO_CIA", "TIPO_M", "FORMULA_ACTIVA") AS 
  SELECT "FORMULA_ID",
           "DESCRIPCION",
           "IND_CALCULO",
           "PAIS",
           "NO_CIA",
           "TIPO_M",
           "FORMULA_ACTIVA"
      FROM NAF47_TNET.ARPLREGF@GPOETNET;