CREATE  FORCE VIEW "NAF47_TNET"."ARPLCARGA_EXCEL_COMISIONES" ("NO_CIA", "COD_PLA", "NO_EMPLE", "NO_INGRE", "MONTO", "USUARIO") AS 
  SELECT "NO_CIA",
           "COD_PLA",
           "NO_EMPLE",
           "NO_INGRE",
           "MONTO",
           "USUARIO"
      FROM NAF47_TNET.ARPLCARGA_EXCEL_COMISIONES@GPOETNET;