CREATE  FORCE VIEW "NAF47_TNET"."ARPLHGIE" ("NO_CIA", "GRUPO_ING", "DESCRIPCION", "F_SISTEMA") AS 
  SELECT "NO_CIA",
           "GRUPO_ING",
           "DESCRIPCION",
           "F_SISTEMA"
      FROM NAF47_TNET.ARPLHGIE@GPOETNET;