CREATE  FORCE VIEW "NAF47_TNET"."ARPLGIE" ("NO_CIA", "GRUPO_ING", "F_SISTEMA", "DESCRIPCION") AS 
  SELECT "NO_CIA",
           "GRUPO_ING",
           "F_SISTEMA",
           "DESCRIPCION"
      FROM NAF47_TNET.ARPLGIE@GPOETNET;