CREATE  FORCE VIEW "NAF47_TNET"."ARPL_FINIQUITO" ("NO_CIA", "NO_EMPLE", "NO_DEDU", "NO_OPERA", "SECUENCIA", "USUARIO_CREA", "FECHA_CREA") AS 
  SELECT NO_CIA,
           NO_EMPLE,
           NO_DEDU,
           NO_OPERA,
           SECUENCIA,
           USUARIO_CREA,
           FECHA_CREA
      FROM NAF47_TNET.ARPL_FINIQUITO@GPOETNET;