CREATE  FORCE VIEW "NAF47_TNET"."ARPLTIT" ("TITULO", "DESCRIPCION", "USUARIO_CREA", "FECHA_CREA", "USUARIO_ACTUALIZA", "FECHA_ACTUALIZA") AS 
  SELECT "TITULO",
           "DESCRIPCION",
           "USUARIO_CREA",
           "FECHA_CREA",
           "USUARIO_ACTUALIZA",
           "FECHA_ACTUALIZA"
      FROM NAF47_TNET.ARPLTIT@GPOETNET;