CREATE  FORCE VIEW "NAF47_TNET"."ARPLAR" ("NO_CIA", "AREA", "DESCRI", "MOVIMIENTO", "SUCURSAL") AS 
  SELECT "NO_CIA",
           "AREA",
           "DESCRI",
           "MOVIMIENTO",
           "SUCURSAL"
      FROM NAF47_TNET.ARPLAR@GPOETNET;