CREATE  FORCE VIEW "NAF47_TNET"."ARPLEPRENOM" ("NO_CIA", "ID_PLANTILLA", "COD_PLANTILLA", "DESCRIPCION") AS 
  SELECT "NO_CIA",
           "ID_PLANTILLA",
           "COD_PLANTILLA",
           "DESCRIPCION"
      FROM NAF47_TNET.ARPLEPRENOM@GPOETNET;