CREATE  FORCE VIEW "NAF47_TNET"."ARPLHS_ANTICIPO_COMISION" ("NO_CIA", "NO_EMPLE", "TIPO_EMP", "ANIO", "MES", "ANTICIPO_COMISION", "USUARIO") AS 
  SELECT "NO_CIA",
           "NO_EMPLE",
           "TIPO_EMP",
           "ANIO",
           "MES",
           "ANTICIPO_COMISION",
           "USUARIO"
      FROM NAF47_TNET.ARPLHS_ANTICIPO_COMISION@GPOETNET;