CREATE  FORCE VIEW "NAF47_TNET"."ARPLHORA" ("NO_CIA", "NO_HORA", "DESCRIPCION", "JORNADA", "STE_HORARIO") AS 
  SELECT "NO_CIA",
           "NO_HORA",
           "DESCRIPCION",
           "JORNADA",
           "STE_HORARIO"
      FROM NAF47_TNET.ARPLHORA@GPOETNET;