CREATE  FORCE VIEW "NAF47_TNET"."ARPLNSAL" ("NO_CIA", "NIVEL", "SUB_NIVEL", "PUESTO", "SAL_BAS", "GANA_EXTRAS", "SAL_BAS_ANT", "NUEVO_SAL_BAS", "IND_ACC_AUMENTO") AS 
  SELECT "NO_CIA",
           "NIVEL",
           "SUB_NIVEL",
           "PUESTO",
           "SAL_BAS",
           "GANA_EXTRAS",
           "SAL_BAS_ANT",
           "NUEVO_SAL_BAS",
           "IND_ACC_AUMENTO"
      FROM NAF47_TNET.ARPLNSAL@GPOETNET;