CREATE  FORCE VIEW "NAF47_TNET"."ARPLTM" ("NO_CIA", "COD_PLA", "NO_EMPLE", "HORARIO", "MARCA_CORRECTA", "FECHA_ENTRA", "HORA_ENTRA", "FECHA_SALE", "HORA_SALE", "OBSERVACIONES") AS 
  SELECT "NO_CIA",
           "COD_PLA",
           "NO_EMPLE",
           "HORARIO",
           "MARCA_CORRECTA",
           "FECHA_ENTRA",
           "HORA_ENTRA",
           "FECHA_SALE",
           "HORA_SALE",
           "OBSERVACIONES"
      FROM NAF47_TNET.ARPLTM@GPOETNET;