CREATE  FORCE VIEW "NAF47_TNET"."ARPLAP_PERIODOS" ("NO_CIA", "NO_EMPLE", "NO_ACCION", "PERIODO", "DIAS", "NO_ACCION_TMP") AS 
  SELECT "NO_CIA",
           "NO_EMPLE",
           "NO_ACCION",
           "PERIODO",
           "DIAS",
           "NO_ACCION_TMP"
      FROM NAF47_TNET.ARPLAP_PERIODOS@GPOETNET;