CREATE  FORCE VIEW "NAF47_TNET"."ARPLDPRENOM" ("NO_CIA", "ID_PLANTILLA", "AREA", "DEPTO", "DIVISION", "SECCION") AS 
  SELECT "NO_CIA",
           "ID_PLANTILLA",
           "AREA",
           "DEPTO",
           "DIVISION",
           "SECCION"
      FROM NAF47_TNET.ARPLDPRENOM@GPOETNET;