CREATE  FORCE VIEW "NAF47_TNET"."ARPLAPTM" ("TIPO_MOV", "CLASE_MOV", "GOCE_SUELDO", "DESCRIPCION") AS 
  SELECT "TIPO_MOV",
           "CLASE_MOV",
           "GOCE_SUELDO",
           "DESCRIPCION"
      FROM NAF47_TNET.ARPLAPTM@GPOETNET;