

CREATE  FORCE VIEW "NAF47_TNET"."ARPLPAN" ("ANO_ANT", "PORCENTAJE", "DIAS_VAC", "PORC_PROVI_VAC") AS 
  SELECT "ANO_ANT",
           "PORCENTAJE",
           "DIAS_VAC",
           "PORC_PROVI_VAC"
      FROM NAF47_TNET.ARPLPAN@GPOETNET;