

CREATE  FORCE VIEW "NAF47_TNET"."ARPLPPRENOM" ("NO_CIA", "ID_PLANTILLA", "COD_LINEA", "DESCRI_LINEA", "SECUENCIA", "NO_INGRE", "FACTOR_MULT") AS 
  SELECT "NO_CIA",
           "ID_PLANTILLA",
           "COD_LINEA",
           "DESCRI_LINEA",
           "SECUENCIA",
           "NO_INGRE",
           "FACTOR_MULT"
      FROM NAF47_TNET.ARPLPPRENOM@GPOETNET;