CREATE  FORCE VIEW "NAF47_TNET"."ARPLCAT" ("CATEGORIA", "DESCRIPCION", "B_FUNCIONAL", "NO_CIA", "TIPO", "CODIGO_IESS", "IND_JEFE") AS 
  SELECT "CATEGORIA",
           "DESCRIPCION",
           "B_FUNCIONAL",
           "NO_CIA",
           "TIPO",
           "CODIGO_IESS",
           "IND_JEFE"
      FROM NAF47_TNET.ARPLCAT@GPOETNET;