CREATE  FORCE VIEW "NAF47_TNET"."ARPLHGID" ("NO_CIA", "GRUPO_ING", "F_SISTEMA", "NO_INGRE", "MAS_OTRAS_PLA") AS 
  SELECT "NO_CIA",
           "GRUPO_ING",
           "F_SISTEMA",
           "NO_INGRE",
           "MAS_OTRAS_PLA"
      FROM NAF47_TNET.ARPLHGID@GPOETNET;