CREATE  FORCE VIEW "NAF47_TNET"."ARPLCARGA_EXCEL_INGRESOS" ("NO_CIA", "COD_PLA", "NO_EMPLE", "NO_INGRE", "CANTIDAD", "USUARIO", "PORC_BASE", "PORC_GANADO") AS 
  SELECT "NO_CIA",
           "COD_PLA",
           "NO_EMPLE",
           "NO_INGRE",
           "CANTIDAD",
           "USUARIO",
           "PORC_BASE",
           "PORC_GANADO"
      FROM NAF47_TNET.ARPLCARGA_EXCEL_INGRESOS@GPOETNET;