CREATE  FORCE VIEW "NAF47_TNET"."ARPLCID" ("NO_CIA", "GRUPO", "CODIGO", "TIPO", "CUENTA_CONTABLE") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "CODIGO",
           "TIPO",
           "CUENTA_CONTABLE"
      FROM NAF47_TNET.ARPLCID@GPOETNET;