CREATE  FORCE VIEW "NAF47_TNET"."ARPLREPORTE_ANTICIPO_COMISION" ("NO_CIA", "USUARIO", "SECUENCIA", "DATO") AS 
  SELECT "NO_CIA",
           "USUARIO",
           "SECUENCIA",
           "DATO"
      FROM NAF47_TNET.ARPLREPORTE_ANTICIPO_COMISION@GPOETNET;