CREATE  FORCE VIEW "NAF47_TNET"."ARPLPGE" ("GRUPO_PARAMETRO", "DESCRIPCION", "IND_LEY_CIA", "PAIS", "NO_CIA", "SECUENCIA", "INTERFAZ_GENERAL") AS 
  SELECT "GRUPO_PARAMETRO",
           "DESCRIPCION",
           "IND_LEY_CIA",
           "PAIS",
           "NO_CIA",
           "SECUENCIA",
           "INTERFAZ_GENERAL"
      FROM NAF47_TNET.ARPLPGE@GPOETNET;