CREATE  FORCE VIEW "NAF47_TNET"."ARPLIS_HISTORICO" ("NO_CIA", "LIMITEINF", "LIMITESUP", "IMPUESTO_MIN", "PORCENTAJE", "ANIO") AS 
  SELECT "NO_CIA",
           "LIMITEINF",
           "LIMITESUP",
           "IMPUESTO_MIN",
           "PORCENTAJE",
           "ANIO"
      FROM NAF47_TNET.ARPLIS_HISTORICO@GPOETNET;