CREATE  FORCE VIEW "NAF47_TNET"."ARPLPRENOM" ("ID_PLANTILLA", "NO_CIA", "COD_PLA", "NO_EMPLE", "COD_LINEA", "SECUENCIA", "NO_INGRE", "CANTIDAD", "EMP_REEMPLA") AS 
  SELECT "ID_PLANTILLA",
           "NO_CIA",
           "COD_PLA",
           "NO_EMPLE",
           "COD_LINEA",
           "SECUENCIA",
           "NO_INGRE",
           "CANTIDAD",
           "EMP_REEMPLA"
      FROM NAF47_TNET.ARPLPRENOM@GPOETNET;