CREATE  FORCE VIEW "NAF47_TNET"."ARPLGID" ("NO_CIA", "GRUPO_ING", "NO_INGRE", "MAS_OTRAS_PLA") AS 
  SELECT "NO_CIA",
           "GRUPO_ING",
           "NO_INGRE",
           "MAS_OTRAS_PLA"
      FROM NAF47_TNET.ARPLGID@GPOETNET;