CREATE  FORCE VIEW "NAF47_TNET"."ARPLOFICINA" ("NO_CIA", "OFICINA", "NOMBRE_OFICINA", "DIRECCION_OFICINA", "USUARIO_CREA", "FECHA_CREA", "USUARIO_ACTUALIZA", "FECHA_ACTUALIZA", "ESTADO") AS 
  SELECT "NO_CIA",
           "OFICINA",
           "NOMBRE_OFICINA",
           "DIRECCION_OFICINA",
           "USUARIO_CREA",
           "FECHA_CREA",
           "USUARIO_ACTUALIZA",
           "FECHA_ACTUALIZA",
           "ESTADO"
      FROM NAF47_TNET.ARPLOFICINA@GPOETNET;