CREATE  FORCE VIEW "NAF47_TNET"."ARPRPP" ("NO_CIA", "CODIGO", "DESCRIPCION", "MOVIMIENTO", "ESTADO") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "MOVIMIENTO",
           "ESTADO"
      FROM NAF47_TNET.ARPRPP@GPOETNET;