
CREATE  FORCE VIEW "NAF47_TNET"."ARRHST_EMP" ("NO_CIA", "NO_SOLIC", "NO_EMPLE", "FAMILIAR") AS 
  SELECT "NO_CIA",
           "NO_SOLIC",
           "NO_EMPLE",
           "FAMILIAR"
      FROM NAF47_TNET.ARRHST_EMP@GPOETNET;