
CREATE  FORCE VIEW "NAF47_TNET"."ARRHST_REFB" ("NO_CIA", "NO_SOLIC", "TIPO", "BANCO", "CTA_CORRIENTE", "CTA_AHORROS", "INSTITUCION", "NUM_TARJETA", "FECHA_OTORGAMIENTO") AS 
  SELECT "NO_CIA",
           "NO_SOLIC",
           "TIPO",
           "BANCO",
           "CTA_CORRIENTE",
           "CTA_AHORROS",
           "INSTITUCION",
           "NUM_TARJETA",
           "FECHA_OTORGAMIENTO"
      FROM NAF47_TNET.ARRHST_REFB@GPOETNET;