CREATE  FORCE VIEW "NAF47_TNET"."ARRHRE" ("NO_CIA", "DESCRIPCION", "LIMITEINF", "LIMITESUP") AS 
  SELECT "NO_CIA",
           "DESCRIPCION",
           "LIMITEINF",
           "LIMITESUP"
      FROM NAF47_TNET.ARRHRE@GPOETNET;