CREATE  FORCE VIEW "NAF47_TNET"."ARRHES" ("NO_CIA", "NO_SOLIC", "FECHA", "EVALUACION", "CUBIERTOS", "TIPO", "RESULTADO", "ENTREVISTADOR") AS 
  SELECT "NO_CIA",
           "NO_SOLIC",
           "FECHA",
           "EVALUACION",
           "CUBIERTOS",
           "TIPO",
           "RESULTADO",
           "ENTREVISTADOR"
      FROM NAF47_TNET.ARRHES@GPOETNET;