


CREATE  FORCE VIEW "NAF47_TNET"."CASIFICADORES_INDUSTRIAL_TEMP" ("GRUPO", "SUBGRUPO", "SUBGRUPO_FINAL", "SUBGRUPO2", "USO_FINAL") AS 
  SELECT "GRUPO",
           "SUBGRUPO",
           "SUBGRUPO_FINAL",
           "SUBGRUPO2",
           "USO_FINAL"
      FROM NAF47_TNET.CASIFICADORES_INDUSTRIAL_TEMP@GPOETNET;