CREATE  FORCE VIEW "NAF47_TNET"."CG_M_BALANCE_GENERAL" ("COMPANIA", "ID_CUENTA_CONTABLE", "SALDO") AS 
  SELECT "COMPANIA", "ID_CUENTA_CONTABLE", "SALDO"
      FROM NAF47_TNET.CG_M_BALANCE_GENERAL@GPOETNET;