CREATE  FORCE VIEW "NAF47_TNET"."CG_M_PLAN_CUENTAS" ("COMPANIA", "ID_CUENTA_CONTABLE", "NOMBRE", "TIPO", "CLASE", "NATURALEZA", "ULTIMO_NIVEL", "ID_CUENTA_NAF", "NIVEL") AS 
  SELECT "COMPANIA",
           "ID_CUENTA_CONTABLE",
           "NOMBRE",
           "TIPO",
           "CLASE",
           "NATURALEZA",
           "ULTIMO_NIVEL",
           "ID_CUENTA_NAF",
           "NIVEL"
      FROM NAF47_TNET.CG_M_PLAN_CUENTAS@GPOETNET;