CREATE  FORCE VIEW "NAF47_TNET"."CG_M_CUENTAS_RETENCIONES" ("CODEMP", "ID_CUENTA_CONTABLE", "NOMBRE_CUENTA", "CODRET", "CONRETFUEAIR") AS 
  SELECT "CODEMP",
           "ID_CUENTA_CONTABLE",
           "NOMBRE_CUENTA",
           "CODRET",
           "CONRETFUEAIR"
      FROM NAF47_TNET.CG_M_CUENTAS_RETENCIONES@GPOETNET;