CREATE  FORCE VIEW "NAF47_TNET"."CONCEPTOS" ("NO_CIA", "CONCEPTO", "DESCRIPCION", "TIPO_DOC") AS 
  SELECT "NO_CIA",
           "CONCEPTO",
           "DESCRIPCION",
           "TIPO_DOC"
      FROM NAF47_TNET.CONCEPTOS@GPOETNET;