
CREATE  FORCE VIEW "NAF47_TNET"."CONSEC_PERIODO" ("NO_CIA", "FORMULARIO", "PERIODO", "SIGUIENTE", "NUM_INICIAL", "NUM_FINAL") AS 
  SELECT "NO_CIA",
           "FORMULARIO",
           "PERIODO",
           "SIGUIENTE",
           "NUM_INICIAL",
           "NUM_FINAL"
      FROM NAF47_TNET.CONSEC_PERIODO@GPOETNET;