CREATE  FORCE VIEW "NAF47_TNET"."CP_DOCUMENTO_ORIGEN" ("COMPANIA", "TIPO_DOCUMENTO", "NO_DOCUMENTO", "TIPO_DOCUMENTO_ORIGEN", "NO_DOCUMENTO_ORIGEN", "MONTO", "USUARIO_CREACION", "FECHA_CREACION", "ID_DOCUMENTO_INV", "TIPO_DOCUMENTO_INV") AS 
  SELECT "COMPANIA",
           "TIPO_DOCUMENTO",
           "NO_DOCUMENTO",
           "TIPO_DOCUMENTO_ORIGEN",
           "NO_DOCUMENTO_ORIGEN",
           "MONTO",
           "USUARIO_CREACION",
           "FECHA_CREACION",
           "ID_DOCUMENTO_INV",
           "TIPO_DOCUMENTO_INV"
      FROM NAF47_TNET.CP_DOCUMENTO_ORIGEN@GPOETNET;