CREATE  FORCE VIEW "NAF47_TNET"."CP_FORMA_PAGO_DOC" ("ID_COMPANIA", "ID_DOCUMENTO", "ID_FORMA_PAGO", "TIPO_DOCUMENTO", "USR_CREACION", "FE_CREACION", "USR_ULT_MOD", "FE_ULT_MOD") AS 
  SELECT "ID_COMPANIA",
           "ID_DOCUMENTO",
           "ID_FORMA_PAGO",
           "TIPO_DOCUMENTO",
           "USR_CREACION",
           "FE_CREACION",
           "USR_ULT_MOD",
           "FE_ULT_MOD"
      FROM NAF47_TNET.CP_FORMA_PAGO_DOC@GPOETNET;