CREATE  FORCE VIEW "NAF47_TNET"."CP_RETENCIONES_ANULADAS" ("NO_CIA", "NO_DOCU", "USUARIO", "COMP_RET", "FECHA") AS 
  SELECT "NO_CIA",
           "NO_DOCU",
           "USUARIO",
           "COMP_RET",
           "FECHA"
      FROM NAF47_TNET.CP_RETENCIONES_ANULADAS@GPOETNET;