CREATE  FORCE VIEW "NAF47_TNET"."DAV_8" ("NO_CIA", "NUM_FAC", "LUGAR", "FECCAMBIO", "TIPOCAMBIO", "PAISPROC", "CODIGOPAIS", "PRECIO_FACTURA", "GASTO_TRANS", "GASTO_SEGUR") AS 
  SELECT "NO_CIA",
           "NUM_FAC",
           "LUGAR",
           "FECCAMBIO",
           "TIPOCAMBIO",
           "PAISPROC",
           "CODIGOPAIS",
           "PRECIO_FACTURA",
           "GASTO_TRANS",
           "GASTO_SEGUR"
      FROM NAF47_TNET.DAV_8@GPOETNET;