CREATE  FORCE VIEW "NAF47_TNET"."ELOAD" ("ID", "NOM_ARCHIVO", "SEPARADOR", "DESCRIPCION", "NOM_TABLA", "LISTA_CAMPOS", "CANT_CAMPOS") AS 
  SELECT "ID",
           "NOM_ARCHIVO",
           "SEPARADOR",
           "DESCRIPCION",
           "NOM_TABLA",
           "LISTA_CAMPOS",
           "CANT_CAMPOS"
      FROM NAF47_TNET.ELOAD@GPOETNET;