CREATE  FORCE VIEW "NAF47_TNET"."FERIADOS" ("NO_CIA", "ANO", "DIA", "DESCRIPCION") AS 
  SELECT "NO_CIA",
           "ANO",
           "DIA",
           "DESCRIPCION"
      FROM NAF47_TNET.FERIADOS@GPOETNET;