CREATE  FORCE VIEW "NAF47_TNET"."FOTOS_ARTICULOS" ("NO_CIA", "NO_ARTICULO", "FOTO", "PATH", "FECHA_CREA", "USUARIO_CREA", "FECHA_MODIFICA", "USUARIO_MODIFICA") AS 
  SELECT "NO_CIA",
           "NO_ARTICULO",
           "FOTO",
           "PATH",
           "FECHA_CREA",
           "USUARIO_CREA",
           "FECHA_MODIFICA",
           "USUARIO_MODIFICA"
      FROM NAF47_TNET.FOTOS_ARTICULOS@GPOETNET;