CREATE  FORCE VIEW "NAF47_TNET"."GE_HOMOLOGACION_CODIGOS" ("ID_BANCO", "CODIGO", "DESCRIPCION", "ESTADO") AS 
  SELECT "ID_BANCO",
           "CODIGO",
           "DESCRIPCION",
           "ESTADO"
      FROM NAF47_TNET.GE_HOMOLOGACION_CODIGOS@GPOETNET;