CREATE  FORCE VIEW "NAF47_TNET"."GRUPOS" ("NO_CIA", "GRUPO", "DESCRIPCION", "METODO_COSTO", "IND_PROD_SERV", "REQUISICION") AS 
  SELECT "NO_CIA",
           "GRUPO",
           "DESCRIPCION",
           "METODO_COSTO",
           "IND_PROD_SERV",
           "REQUISICION"
      FROM NAF47_TNET.GRUPOS@GPOETNET;