CREATE  FORCE VIEW "NAF47_TNET"."INFO_RETENCIONES" ("SECUENCIA_CARGA_ID", "ELEMENTO_ID", "RETENCION_ID", "BASE_IMPONIBLE", "PORCENTAJE_RETENCION", "VALOR_RETENIDO", "SUSTENTO_ID", "DOC_SUSTENTO_ID") AS 
  SELECT "SECUENCIA_CARGA_ID","ELEMENTO_ID","RETENCION_ID","BASE_IMPONIBLE","PORCENTAJE_RETENCION","VALOR_RETENIDO","SUSTENTO_ID","DOC_SUSTENTO_ID"
FROM NAF47_TNET.INFO_RETENCIONES@GPOETNET;