CREATE  FORCE VIEW "NAF47_TNET"."INFO_DETALLE_FACTURA" ("SECUENCIA_CARGA_ID", "CODIGO_PRINCIPAL", "DESCRIPCION", "CANTIDAD", "PRECIO_UNITARIO", "DESCUENTO", "TOTAL_SIMP") AS 
  SELECT "SECUENCIA_CARGA_ID","CODIGO_PRINCIPAL","DESCRIPCION","CANTIDAD","PRECIO_UNITARIO","DESCUENTO","TOTAL_SIMP"
FROM NAF47_TNET.INFO_DETALLE_FACTURA@GPOETNET;