CREATE  FORCE VIEW "NAF47_TNET"."INFO_IMPUESTOS" ("SECUENCIA_CARGA_ID", "IMPUESTO_ID", "PORCENTAJE_ID", "TARIFA", "BASE_IMPONIBLE", "VALOR", "SUSTENTO_ID", "DOC_SUSTENTO_ID", "ITEM_FACTURA_ID") AS 
  SELECT "SECUENCIA_CARGA_ID","IMPUESTO_ID","PORCENTAJE_ID","TARIFA","BASE_IMPONIBLE","VALOR","SUSTENTO_ID","DOC_SUSTENTO_ID","ITEM_FACTURA_ID"
FROM NAF47_TNET.INFO_IMPUESTOS@GPOETNET;