CREATE  FORCE VIEW "NAF47_TNET"."INFO_PAGO" ("SECUENCIA_CARGA_ID", "FORMA_PAGO_ID", "TOTAL", "PLAZO", "UNIDAD_TIEMPO", "SUSTENTO_ID", "DOC_SUSTENTO_ID") AS 
  SELECT "SECUENCIA_CARGA_ID","FORMA_PAGO_ID","TOTAL","PLAZO","UNIDAD_TIEMPO","SUSTENTO_ID","DOC_SUSTENTO_ID"
FROM NAF47_TNET.INFO_PAGO@GPOETNET;