CREATE  OR REPLACE  VIEW "NAF47_TNET"."INFO_PLANTILLAS_DET" ("PLANTILLA_ID", "ID_DETALLE", "CUENTA_CONTABLE", "CENTRO_COSTO", "BAND_DEB_CRED", "GLOSA", "PORCENTAJE", "ESTADO") AS 
  SELECT "PLANTILLA_ID",
           "ID_DETALLE",
           "CUENTA_CONTABLE",
           "CENTRO_COSTO",
           "BAND_DEB_CRED",
           "GLOSA",
           "PORCENTAJE",
           "ESTADO"
      FROM NAF47_TNET.INFO_PLANTILLAS_DET@Gpoetnet;