CREATE  FORCE VIEW "NAF47_TNET"."INV_PLANTILLAS_DET_REQ" ("NO_CIA", "CENTRO", "COD_PLANTILLA", "NUMERO_LINEA", "BODEGA", "NO_ARTI", "CANTIDAD", "CENTRO_COSTO", "NUMERO_LINEA_REFERENCIA") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "COD_PLANTILLA",
           "NUMERO_LINEA",
           "BODEGA",
           "NO_ARTI",
           "CANTIDAD",
           "CENTRO_COSTO",
           "NUMERO_LINEA_REFERENCIA"
      FROM NAF47_TNET.INV_PLANTILLAS_DET_REQ@GPOETNET;