CREATE  FORCE VIEW "NAF47_TNET"."INV_HISTORICO_SERIE" ("COMPANIA", "NO_DOCUMENTO", "LINEA", "SERIE", "TIPO_DOCUMENTO", "DESC_TIPO_DOCUMENTO", "NO_BODEGA", "FECHA_PROCESO", "CONCEPTO") AS 
  SELECT "COMPANIA",
           "NO_DOCUMENTO",
           "LINEA",
           "SERIE",
           "TIPO_DOCUMENTO",
           "DESC_TIPO_DOCUMENTO",
           "NO_BODEGA",
           "FECHA_PROCESO",
           "CONCEPTO"
      FROM NAF47_TNET.INV_HISTORICO_SERIE@GPOETNET;