CREATE  FORCE VIEW "NAF47_TNET"."INV_SOLICITUD_REQUISICION" ("NO_CIA", "NUMERO_SOLICITUD", "NO_ARTI", "CENTRO_COSTO", "CANTIDAD", "BODEGA", "FECHA", "NO_PROVE", "EMPLE_REALIZA") AS 
  SELECT "NO_CIA",
           "NUMERO_SOLICITUD",
           "NO_ARTI",
           "CENTRO_COSTO",
           "CANTIDAD",
           "BODEGA",
           "FECHA",
           "NO_PROVE",
           "EMPLE_REALIZA"
      FROM NAF47_TNET.INV_SOLICITUD_REQUISICION@GPOETNET;