CREATE  FORCE VIEW "NAF47_TNET"."INV_PLANTILLAS_CAB_REQ" ("NO_CIA", "CENTRO", "COD_PLANTILLA", "CENTRO_COSTO", "OBSERVACION", "USUARIO_SISTEMA", "USUARIO_INGRESA", "USUARIO_RESPONSABLE") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "COD_PLANTILLA",
           "CENTRO_COSTO",
           "OBSERVACION",
           "USUARIO_SISTEMA",
           "USUARIO_INGRESA",
           "USUARIO_RESPONSABLE"
      FROM NAF47_TNET.INV_PLANTILLAS_CAB_REQ@GPOETNET;