CREATE  FORCE VIEW "NAF47_TNET"."LINEA" ("NO_CIA", "NO_LINEA", "DESCRIPCION", "DIVISION", "SUBDIVISION") AS 
  SELECT "NO_CIA",
           "NO_LINEA",
           "DESCRIPCION",
           "DIVISION",
           "SUBDIVISION"
      FROM NAF47_TNET.LINEA@GPOETNET;