CREATE  FORCE VIEW "NAF47_TNET"."LOG_ERROR_PEDIDOS_AUT" ("ID_LOG_PEDIDO", "ID_PEDIDO", "LOGIN_LIDER", "LOGIN_TECNICO", "OBSERVACION", "FECHA_CREACION", "ID_PERSONA_ROL") AS 
  SELECT "ID_LOG_PEDIDO",
           "ID_PEDIDO",
           "LOGIN_LIDER",
           "LOGIN_TECNICO",
           "OBSERVACION",
           "FECHA_CREACION",
           "ID_PERSONA_ROL"
      FROM NAF47_TNET.LOG_ERROR_PEDIDOS_AUT@GPOETNET;