CREATE  FORCE VIEW "NAF47_TNET"."LTARCK_DIVISION_CC" ("NO_CIA", "COD_DIVISION", "CTA_CONTABLE", "CENTRO_COSTO") AS 
  SELECT "NO_CIA",
           "COD_DIVISION",
           "CTA_CONTABLE",
           "CENTRO_COSTO"
      FROM NAF47_TNET.LTARCK_DIVISION_CC@GPOETNET;