CREATE  FORCE VIEW "NAF47_TNET"."LTARCP_DOC_RET_IVA" ("NO_CIA", "TIPO_DOC", "CONDIC_TRIBUT", "TIPO_COMPRA", "CLAVE_RET_IVA") AS 
  SELECT "NO_CIA",
           "TIPO_DOC",
           "CONDIC_TRIBUT",
           "TIPO_COMPRA",
           "CLAVE_RET_IVA"
      FROM NAF47_TNET.LTARCP_DOC_RET_IVA@GPOETNET;