CREATE  FORCE VIEW "NAF47_TNET"."MIGRA_ARCKMM_TEMP_26072013" ("PROCEDENCIA", "TIPO_DOC", "NO_DOCU") AS 
  SELECT "PROCEDENCIA", "TIPO_DOC", "NO_DOCU"
      FROM NAF47_TNET.MIGRA_ARCKMM_TEMP_26072013@GPOETNET;