CREATE  FORCE VIEW "NAF47_TNET"."MIGRA_CABEING" ("NO_CIA", "CENTRO", "DOCUM", "FECHA", "BODE", "FECHA_PROCESO", "IND_PROCESADO", "OBSERVACION") AS 
  SELECT "NO_CIA",
           "CENTRO",
           "DOCUM",
           "FECHA",
           "BODE",
           "FECHA_PROCESO",
           "IND_PROCESADO",
           "OBSERVACION"
      FROM NAF47_TNET.MIGRA_CABEING@GPOETNET;