CREATE  FORCE VIEW "NAF47_TNET"."MONEDAS" ("ID_MONEDA", "DESC_MONEDA", "DESCRIPCION", "SIGNO", "REDONDEO", "NUMDECI") AS 
  SELECT "ID_MONEDA",
           "DESC_MONEDA",
           "DESCRIPCION",
           "SIGNO",
           "REDONDEO",
           "NUMDECI"
      FROM NAF47_TNET.MONEDAS@GPOETNET;