CREATE  FORCE VIEW "NAF47_TNET"."PL_HIS_INGRESOS_EMPLEADO" ("NO_CIA", "NO_EMPLE", "F_INGRESO", "F_EGRESO", "TIPO_EMP", "MO_SALIDA", "ST_DATO", "OBSERVACION") AS 
  SELECT "NO_CIA",
           "NO_EMPLE",
           "F_INGRESO",
           "F_EGRESO",
           "TIPO_EMP",
           "MO_SALIDA",
           "ST_DATO",
           "OBSERVACION"
      FROM NAF47_TNET.PL_HIS_INGRESOS_EMPLEADO@GPOETNET;