CREATE  FORCE VIEW "NAF47_TNET"."PL_HISTORICO_CAM_SUELDOS" ("NO_CIA", "NO_EMPLE", "SALARIO", "FECHA", "SUELDO_ACT") AS 
  SELECT "NO_CIA",
           "NO_EMPLE",
           "SALARIO",
           "FECHA",
           "SUELDO_ACT"
      FROM NAF47_TNET.PL_HISTORICO_CAM_SUELDOS@GPOETNET;