CREATE  FORCE VIEW "NAF47_TNET"."PL_PATRONAL_PROVINCIA" ("NO_CIA", "ID_PAIS", "ID_PROVINCIA", "NO_PATRONAL", "DIRECCION") AS 
  SELECT "NO_CIA",
           "ID_PAIS",
           "ID_PROVINCIA",
           "NO_PATRONAL",
           "DIRECCION"
      FROM NAF47_TNET.PL_PATRONAL_PROVINCIA@GPOETNET;