CREATE  FORCE VIEW "NAF47_TNET"."PLSQL_PROFILER_UNITS" ("RUNID", "UNIT_NUMBER", "UNIT_TYPE", "UNIT_OWNER", "UNIT_NAME", "UNIT_TIMESTAMP", "TOTAL_TIME", "SPARE1", "SPARE2") AS 
  SELECT "RUNID",
           "UNIT_NUMBER",
           "UNIT_TYPE",
           "UNIT_OWNER",
           "UNIT_NAME",
           "UNIT_TIMESTAMP",
           "TOTAL_TIME",
           "SPARE1",
           "SPARE2"
      FROM NAF47_TNET.PLSQL_PROFILER_UNITS@GPOETNET;