CREATE  FORCE VIEW "NAF47_TNET"."PR_CENTRO_COSTO" ("ID_CENTRO_COSTO", "NO_CIA", "CODIGO", "DESCRIPCION", "ESTADO", "USR_CREACION", "FE_CREACION", "USR_ULT_MOD", "FE_ULT_MOD") AS 
  SELECT "ID_CENTRO_COSTO",
           "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "ESTADO",
           "USR_CREACION",
           "FE_CREACION",
           "USR_ULT_MOD",
           "FE_ULT_MOD"
      FROM NAF47_TNET.PR_CENTRO_COSTO@GPOETNET;