CREATE  FORCE VIEW "NAF47_TNET"."PRESTAMOS_IESS_TEMP" ("CEDULA", "PQUIROGRAFARIO", "PHIPOTECARIO", "PTOTAL", "PROCESADO") AS 
  SELECT "CEDULA",
           "PQUIROGRAFARIO",
           "PHIPOTECARIO",
           "PTOTAL",
           "PROCESADO"
      FROM NAF47_TNET.PRESTAMOS_IESS_TEMP@GPOETNET;