CREATE  FORCE VIEW "NAF47_TNET"."PROVEEDOR_COD_ART" ("PROVEEDOR", "CODIGO_ANTERIOR", "COD_ART_PROV", "DESC_PROV") AS 
  SELECT "PROVEEDOR",
           "CODIGO_ANTERIOR",
           "COD_ART_PROV",
           "DESC_PROV"
      FROM NAF47_TNET.PROVEEDOR_COD_ART@GPOETNET;