CREATE  FORCE VIEW "NAF47_TNET"."PUESTOS" ("CODIGO_PUESTO", "DESCRIPCION_PUESTO", "TIPO_PUESTO") AS 
  SELECT "CODIGO_PUESTO", "DESCRIPCION_PUESTO", "TIPO_PUESTO"
      FROM NAF47_TNET.PUESTOS@GPOETNET;