CREATE  FORCE VIEW "NAF47_TNET"."SEG_AUDITORIA_TRANSACCIONES" ("NO_CIA", "MODULO", "ID_NIVEL", "NUMERO_TRANSACCION", "TIPO_MOVIMIENTO", "USUARIO", "FECHAHORA_AUDITORIA") AS 
  SELECT "NO_CIA",
           "MODULO",
           "ID_NIVEL",
           "NUMERO_TRANSACCION",
           "TIPO_MOVIMIENTO",
           "USUARIO",
           "FECHAHORA_AUDITORIA"
      FROM NAF47_TNET.SEG_AUDITORIA_TRANSACCIONES@GPOETNET;