CREATE  FORCE VIEW "NAF47_TNET"."SRI_PARAISO_FISCAL" ("ID_PARAISO_FISCAL", "DESCRIPCION", "PAIS_ID", "FE_INICIO", "FE_FIN", "FE_CREACION", "USR_CREACION", "FE_ULT_MOD", "USR_ULT_MOD") AS 
  SELECT "ID_PARAISO_FISCAL",
           "DESCRIPCION",
           "PAIS_ID",
           "FE_INICIO",
           "FE_FIN",
           "FE_CREACION",
           "USR_CREACION",
           "FE_ULT_MOD",
           "USR_ULT_MOD"
      FROM NAF47_TNET.SRI_PARAISO_FISCAL@GPOETNET;