CREATE  FORCE VIEW "NAF47_TNET"."SRI_PORC_ICE" ("CODIGO", "PORCENTAJE_ICE", "CODIGO_IMPUESTO", "DESCRIPCION", "FECHA_INICIO", "FECHA_FIN") AS 
  SELECT "CODIGO",
           "PORCENTAJE_ICE",
           "CODIGO_IMPUESTO",
           "DESCRIPCION",
           "FECHA_INICIO",
           "FECHA_FIN"
      FROM NAF47_TNET.SRI_PORC_ICE@GPOETNET;