CREATE  FORCE VIEW "NAF47_TNET"."SRI_TIPOS_IMPORT_EXPORT" ("CODIGO", "SEC_TIPO_IMPORT_EXPORT") AS 
  SELECT "CODIGO", "SEC_TIPO_IMPORT_EXPORT"
      FROM NAF47_TNET.SRI_TIPOS_IMPORT_EXPORT@GPOETNET;