CREATE  FORCE VIEW "NAF47_TNET"."SRI_REL_SUST_TRIB_TIPO_COMP" ("CODIGO_SUST_TRIB", "CODIGO_TIPO_COMP") AS 
  SELECT "CODIGO_SUST_TRIB", "CODIGO_TIPO_COMP"
      FROM NAF47_TNET.SRI_REL_SUST_TRIB_TIPO_COMP@GPOETNET;