CREATE  FORCE VIEW "NAF47_TNET"."SRI_SECUENCIALES_TRANSACCIONES" ("CODIGO", "CODIGO_TIPO_TRANS", "CODIGO_IDENTIFICACION", "ING_TIPO_IDENTIFICACION") AS 
  SELECT "CODIGO",
           "CODIGO_TIPO_TRANS",
           "CODIGO_IDENTIFICACION",
           "ING_TIPO_IDENTIFICACION"
      FROM NAF47_TNET.SRI_SECUENCIALES_TRANSACCIONES@GPOETNET;