CREATE  FORCE VIEW "NAF47_TNET"."SRI_REL_TIPO_TRANS_TIPO_COMP" ("CODIGO_TIPO_TRANS", "CODIGO_TIPO_COMP") AS 
  SELECT "CODIGO_TIPO_TRANS", "CODIGO_TIPO_COMP"
      FROM NAF47_TNET.SRI_REL_TIPO_TRANS_TIPO_COMP@GPOETNET;