CREATE  FORCE VIEW "NAF47_TNET"."SRI_RET_FUENTE_IMP_RENTA" ("CODIGO", "DESCRIPCION", "PORC_RETENCION", "F_INICIO_PORC", "F_FIN_PORC", "INGRESA_PORCENTAJE", "COD_NO_RETENCION") AS 
  SELECT "CODIGO",
           "DESCRIPCION",
           "PORC_RETENCION",
           "F_INICIO_PORC",
           "F_FIN_PORC",
           "INGRESA_PORCENTAJE",
           "COD_NO_RETENCION"
      FROM NAF47_TNET.SRI_RET_FUENTE_IMP_RENTA@GPOETNET;