CREATE  FORCE VIEW "NAF47_TNET"."SRI_LOG_ERRORES" ("NO_CIA", "NOMBRE_PROCESO", "CLAVE", "MENSAJE_ERROR", "FE_CREACION", "USR_CREACION") AS 
  SELECT "NO_CIA",
           "NOMBRE_PROCESO",
           "CLAVE",
           "MENSAJE_ERROR",
           "FE_CREACION",
           "USR_CREACION"
      FROM NAF47_TNET.SRI_LOG_ERRORES@GPOETNET;