CREATE  FORCE VIEW "NAF47_TNET"."SRI_PAIS" ("ID_PAIS", "DESCRIPCION", "ESTADO", "FE_CREACION", "USR_CREACION", "FE_ULT_MOD", "USR_ULT_MOD") AS 
  SELECT "ID_PAIS",
           "DESCRIPCION",
           "ESTADO",
           "FE_CREACION",
           "USR_CREACION",
           "FE_ULT_MOD",
           "USR_ULT_MOD"
      FROM NAF47_TNET.SRI_PAIS@GPOETNET;