CREATE  FORCE VIEW "NAF47_TNET"."SRI_TIPOS_IDENTIFICACIONES" ("CODIGO", "NOMBRE_IDENTIFICACION") AS 
  SELECT "CODIGO", "NOMBRE_IDENTIFICACION"
      FROM NAF47_TNET.SRI_TIPOS_IDENTIFICACIONES@GPOETNET;