CREATE  FORCE VIEW "NAF47_TNET"."SRI_PORC_IVA" ("CODIGO", "PORC_IVA", "FECHA_INICIO", "FECHA_FIN") AS 
  SELECT "CODIGO",
           "PORC_IVA",
           "FECHA_INICIO",
           "FECHA_FIN"
      FROM NAF47_TNET.SRI_PORC_IVA@GPOETNET;