CREATE  FORCE VIEW "NAF47_TNET"."SRI_AT_INTERFACE" ("DETALLE", "NO_CIA", "LINEA", "TIPO") AS 
  SELECT "DETALLE",
           "NO_CIA",
           "LINEA",
           "TIPO"
      FROM NAF47_TNET.SRI_AT_INTERFACE@GPOETNET;