CREATE  FORCE VIEW "NAF47_TNET"."SRI_TIPO_COMPROBANTE_RELACION" ("ID_TIPO_COMPROBANTE", "ID_COMP_RELACIONADO", "ESTADO", "USUARIO_CREACION", "FECHA_CREACION", "USUARIO_ACTUALIZA", "FECHA_ACTUALIZA") AS 
  SELECT "ID_TIPO_COMPROBANTE",
           "ID_COMP_RELACIONADO",
           "ESTADO",
           "USUARIO_CREACION",
           "FECHA_CREACION",
           "USUARIO_ACTUALIZA",
           "FECHA_ACTUALIZA"
      FROM NAF47_TNET.SRI_TIPO_COMPROBANTE_RELACION@GPOETNET;