CREATE  FORCE VIEW "NAF47_TNET"."SRI_SUSTENTO_COMPROBANTE" ("CODIGO", "DESCRIPCION", "APLICA_C_TRIBUTARIO") AS 
  SELECT "CODIGO", "DESCRIPCION", "APLICA_C_TRIBUTARIO"
      FROM NAF47_TNET.SRI_SUSTENTO_COMPROBANTE@GPOETNET;