CREATE  FORCE VIEW "NAF47_TNET"."TAAUDCE" ("TABLA", "IND_INSERT", "IND_UPDATE", "IND_DELETE") AS 
  SELECT "TABLA",
           "IND_INSERT",
           "IND_UPDATE",
           "IND_DELETE"
      FROM NAF47_TNET.TAAUDCE@GPOETNET;