CREATE  FORCE VIEW "NAF47_TNET"."TAAUDITORIA" ("TABLA", "MOVIMIENTO", "USUARIO", "FECHA", "LLAVE", "VALORES") AS 
  SELECT "TABLA",
           "MOVIMIENTO",
           "USUARIO",
           "FECHA",
           "LLAVE",
           "VALORES"
      FROM NAF47_TNET.TAAUDITORIA@GPOETNET;