CREATE  FORCE VIEW "NAF47_TNET"."TAFFCU" ("NO_CIA", "ID_USU", "MODULO", "SUBMODULO") AS 
  SELECT "NO_CIA",
           "ID_USU",
           "MODULO",
           "SUBMODULO"
      FROM NAF47_TNET.TAFFCU@GPOETNET;