CREATE  FORCE VIEW "NAF47_TNET"."TAFFCG" ("NO_CIA", "COD_GASTO", "DESCRIPCION", "CTA_CONTABLE") AS 
  SELECT "NO_CIA",
           "COD_GASTO",
           "DESCRIPCION",
           "CTA_CONTABLE"
      FROM NAF47_TNET.TAFFCG@GPOETNET;