CREATE  FORCE VIEW "NAF47_TNET"."TAFFUA" ("NO_CIA", "USUARIO", "COD_CAJA", "NO_EMPLE", "NOMBRE", "MONTO_MAXIMO_NOMINAL", "MONTO_MAXIMO_DOLARES") AS 
  SELECT "NO_CIA",
           "USUARIO",
           "COD_CAJA",
           "NO_EMPLE",
           "NOMBRE",
           "MONTO_MAXIMO_NOMINAL",
           "MONTO_MAXIMO_DOLARES"
      FROM NAF47_TNET.TAFFUA@GPOETNET;