CREATE  FORCE VIEW "NAF47_TNET"."TAP_HISTORIAL_OC" ("NO_CIA", "NO_ORDEN", "NO_LINEA", "NO_ARTI", "CANTIDAD", "RECIBIDO", "FECHA_RECEPCION", "USR_RECEPCION") AS 
  SELECT "NO_CIA",
           "NO_ORDEN",
           "NO_LINEA",
           "NO_ARTI",
           "CANTIDAD",
           "RECIBIDO",
           "FECHA_RECEPCION",
           "USR_RECEPCION"
      FROM NAF47_TNET.TAP_HISTORIAL_OC@GPOETNET;