CREATE  FORCE VIEW "NAF47_TNET"."TAP_BONIFICACION" ("NO_CIA", "NO_PROVE", "NO_ARTI", "RANGO_INICIAL", "RANGO_FINAL", "CANTIDAD_BONIF", "UNIDAD_BONIF") AS 
  SELECT "NO_CIA",
           "NO_PROVE",
           "NO_ARTI",
           "RANGO_INICIAL",
           "RANGO_FINAL",
           "CANTIDAD_BONIF",
           "UNIDAD_BONIF"
      FROM NAF47_TNET.TAP_BONIFICACION@GPOETNET;