CREATE  FORCE VIEW "NAF47_TNET"."TAPCPS" ("NO_CIA", "CODIGO", "DESCRIPCION", "TIPO", "PORCENTAJE_IVA", "ID_CUENTA_CONTABLE", "ESTADO", "TIPO_MONTO", "MONTO_REFERENCIA") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "DESCRIPCION",
           "TIPO",
           "PORCENTAJE_IVA",
           "ID_CUENTA_CONTABLE",
           "ESTADO",
           "TIPO_MONTO",
           "MONTO_REFERENCIA"
      FROM NAF47_TNET.TAPCPS@GPOETNET;