CREATE  FORCE VIEW "NAF47_TNET"."TAPHSOLI" ("NO_CIA", "NO_SOLIC", "ESTADO", "FECHA_F", "MOTIVO_ANULACION") AS 
  SELECT "NO_CIA",
           "NO_SOLIC",
           "ESTADO",
           "FECHA_F",
           "MOTIVO_ANULACION"
      FROM NAF47_TNET.TAPHSOLI@GPOETNET;