CREATE  FORCE VIEW "NAF47_TNET"."TAPORD_FACTENCAB" ("NO_CIA", "NO_ORDEN", "NO_FISICO", "SERIE_FISICO", "TIPO_REF", "FECHA_TRANS", "TOTAL_FACT") AS 
  SELECT "NO_CIA",
           "NO_ORDEN",
           "NO_FISICO",
           "SERIE_FISICO",
           "TIPO_REF",
           "FECHA_TRANS",
           "TOTAL_FACT"
      FROM NAF47_TNET.TAPORD_FACTENCAB@GPOETNET;