CREATE  FORCE VIEW "NAF47_TNET"."TAPPRI" ("NO_CIA", "CODIGO", "PLAZO", "DESCRIPCION") AS 
  SELECT "NO_CIA",
           "CODIGO",
           "PLAZO",
           "DESCRIPCION"
      FROM NAF47_TNET.TAPPRI@GPOETNET;