CREATE  FORCE VIEW "NAF47_TNET"."TI_PRESTAMOS" ("ID_COMPROBANTE", "ID_PERSONA", "ID_LIBRO", "ID_COPIA", "FECHA_PRESTAMO", "FECHA_DEVOLUCION") AS 
  SELECT "ID_COMPROBANTE",
           "ID_PERSONA",
           "ID_LIBRO",
           "ID_COPIA",
           "FECHA_PRESTAMO",
           "FECHA_DEVOLUCION"
      FROM NAF47_TNET.TI_PRESTAMOS@GPOETNET;