CREATE  FORCE VIEW "NAF47_TNET"."TMP_ARCKSD" ("NO_CIA", "NO_CTA", "DIA_CIERRE", "SALDO_DIA") AS 
  SELECT "NO_CIA",
           "NO_CTA",
           "DIA_CIERRE",
           "SALDO_DIA"
      FROM NAF47_TNET.TMP_ARCKSD@GPOETNET;