CREATE  FORCE VIEW "NAF47_TNET"."V_ACCIONES_PERSONAL" ("TIPO_MOV", "CLASE_MOV", "GOCE_SUELDO", "DESCRIPCION", "NO_CIA", "NO_EMPLE", "NOMBRE_EMPLEADO", "FECHA", "DIAS", "COD_PLA") AS 
  SELECT "TIPO_MOV",
           "CLASE_MOV",
           "GOCE_SUELDO",
           "DESCRIPCION",
           "NO_CIA",
           "NO_EMPLE",
           "NOMBRE_EMPLEADO",
           "FECHA",
           "DIAS",
           "COD_PLA"
      FROM NAF47_TNET.V_ACCIONES_PERSONAL@GPOETNET;