CREATE  FORCE VIEW "NAF47_TNET"."V_ARTICULOS_VENTAS_MENSUALES" ("ARTICULO", "FECHA", "UNIDADES", "MONTO", "ANO", "MES") AS 
  SELECT "ARTICULO",
           "FECHA",
           "UNIDADES",
           "MONTO",
           "ANO",
           "MES"
      FROM NAF47_TNET.V_ARTICULOS_VENTAS_MENSUALES@GPOETNET;