CREATE  FORCE VIEW "NAF47_TNET"."V_AREA_DEPARTAMENTO_COMPANIA" ("NO_CIA", "DESCRIP", "AREA", "DESCRI", "DEPA", "DEPARTAMENTO") AS 
  SELECT "NO_CIA",
           "DESCRIP",
           "AREA",
           "DESCRI",
           "DEPA",
           "DEPARTAMENTO"
      FROM NAF47_TNET.V_AREA_DEPARTAMENTO_COMPANIA@GPOETNET;