CREATE  FORCE VIEW "NAF47_TNET"."V_ARTICULO_COD_BARRA" ("NO_ARTI", "DESCRIPCION", "BODEGA", "STOCK", "NO_CIA", "ARTICULO", "COD_ALTERNO", "TIPO_COD") AS 
  SELECT "NO_ARTI",
           "DESCRIPCION",
           "BODEGA",
           "STOCK",
           "NO_CIA",
           "ARTICULO",
           "COD_ALTERNO",
           "TIPO_COD"
      FROM NAF47_TNET.V_ARTICULO_COD_BARRA@GPOETNET;