CREATE  FORCE VIEW "NAF47_TNET"."V_COMPRAS_CLIENTES" ("NO_CLIENTE", "FECHA", "DESCUENTO1", "DESCUENTO2", "BODEGA", "NO_ARTI", "PEDIDO", "PRECIO") AS 
  SELECT "NO_CLIENTE",
           "FECHA",
           "DESCUENTO1",
           "DESCUENTO2",
           "BODEGA",
           "NO_ARTI",
           "PEDIDO",
           "PRECIO"
      FROM NAF47_TNET.V_COMPRAS_CLIENTES@GPOETNET;