CREATE  FORCE VIEW "NAF47_TNET"."V_CUENTA_CONTABLE_COMPANIA" ("NO_CIA", "CTA_FMT", "DESCRI", "CUENTA", "PADRE", "DESCR") AS 
  SELECT "NO_CIA",
           "CTA_FMT",
           "DESCRI",
           "CUENTA",
           "PADRE",
           "DESCR"
      FROM NAF47_TNET.V_CUENTA_CONTABLE_COMPANIA@GPOETNET;