CREATE  FORCE VIEW "NAF47_TNET"."V_DATOS_EMPLEADOS" ("NOMBRE", "CEDULA", "ESTADO", "CARGO_EMPLEADO", "NOMBRE_JEFE", "NOMBRE_CANTON") AS 
  SELECT "NOMBRE",
           "CEDULA",
           "ESTADO",
           "CARGO_EMPLEADO",
           "NOMBRE_JEFE",
           "NOMBRE_CANTON"
      FROM NAF47_TNET.V_DATOS_EMPLEADOS@GPOETNET;