CREATE  FORCE VIEW "NAF47_TNET"."V_DESCRIPCION_CARACTERISTICA" ("ID_CARACTERISTICA", "DESCRIPCION", "ESTADO") AS 
  SELECT "ID_CARACTERISTICA", "DESCRIPCION", "ESTADO"
      FROM NAF47_TNET.V_DESCRIPCION_CARACTERISTICA@GPOETNET;