CREATE  FORCE VIEW "NAF47_TNET"."V_DEV_VENTAS_SRI" ("NO_CIA", "MES_ANIO", "CEDULA", "TIPO_ID_TRIBUTARIO", "PARTE_RELACIONADA", "SUBTOTAL", "IVA", "TOTAL_COMPROBANTES_EMITIDOS", "TIPO", "GRAVADO", "EXENTO") AS 
  SELECT "NO_CIA",
           "MES_ANIO",
           "CEDULA",
           "TIPO_ID_TRIBUTARIO",
           "PARTE_RELACIONADA",
           "SUBTOTAL",
           "IVA",
           "TOTAL_COMPROBANTES_EMITIDOS",
           "TIPO",
           "GRAVADO",
           "EXENTO"
      FROM NAF47_TNET.V_DEV_VENTAS_SRI@GPOETNET;