CREATE  FORCE VIEW "NAF47_TNET"."V_ERROR_TRANS_STOCK" ("NO_CIA", "NO_ARTI", "BODEGA", "TRANSSTOCK", "STOCK") AS 
  SELECT "NO_CIA",
           "NO_ARTI",
           "BODEGA",
           "TRANSSTOCK",
           "STOCK"
      FROM NAF47_TNET.V_ERROR_TRANS_STOCK@GPOETNET;