CREATE  FORCE VIEW "NAF47_TNET"."V_IM_CUENTA_TRANSITO" ("NO_CIA", "NO_EMBARQUE", "TIPO_EMBARQUE", "FECHA_EMBARQUE", "MONTO_CXP", "MONTO_INV") AS 
  SELECT "NO_CIA",
           "NO_EMBARQUE",
           "TIPO_EMBARQUE",
           "FECHA_EMBARQUE",
           "MONTO_CXP",
           "MONTO_INV"
      FROM NAF47_TNET.V_IM_CUENTA_TRANSITO@GPOETNET;