CREATE  FORCE VIEW "NAF47_TNET"."V_INV_DIFERENCIA_LOTES" ("NO_CIA", "STOCK", "STOCK_LOTE", "BODEGA", "NO_ARTI") AS 
  SELECT "NO_CIA",
           "STOCK",
           "STOCK_LOTE",
           "BODEGA",
           "NO_ARTI"
      FROM NAF47_TNET.V_INV_DIFERENCIA_LOTES@GPOETNET;