CREATE  FORCE VIEW "NAF47_TNET"."V_INV_STOCK_ARINMA" ("NO_CIA", "BODEGA", "NO_ARTI", "DESCRIPCION", "STOCK") AS 
  SELECT "NO_CIA",
           "BODEGA",
           "NO_ARTI",
           "DESCRIPCION",
           "STOCK"
      FROM NAF47_TNET.V_INV_STOCK_ARINMA@GPOETNET;