
CREATE  FORCE VIEW "NAF47_TNET"."V_INV_TRANS_LOTES" ("NO_CIA", "BODEGA", "NO_LOTE", "NO_ARTI", "TOTAL_LOTE_TRANS", "INGRESOS", "SALIDAS") AS 
  SELECT "NO_CIA",
           "BODEGA",
           "NO_LOTE",
           "NO_ARTI",
           "TOTAL_LOTE_TRANS",
           "INGRESOS",
           "SALIDAS"
      FROM NAF47_TNET.V_INV_TRANS_LOTES@GPOETNET;