CREATE  FORCE VIEW "NAF47_TNET"."V_LOGIN_CLIENTE" ("SERIE_FISICA", "LOGIN", "NOMBRE_ELEMENTO") AS 
  SELECT "SERIE_FISICA", "LOGIN", "NOMBRE_ELEMENTO"
      FROM NAF47_TNET.V_LOGIN_CLIENTE@GPOETNET;