CREATE  FORCE VIEW "NAF47_TNET"."V_PEDIDOS_PICKING" ("NO_CIA", "CENTROD", "NO_FACTU", "NO_ARTI", "PEDIDO", "CANT_APROBADA", "NO_DOCU_REFE_PICKING", "NO_FISICO") AS 
  SELECT "NO_CIA",
           "CENTROD",
           "NO_FACTU",
           "NO_ARTI",
           "PEDIDO",
           "CANT_APROBADA",
           "NO_DOCU_REFE_PICKING",
           "NO_FISICO"
      FROM NAF47_TNET.V_PEDIDOS_PICKING@GPOETNET;