CREATE  FORCE VIEW "NAF47_TNET"."V_PLAN_CUENTAS_EMPRESAS" ("NO_CIA", "CUENTA", "DESCRIPCION", "TIPO", "CLASE") AS 
  SELECT "NO_CIA",
           "CUENTA",
           "DESCRIPCION",
           "TIPO",
           "CLASE"
      FROM NAF47_TNET.V_PLAN_CUENTAS_EMPRESAS@GPOETNET;