CREATE  FORCE VIEW "NAF47_TNET"."V_PRODUCTO_UBICACION" ("NO_CIA", "BODEGA", "UBICACION", "DESC_UBICACION", "NO_ARTICULO", "DESC_ARTICULO", "MANEJA_SERIE", "MEDIDA", "STOCK") AS 
  SELECT "NO_CIA",
           "BODEGA",
           "UBICACION",
           "DESC_UBICACION",
           "NO_ARTICULO",
           "DESC_ARTICULO",
           "MANEJA_SERIE",
           "MEDIDA",
           "STOCK"
      FROM NAF47_TNET.V_PRODUCTO_UBICACION@GPOETNET;