CREATE  FORCE VIEW "NAF47_TNET"."V_PRECIO_UTILIDAD" ("NO_ARTI", "DESCRIPCION", "PRECIO_FOB", "ULTIMO_COSTO", "PVP", "UTILIDAD", "DESCUENTO") AS 
  SELECT "NO_ARTI",
           "DESCRIPCION",
           "PRECIO_FOB",
           "ULTIMO_COSTO",
           "PVP",
           "UTILIDAD",
           "DESCUENTO"
      FROM NAF47_TNET.V_PRECIO_UTILIDAD@GPOETNET;