CREATE  FORCE VIEW "NAF47_TNET"."V_PUESTOS_COMPANIA" ("NO_CIA", "DESCRIP", "PUESTO", "DESCRI", "JEFE") AS 
  SELECT "NO_CIA",
           "DESCRIP",
           "PUESTO",
           "DESCRI",
           "JEFE"
      FROM NAF47_TNET.V_PUESTOS_COMPANIA@GPOETNET;