/**
 * Scripts para el reverso de los parametros del producto SAFE ENTRY
 *
 * @author Leonardo Mero <lemero@telconet.ec>
 * @version 1.0 09-12-2022
 */


--DB GENERAL

--Se hace el reset del parametro para no mostrar el boton de cancelar
 UPDATE DB_GENERAL.ADMI_PARAMETRO_DET
SET VALOR1 = REPLACE(VALOR1, ',SAFE ENTRY','')
WHERE ID_PARAMETRO_DET =
  (SELECT ID_PARAMETRO_DET
  FROM DB_GENERAL.ADMI_PARAMETRO_DET
  WHERE PARAMETRO_ID =
    (SELECT ID_PARAMETRO
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB
    WHERE NOMBRE_PARAMETRO = 'NO_VISUALIZAR_BOTON_DE_CANCELAR'
    )
  );

--Se eliminan los parametros de configuracion de SAFE ENTRY
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID =
  (SELECT ID_PARAMETRO
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB
  WHERE NOMBRE_PARAMETRO = 'CONFIG SAFE ENTRY'
  AND MODULO             = 'COMERCIAL'
  AND ESTADO             = 'Activo'
  );
--Se eliminan el parametro cabecera de configuracion de SAFE ENTRY
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'CONFIG SAFE ENTRY'
AND MODULO             = 'COMERCIAL'
AND ESTADO             = 'Activo';
--Se eliminan los parametros de configuracion de SAFE ENTRY
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID =
  (SELECT ID_PARAMETRO
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB
  WHERE NOMBRE_PARAMETRO = 'CONFIG TAREAS SAFE ENTRY'
  AND MODULO             = 'COMERCIAL'
  AND ESTADO             = 'Activo'
  );
--Se eliminan el parametro cabecera de configuracion de SAFE ENTRY
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'CONFIG TAREAS SAFE ENTRY'
AND MODULO             = 'COMERCIAL'
AND ESTADO             = 'Activo';
--Se eliminan los parametros de configuracion de SAFE ENTRY
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID =
  (SELECT ID_PARAMETRO
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB
  WHERE NOMBRE_PARAMETRO = 'CONFIG ELEMENTOS SAFE ENTRY'
  AND MODULO             = 'TECNICO'
  AND ESTADO             = 'Activo'
  );
--Se eliminan el parametro cabecera de configuracion de SAFE ENTRY
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'CONFIG ELEMENTOS SAFE ENTRY'
AND MODULO             = 'TECNICO'
AND ESTADO             = 'Activo';

--
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE
    VALOR1 = 'SAFE ENTRY'
    AND PARAMETRO_ID = ( SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'VISUALIZAR_PANTALLA_FIBRA' );
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE VALOR1    IN ('UPS','RASPBERRY','NVR','SWITCH')
AND PARAMETRO_ID = '1563';

--Se elimina la caracteristica ELEMENTO_CLIENTE_ID del producto SAFE ENTRY
DELETE
FROM DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
WHERE PRODUCTO_ID =
  (SELECT ID_PRODUCTO
  FROM DB_COMERCIAL.ADMI_PRODUCTO
  WHERE NOMBRE_TECNICO = 'SAFE ENTRY'
  AND ESTADO           = 'Activo'
  )
AND CARACTERISTICA_ID =
  (SELECT ID_CARACTERISTICA
  FROM DB_COMERCIAL.ADMI_CARACTERISTICA
  WHERE DESCRIPCION_CARACTERISTICA = 'ELEMENTO_CLIENTE_ID'
  AND ESTADO                       = 'Activo'
  );
COMMIT;
/