DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET 
WHERE PARAMETRO_ID = (
            SELECT
                ID_PARAMETRO
            FROM
                DB_GENERAL.ADMI_PARAMETRO_CAB
            WHERE
                    NOMBRE_PARAMETRO = 'PARAMETROS_FORMULARIO_ACEPTACION_PROSPECTO'
                AND ESTADO = 'Activo'
        );

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'PARAMETROS_FORMULARIO_ACEPTACION_PROSPECTO';
COMMIT;       

