/**
 * DEBE EJECUTARSE EN DB_GENERAL
 * Script para eliminar cabecera y detalle de parametros para flujo de factibilidad con empresa Ecuanet.
 * @author Jonathan Mazón Sánchez <jmazon@telconet.ec>
 * @version 1.0 
 * @since 01-03-2023 - Versión Inicial.
 */

/*ROLLBACK PARA PONER PREFIJO MD EN EL VALOR4 */

 UPDATE
	DB_GENERAL.ADMI_PARAMETRO_DET
SET
	VALOR4 = '["MD"]'
	WHERE PARAMETRO_ID = 1852
	AND DESCRIPCION = 'VALIDACION_FACTIBILIDAD_NUEVO_ALGORITMO';


/*ROLLBACK PARA REGISTRO DE FACTIBILIDAD*/ 

DELETE
FROM
	DB_GENERAL.ADMI_PARAMETRO_DET
WHERE
	PARAMETRO_ID = (
	SELECT
		ID_PARAMETRO
	FROM
		DB_GENERAL.ADMI_PARAMETRO_CAB
	WHERE
		NOMBRE_PARAMETRO = 'FACTIBILIDAD_ELEMENTO_EQUIVALENTE')
	AND VALOR1 = 'EN'
	AND VALOR2 = 'OLT';


/*ROLLBACK CAMPOS PARA LA TOMA DE INFORMACION PARA INSTALACION DE OLT INTERNET ECUANET*/

DELETE
FROM
	DB_GENERAL.ADMI_PARAMETRO_DET
WHERE
	PARAMETRO_ID = (
	SELECT
		ID_PARAMETRO
	FROM
		ADMI_PARAMETRO_CAB
	WHERE
		NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN')
	AND DESCRIPCION = 'Valor3:Dist max. cobert,Valor4:Dist max. factib,Valor5-Valor6:# max. cajas-conectores Cobert-Factib'
	AND USR_CREACION = 'emartillo';

/*ROLLBACK CAMPOS PARA LA TOMA DE INFORMACION PARA INSTALACION DE OLT INTERNET ECUANET*/

DELETE
FROM
	DB_GENERAL.ADMI_PARAMETRO_DET
WHERE
	PARAMETRO_ID = (
	SELECT
		ID_PARAMETRO parametro_id
	FROM
		ADMI_PARAMETRO_CAB
	WHERE
		NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN')
	AND DESCRIPCION = 'Valor3: Tipo de elemento conector'
	AND USR_CREACION = 'emartillo';


/*ROLLBACK CAMPOS PARA LA TOMA DE INFORMACION PARA INSTALACION DE OLT INTERNET ECUANET*/

DELETE
FROM
	DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE
	ID_PARAMETRO = (
	SELECT
		ID_PARAMETRO
	FROM
		ADMI_PARAMETRO_CAB
	WHERE
		NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN')
	AND USR_CREACION = 'emartillo';

COMMIT;


/
     
