/*******************************************************************************************************************************************************/
/**
* DEBE EJECUTARSE EN DB_GENERAL
* @author jsburgos <jsburgos@telconet.ec>
* @version 1.0 15-02-2023.
********************************************************************************************************************************************************/
-- PARAMETROS GENERALES PARA EJECUTAR PROCESO DE MIGRACION OLT ALTA DENSIDAD
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB
(
    ID_PARAMETRO,
    NOMBRE_PARAMETRO,
    DESCRIPCION,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
    'MIGRACION_OLT_ALTA_DENSIDAD',
    'PARAMETROS PARA REALIZAR LA MIGRACION DE OLTS ALTA DENSIDAD',
    'Activo',
    'jsburgos',
     SYSDATE,
    '127.0.0.1'
);

-- DETALLES PARAMETROS
-- DETERMINAR EL NUMERO DE PIPE QUE SE ENVIAN EN LOS ARCHIVOS CSV DE MIGRACION, SE VALIDA EL FORMATO
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NUMERO DE PIPE QUE TIENE EL FORMATO DE ARCHIVO OLT EN LA MIGRACION',
     'NUMERO_PIPE',
     'OLT',
     '5',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NUMERO DE PIPE QUE TIENE EL FORMATO DE ARCHIVO SPLITTER EN LA MIGRACION',
     'NUMERO_PIPE',
     'SPLITTER',
     '1',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NUMERO DE PIPE QUE TIENE EL FORMATO DE ARCHIVO ENLACE EN LA MIGRACION',
     'NUMERO_PIPE',
     'ENLACE',
     '8',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

--- PARAMETROS PARA FILTROS DE REPORTES PREVIO A LA MIGRACION OLT ALTA DENSIDAD
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'INTERNET SMALL BUSINESS',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

--- PARAMETROS PARA ESPECIFICAR LOS PRODUCTOS TN QUE ENTRAN EN LA MIGRACION OLT ALTA DENSIDAD
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'TELCOHOME',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'DATOS SAFECITY',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'SAFECITYDATOS',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'SAFECITYWIFI',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'SAFECITYSWPOE',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'SAFE ANALYTICS CAM',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS TN',
     'PRODUCTO_TN',
     'IP',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

--- PARAMETROS PARA ESPECIFICAR LOS PRODUCTOS MEGA QUE ENTRAN EN LA MIGRACION OLT ALTA DENSIDAD
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL NOMBRE TECNICO DE LOS PRODUCTOS MD',
     'PRODUCTO_MD',
     'INTERNET',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);


-- FILTRO PARA PARA VALIDAR ESTADO DE LOS SERVICIOS
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Anulado',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Rechazado',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Rechazada',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Eliminado',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Cancelado',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Cancel',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA DETERMINAR EL ESTADO EN EL QUE NO DEBE ESTAR EL SERVICIO',
     'ESTADO_SERVICIO',
     'Trasladado',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

-- FILTRO PARA EXCLUIR MARCA TIPO TELLION
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA EXCLUIR MARCA TIPO TELLION',
     'TIPO_MARCA',
     'TELLION',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

--
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'FILTRO PARA TERMINAR LOOP DE ENLACE EN REPORTE PREVIO',
     'MAX_ITERACIONES_ENLACE',
     '50',
     NULL,
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

-- PARAMETROS PARA NOTIFICACIONES DE CORREO ELECTRONICO
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'REMITENTE Y ASUNTO DE CORREO PARA NOTIFICACIONES DE ERROR EN PROCESO DE MIGRACION OLT',
     'MIGRA_NOTIFICACIONES',
     'NOTIFICACIONES_ERR',
     'notificaciones_telcos@telconet.ec',
     'Reporte errores archivos cargados - Migración OLT {{NOMBRE_OLT}}',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'REMITENTE Y ASUNTO DE CORREO PARA NOTIFICACIONES DE REPORTES PREVIO A MIGRACION OLT',
     'MIGRA_NOTIFICACIONES',
     'NOTIFICACIONES_PREV_TECNICA',
     'notificaciones_telcos@telconet.ec',
     'Reportes iniciales Migración OLT DATA TECNICA {{NOMBRE_OLT}}',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'REMITENTE Y ASUNTO DE CORREO PARA NOTIFICACIONES DE REPORTES PREVIO A MIGRACION OLT',
     'MIGRA_NOTIFICACIONES',
     'NOTIFICACIONES_PREV_ENLACE',
     'notificaciones_telcos@telconet.ec',
     'Reportes iniciales Migración OLT ENLACES {{NOMBRE_OLT}}',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
(
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION
)
VALUES
(
     DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
     (SELECT ID_PARAMETRO        FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO   = 'MIGRACION_OLT_ALTA_DENSIDAD' AND ESTADO      = 'Activo'),
     'REMITENTE Y ASUNTO DE CORREO PARA NOTIFICACIONES DE REPORTES POSTERIOR A MIGRACION OLT',
     'MIGRA_NOTIFICACIONES',
     'NOTIFICACIONES_POST_TECNICA',
     'notificaciones_telcos@telconet.ec',
     'Reportes final Migración OLT {{NOMBRE_OLT}}',
     'Activo',
     'jsburgos',
      SYSDATE,
     '127.0.0.1'
);

-- INSERT PARA NUEVO DIRECTORIO PARA EL PROCESO DE MIGRACION OLT ALTA DENSIDAD
INSERT INTO DB_GENERAL.ADMI_GESTION_DIRECTORIOS
(
    ID_GESTION_DIRECTORIO,
    CODIGO_APP,
    CODIGO_PATH,
    APLICACION,
    PAIS,
    EMPRESA,
    MODULO,
    SUBMODULO,
    ESTADO,
    FE_CREACION,
    USR_CREACION
)
VALUES
(
    DB_GENERAL.SEQ_ADMI_GESTION_DIRECTORIOS.nextval,
    4,
    (SELECT (CASE WHEN MAX(CODIGO_PATH) IS NULL THEN 0+1 ELSE (MAX(CODIGO_PATH)+1) END) AS CODIGO_PATH
        FROM DB_GENERAL.ADMI_GESTION_DIRECTORIOS WHERE CODIGO_APP=4),
    'TelcosWeb',
    '593',
    'MD',
    'Tecnico',
    'MigracionOltAltaDensidad',
    'Activo',
    sysdate,
    'jsburgos'
);

COMMIT;
/

