/**
* Deletes de parámetros del paquete NAF47_TNET.GENERAR_IMG_EMPLEADOS_TN 
*
* @author Bryan Fonseca <bfonseca@telconet.ec>
* @version 1.0 24-11-2022
*/

-- Se borran los parámetros
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID = (
	SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'FOTOS_EMPLEADOS_TN'
);

-- Se borra la cabecera
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'FOTOS_EMPLEADOS_TN';

COMMIT;
/