/**
 * Documentación para actualizar parámetros
 * Parámetros de actualización en DB_GENERAL.ADMI_PARAMETRO_CAB 
 * y DB_GENERAL.ADMI_PARAMATRO_DET.
 *
 * @author Steven Ruano <sruano@telconet.ec>
 * @version 1.0 13-04-2023
 *
 */
 
SET SERVEROUTPUT ON

--UPDATE PARA EL PARAMETRO 
UPDATE DB_GENERAL.ADMI_PARAMETRO_DET
SET VALOR1        = 'HOUSING'
WHERE DESCRIPCION = 'LISTADO_SERVICIO_SERVIDORES_ALQUILER'
AND PARAMETRO_ID  =
  (SELECT ID_PARAMETRO
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB
  WHERE NOMBRE_PARAMETRO = 'LISTA_CONFIMAR_SERVICIO_CON_SERVIDOR_ALQUILER'
  );
  
COMMIT;

/

