INSERT INTO DB_GENERAL.admi_tipo_documento_general (ID_TIPO_DOCUMENTO, CODIGO_TIPO_DOCUMENTO, descripcion_tipo_documento, ESTADO, USR_CREACION, IP_CREACION, FE_CREACION, VISIBLE, PERSONA, ELEMENTO, mostrar_app)
VALUES (DB_GENERAL.SEQ_ADMI_TIPO_DOCUMENT_GENERAL.NEXTVAL, 'REGC', 'REGULARIZACION DE CONTRATO', 'Activo', 'epin','127.0.0.1', SYSDATE, 'S', 'N', 'N', 'S');

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB(id_parametro, NOMBRE_PARAMETRO, DESCRIPCION, MODULO, PROCESO, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION)
VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL, 'PRODUCTO_NO_APLICA_ADENDUM', 'CODIGO DE PRODUCTO QUE NO APLICAN PARA ADENDUM', 'COMERCIAL', 'COMERCIAL', 'Activo', 'epin', sysdate, '127.0.0.1'); 

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, EMPRESA_COD)
VALUES (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL, (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'PRODUCTO_NO_APLICA_ADENDUM'), 'PRODUCTO_NO_APLICA_ADENDUM', 'VOZ', 'Activo', 'epin', sysdate, '127.0.0.1', '18');

COMMIT;