/*
 * SCRIPT DCL DEL ESQUEMA DB_COMERCIAL. 
 * https://www.techonthenet.com/oracle/grant_revoke.php
 */
GRANT REFERENCES on DB_COMERCIAL.INFO_EMPRESA_GRUPO to DB_DOCUMENTO;
GRANT SELECT  ON DB_COMERCIAL.INFO_EMPRESA_GRUPO TO DB_DOCUMENTO;
/
