
/*
 * SCRIPT  DEL ESQUEMA NAF47_TNET PARA CREAR LAS TABLAS:
 * ADMI_APU 
 * ADMI_APU_PRODUCTO 
 * ADMI_APU_ARTICULO 
 */

	CREATE TABLE "NAF47_TNET"."ADMI_APU" 
	(
	    ID_APU NUMBER  NOT NULL ENABLE,
	    CODIGO_APU VARCHAR2(36 BYTE) NOT NULL ENABLE,
	    NOMBRE_APU  VARCHAR2(200 BYTE) NOT NULL ENABLE,
	    DESCRIPCION_APU  VARCHAR2(200 BYTE) NOT NULL ENABLE,
	    MARCA  VARCHAR2(6 BYTE) NOT NULL ENABLE,
	    EMPRESA_COD VARCHAR2(2 BYTE) NOT NULL ENABLE,
	    DEPARTAMENTO_ID NUMBER NOT NULL ENABLE,
	    ESTADO VARCHAR2(10 BYTE) NOT NULL ENABLE,
	    USR_CREACION   VARCHAR2(30 BYTE) NOT NULL ENABLE,
	    FE_CREACION TIMESTAMP(6) NOT NULL ENABLE,
	    USR_ULT_MOD VARCHAR2(30 BYTE),
	    FE_ULT_MOD TIMESTAMP(6),
	    CONSTRAINT "ADMI_APU_PK" PRIMARY KEY ("ID_APU"),
	    CONSTRAINT "ADMI_APU_FK1" FOREIGN KEY (EMPRESA_COD)
	               REFERENCES DB_COMERCIAL.INFO_EMPRESA_GRUPO (COD_EMPRESA),
	    CONSTRAINT "ADMI_APU_FK2" FOREIGN KEY (DEPARTAMENTO_ID)
	               REFERENCES DB_GENERAL.ADMI_DEPARTAMENTO (ID_DEPARTAMENTO)
	);

	
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."ID_APU" IS 'Id Pk de la tabla';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."CODIGO_APU" IS 'codigo del apu';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."NOMBRE_APU" IS 'nombre del apu';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."DESCRIPCION_APU" IS 'descripcion del apu';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."MARCA" IS 'marca del apu';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."EMPRESA_COD" IS 'id de la empresa del apu';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."DEPARTAMENTO_ID" IS 'id del departamento del apu';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."FE_CREACION" IS 'fecha creacion del registro';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."USR_CREACION" IS 'usuario que creo el registro';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."ESTADO" IS 'Estado de la planificación de la solicitud por asignado';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."FE_ULT_MOD" IS 'Fecha de ultima modificación de la tabla';
	COMMENT ON COLUMN NAF47_TNET."ADMI_APU"."USR_ULT_MOD" IS 'Usuario de ultima modificación de la tabla';
	COMMENT ON TABLE NAF47_TNET."ADMI_APU"  IS 'TABLA EN LA QUE SE REGISTRA APUS';
	

	create sequence NAF47_TNET.SEQ_ADMI_APU
	start with 1 
	increment by 1 
	nomaxvalue;

CREATE TABLE "NAF47_TNET"."ADMI_APU_PRODUCTO" (
    APU_ID NUMBER NOT NULL ENABLE,
    PRODUCTO_ID NUMBER NOT NULL ENABLE,
    ESTADO VARCHAR2(10 BYTE) NOT NULL ENABLE,
    USUARIO_CREACION VARCHAR2(30 BYTE) NOT NULL ENABLE,
    FECHA_CREACION TIMESTAMP(6) NOT NULL ENABLE,
    USUARIO_MODIFICACION VARCHAR2(30 BYTE) NOT NULL ENABLE,
    FECHA_MODIFICACION TIMESTAMP(6) NOT NULL ENABLE,
    CONSTRAINT "APU_ID_PRODUCTO_PK" PRIMARY KEY ("APU_ID","PRODUCTO_ID"),
    CONSTRAINT "APU_ID_PRODUCTO_FK" FOREIGN KEY (APU_ID) REFERENCES NAF47_TNET.ADMI_APU(ID_APU),
    CONSTRAINT "PRODUCTO_ID_FK" FOREIGN KEY (PRODUCTO_ID) REFERENCES DB_COMERCIAL.ADMI_PRODUCTO(ID_PRODUCTO)
);

create sequence NAF47_TNET.SEQ_ADMI_APU_PRODUCTO
 start with 1 
 increment by 1 
 nomaxvalue;

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_PRODUCTO"."APU_ID" IS 'Clave unica del articulo';
COMMENT ON COLUMN NAF47_TNET."ADMI_APU_PRODUCTO"."PRODUCTO_ID" IS 'Clave unica del articulo y Clave foranea para cabecera NAF_47_TNET.ADMI_APU';
COMMENT ON COLUMN NAF47_TNET."ADMI_APU_PRODUCTO"."ESTADO" IS 'indica el estado del producto';



CREATE TABLE "NAF47_TNET"."ADMI_APU_ARTICULO"
(
    ID_APU_ARTICULO NUMBER NOT NULL ENABLE,
    CODIGO_APU_ARTICULO VARCHAR2(36 BYTE) NOT NULL ENABLE,
    APU_ID NUMBER NOT NULL ENABLE,
    CODIGO_ARTICULO_NAF VARCHAR2(36 BYTE) NOT NULL ENABLE,
    EMPRESA_COD VARCHAR2(36 BYTE) NOT NULL ENABLE,
    ES_VARIABLE VARCHAR2(1 BYTE) NOT NULL ENABLE,
    CANTIDAD_DEFAULT NUMBER NOT NULL ENABLE,
    ES_PRINCIPAL VARCHAR2(1 BYTE) NOT NULL ENABLE,
    ESTADO VARCHAR2(10 BYTE) NOT NULL ENABLE,
    USUARIO_CREACION VARCHAR2(30 BYTE) NOT NULL ENABLE,
    FECHA_CREACION TIMESTAMP(6) NOT NULL ENABLE,
    USUARIO_MODIFICACION VARCHAR2(30 BYTE) NOT NULL ENABLE,
    FECHA_MODIFICACION TIMESTAMP(6) NOT NULL ENABLE,
    CONSTRAINT "ADMI_APU_ARTICULO_PK" PRIMARY KEY (ID_APU_ARTICULO),
    CONSTRAINT "APU_ID_FK" FOREIGN KEY (APU_ID) REFERENCES NAF47_TNET.ADMI_APU(ID_APU),
    CONSTRAINT "ARINDA_NAF_FK" FOREIGN KEY (CODIGO_ARTICULO_NAF,EMPRESA_COD) REFERENCES NAF47_TNET.ARINDA(NO_ARTI,NO_CIA)
);

create sequence NAF47_TNET.SEQ_ADMI_APU_ARTICULO
 start with 1 
 increment by 1 
 nomaxvalue;

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."CODIGO_APU_ARTICULO" is 'Clave unica del articulo';

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."APU_ID" is 'Clave foranea para cabecera NAF_47_TNET.ADMI_APU';

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."CODIGO_ARTICULO_NAF" is 'Clave foranea para tabla detalle NAF_47_TNET.ARINDA';

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."EMPRESA_COD" is 'Codigo empresa';

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."ES_VARIABLE" is 'indicaría que si necesito realziar el calculo (factor multiplicador) de la formula, su valor se veria afectado o no';

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."ES_PRINCIPAL" is 'Valor que indica si el material es principal';

COMMENT ON COLUMN NAF47_TNET."ADMI_APU_ARTICULO"."ESTADO" is 'indica el estado del material';



