
/*
 * SCRIPT DCL DEL ESQUEMA NAF47_TNET. 
 * SCRIPT PARA REMOVER SECUENCIALES DE LAS TABLAS ADMI_APU,ADMI_APU_PRODUCTO,ADMI_APU_ARTICULO
 * 
 */

DROP SEQUENCE NAF47_TNET.SEQ_ADMI_APU_ARTICULO;
DROP TABLE NAF47_TNET.ADMI_APU_ARTICULO;

DROP SEQUENCE NAF47_TNET.SEQ_ADMI_APU_PRODUCTO;
DROP TABLE NAF47_TNET.ADMI_APU_PRODUCTO;

DROP SEQUENCE NAF47_TNET.SEQ_ADMI_APU;
DROP TABLE NAF47_TNET.ADMI_APU;
/