CREATE OR REPLACE TRIGGER DB_COMERCIAL.BEFORE_SERVICIO_HISTORIAL_BI
  BEFORE UPDATE ON DB_COMERCIAL.INFO_SERVICIO_HISTORIAL
  REFERENCING NEW AS NEW OLD AS OLD 
  FOR EACH ROW
    /**
    * Documentaci�n para trigger BEFORE_SERVICIO_HISTORIAL_BI
    * Trigger que valida los update en la tabla INFO_SERVICIO_HISTORIAL y almacena fechas de update en INFO_SERVICIO_HISTORIAL_BI
    * @author M�nica Moreta <mmoreta@telconet.ec>
    * @version 2.0 24-08-2022
    */
 
BEGIN

    UPDATE DB_COMERCIAL.INFO_SERVICIO_HISTORIAL_BI
    SET FE_ULT_MOD                   = SYSDATE
    WHERE servicio_historial_id      = :NEW.ID_SERVICIO_HISTORIAL;
    --
    IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO DB_COMERCIAL.INFO_SERVICIO_HISTORIAL_BI (SERVICIO_HISTORIAL_ID,FE_ULT_MOD) 
    VALUES (:NEW.ID_SERVICIO_HISTORIAL, SYSDATE);

    end if; 
    
    EXCEPTION
    WHEN OTHERS THEN
    NULL; 

END;
/