CREATE OR REPLACE TRIGGER DB_COMERCIAL.BEFORE_INFO_SOLUCION_CAB
  BEFORE UPDATE ON DB_COMERCIAL.INFO_SOLUCION_CAB FOR EACH ROW

  /**
   * Documentación para el trigger BEFORE_INFO_SOLUCION_CAB'.
   * Trigger que actualiza los campos de auditoria.
   * @author Germán Valenzuela <gvalenzuela@telconet.ec>
   * @versión 1.0 02-04-2020
   */ 
BEGIN
  :NEW.USR_ULT_MOD := NVL(:NEW.USR_ULT_MOD,NVL(SYS_CONTEXT('USERENV','OS_USER'),USER));
  :NEW.FEC_ULT_MOD := NVL(:NEW.FEC_ULT_MOD,SYSDATE);
  :NEW.IP_ULT_MOD  := NVL(:NEW.IP_ULT_MOD,NVL(SYS_CONTEXT('USERENV','IP_ADDRESS'),'127.0.0.1'));
END;
/

