
--CREAR TRIGGER 
create or replace TRIGGER DB_COMERCIAL.BEFORE_SERVICIO_PRODCARACT_BI
  BEFORE UPDATE ON DB_COMERCIAL.INFO_SERVICIO_PROD_CARACT
  REFERENCING NEW AS NEW OLD AS OLD 
  FOR EACH ROW
    /**
    * Documentación para trigger BEFORE_SERVICIO_PRODCARACT_BI
    * Trigger que valida los update en la tabla INFO_SERVICIO_PROD_CARACT y almacena fechas de update en INFO_SERVICIO_PRODCARACT_BI 
    * @author Mónica Moreta <mmoreta@telconet.ec>
    * @version 2.0 24-08-2022
    */
 
BEGIN

    UPDATE DB_COMERCIAL.INFO_SERVICIO_PRODCARACT_BI 
    SET FE_ULT_MOD                   = SYSDATE
    WHERE servicio_prod_caract_id    = :NEW.ID_SERVICIO_PROD_CARACT;
    --
    IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO DB_COMERCIAL.INFO_SERVICIO_PRODCARACT_BI  (SERVICIO_PROD_CARACT_ID,FE_ULT_MOD) 
    VALUES (:NEW.ID_SERVICIO_PROD_CARACT, SYSDATE);

    end if; 
    
    EXCEPTION
    WHEN OTHERS THEN
    NULL; 

END; 



/