/*
  ======================================================
  =========== SCRIPT DE REVERSO - TRIGGERS ===========
  ======================================================
*/
DROP TRIGGER DB_COMERCIAL.BEFORE_INFO_SOLUCION_CAB;
DROP TRIGGER DB_COMERCIAL.BEFORE_INFO_SOLUCION_DET;
DROP TRIGGER DB_COMERCIAL.BEFORE_INFO_SOLUCION_REF;
DROP TRIGGER DB_COMERCIAL.BEFORE_INFO_SERVICIO_REC_CAB;
DROP TRIGGER DB_COMERCIAL.BEFORE_INFO_SERVICIO_REC_DET;
/
