BEGIN 
dbms_scheduler.create_job('"JOB_CREA_NC_RECHAZO_CONTRATO"',
job_type=>'PLSQL_BLOCK', job_action=>
'BEGIN DB_FINANCIERO.FNCK_TRANSACTION.P_REVERSO_CONTRATO_X_PARAMETRO (''NOTA_CREDITO_X_CONTRATO''); END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('17-OCT-2018 08.00.00.000000000 AM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=DAILY;BYHOUR=8;BYMINUTE=0;BYSECOND=0'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Job que crea las N/C por rechazo de contratos f�sicos creados desde la web.'
);
sys.dbms_scheduler.set_attribute('"JOB_CREA_NC_RECHAZO_CONTRATO"','NLS_ENV','NLS_LANGUAGE=''AMERICAN'' NLS_TERRITORY=''AMERICA'' NLS_CURRENCY=''$'' NLS_ISO_CURRENCY=''AMERICA'' NLS_NUMERIC_CHARACTERS=''.,'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD-MON-RR'' NLS_DATE_LANGUAGE=''AMERICAN'' NLS_SORT=''BINARY'' NLS_TIME_FORMAT=''HH.MI.SSXFF AM'' NLS_TIMESTAMP_FORMAT=''DD-MON-RR HH.MI.SSXFF AM'' NLS_TIME_TZ_FORMAT=''HH.MI.SSXFF AM TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD-MON-RR HH.MI.SSXFF AM TZR'' NLS_DUAL_CURRENCY=''$'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.enable('"JOB_CREA_NC_RECHAZO_CONTRATO"');
COMMIT; 
END; 
/ 
