BEGIN 
dbms_scheduler.create_job('"PROCESAR_RECHAZADOS_IVA"',
job_type=>'PLSQL_BLOCK', job_action=>
'DECLARE
  LV_EMPRESA_COD VARCHAR2(2);
  LV_MENSAJE     VARCHAR2(200);
  LV_USUARIO     VARCHAR2(20);
BEGIN
  LV_EMPRESA_COD := ''18'';
  LV_USUARIO     := ''telcos'';
  --Llamada del procedure
  FNCK_TRANSACTION.P_PROCESAR_ERROR_IVA(PV_EMPRESA_COD  => LV_EMPRESA_COD,
                                        PN_ID_DOCUMENTO => NULL,
                                        PV_ESTADO       => ''Rechazado'',
                                        PV_USUARIO      => LV_USUARIO,
                                        PV_MENSAJE      => LV_MENSAJE);
END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('21-JUL-2015 11.40.01.902826000 PM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=DAILY;BYDAY=MON,TUE,WED,THU,FRI,SAT,SUN;BYHOUR=19;BYMINUTE=0;BYSECOND=0'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'RE-GENERA LOS XML POR ERROR DE IVA'
);
sys.dbms_scheduler.set_attribute('"PROCESAR_RECHAZADOS_IVA"','NLS_ENV','NLS_LANGUAGE=''SPANISH'' NLS_TERRITORY=''SPAIN'' NLS_CURRENCY=''�'' NLS_ISO_CURRENCY=''SPAIN'' NLS_NUMERIC_CHARACTERS='',.'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD/MM/RR'' NLS_DATE_LANGUAGE=''SPANISH'' NLS_SORT=''SPANISH'' NLS_TIME_FORMAT=''HH24:MI:SSXFF'' NLS_TIMESTAMP_FORMAT=''DD/MM/RR HH24:MI:SSXFF'' NLS_TIME_TZ_FORMAT=''HH24:MI:SSXFF TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD/MM/RR HH24:MI:SSXFF TZR'' NLS_DUAL_CURRENCY=''�'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.enable('"PROCESAR_RECHAZADOS_IVA"');
COMMIT; 
END; 
/ 
