/*
 * Drop de los sinonimos de las nuevas estructuras de solución.
 */
DROP PUBLIC SYNONYM INFO_SOLUCION_CAB;
DROP PUBLIC SYNONYM INFO_SOLUCION_DET;
DROP PUBLIC SYNONYM INFO_SOLUCION_REFERENCIA;
DROP PUBLIC SYNONYM INFO_SERVICIO_RECURSO_CAB;
DROP PUBLIC SYNONYM INFO_SERVICIO_RECURSO_DET;
/

