/*
  =======================================================
  =========== SCRIPT DE REVERSO - ESTRUCTURAS ===========
  =======================================================
*/

DROP TABLE DB_DOCUMENTO.ADMI_ATRIBUTO_ENUNCIADO;
DROP TABLE DB_DOCUMENTO.ADMI_DOC_ENUNCIADO_RESP;
DROP TABLE DB_DOCUMENTO.ADMI_DOCUMENTO_ENUNCIADO;
DROP TABLE DB_DOCUMENTO.ADMI_DOCUMENTO;
DROP TABLE DB_DOCUMENTO.ADMI_ENUNCIADO;
DROP TABLE DB_DOCUMENTO.ADMI_RESPUESTA;
DROP TABLE DB_DOCUMENTO.ADMI_PROCESO;
/
