/*
 * DROP DE LOS PAQUETES DE COMECIAL.
 */
DROP PACKAGE DB_COMERCIAL.CMKG_SERVICIO_TRANSACCION;
DROP PACKAGE DB_COMERCIAL.CMKG_SOLICITUD_TRANSACCION;
DROP PACKAGE DB_COMERCIAL.CMKG_SOLUCIONES_CONSULTA;
DROP PACKAGE DB_COMERCIAL.CMKG_SOLUCIONES_TRANSACCION;
DROP PACKAGE DB_COMERCIAL.CMKG_SOLUCIONES_DC;
/
