/*
 * SCRIPT DML DEL ESQUEMA DB_DOCUMENTO. 
 *
 * @author: Miguel Guzman <mguzman@telconet.ec>
 * @notes: Migrado desde DB_DOCUMENTO/DML/DML_24102022_ccaguana.pks para proyecto Ecuanet
 */



 

DELETE FROM DB_DOCUMENTO.INFO_DOC_RESPUESTA_HIST WHERE doc_respuesta_id IN ( 
SELECT ID_DOC_RESPUESTA  FROM DB_DOCUMENTO.INFO_DOC_RESPUESTA WHERE doc_enunciado_resp_id IN ( 
SELECT id_doc_enunciado_resp FROM DB_DOCUMENTO.admi_doc_enunciado_resp WHERE 
DOCUMENTO_ENUNCIADO_ID  IN (
SELECT  ID_DOCUMENTO_ENUNCIADO FROM DB_DOCUMENTO.admi_documento_enunciado WHERE 
ENUNCIADO_ID IN (SELECT ID_ENUNCIADO FROM DB_DOCUMENTO.admi_enunciado WHERE EMPRESA_COD = 33)
))
); 


DELETE FROM DB_DOCUMENTO.INFO_DOC_RESPUESTA WHERE doc_enunciado_resp_id IN ( 
SELECT id_doc_enunciado_resp FROM DB_DOCUMENTO.admi_doc_enunciado_resp WHERE 
DOCUMENTO_ENUNCIADO_ID  IN (
SELECT  ID_DOCUMENTO_ENUNCIADO FROM DB_DOCUMENTO.admi_documento_enunciado WHERE 
ENUNCIADO_ID IN (SELECT ID_ENUNCIADO FROM DB_DOCUMENTO.admi_enunciado WHERE EMPRESA_COD = 33)
) ); 



 
DELETE FROM DB_DOCUMENTO.ADMI_TIPO_ENUNCIADO
WHERE  CAB_ENUNCIADO_ID IN (SELECT ID_CAB_ENUNCIADO FROM DB_DOCUMENTO.ADMI_CAB_ENUNCIADO WHERE EMPRESA_COD = 33)
AND USUARIO_CREACION ='mguzman'; 


DELETE FROM DB_DOCUMENTO.admi_atributo_enunciado 
WHERE CAB_ENUNCIADO_ID IN (SELECT ID_CAB_ENUNCIADO FROM DB_DOCUMENTO.ADMI_CAB_ENUNCIADO WHERE  EMPRESA_COD =  33); 


DELETE  FROM DB_DOCUMENTO.admi_doc_enunciado_resp WHERE 
DOCUMENTO_ENUNCIADO_ID  IN (
SELECT  ID_DOCUMENTO_ENUNCIADO FROM DB_DOCUMENTO.admi_documento_enunciado WHERE 
ENUNCIADO_ID IN (SELECT ID_ENUNCIADO FROM DB_DOCUMENTO.admi_enunciado WHERE EMPRESA_COD = 33)
);


DELETE  FROM DB_DOCUMENTO.admi_documento_enunciado WHERE 
ENUNCIADO_ID IN (SELECT ID_ENUNCIADO FROM DB_DOCUMENTO.admi_enunciado WHERE EMPRESA_COD = 33);


DELETE  FROM DB_DOCUMENTO.admi_enunciado WHERE EMPRESA_COD = 33;
 

DELETE FROM DB_DOCUMENTO.ADMI_RESPUESTA WHERE EMPRESA_COD = 33;


DELETE FROM DB_DOCUMENTO.ADMI_DOCUMENTO 
WHERE PROCESO_ID IN (
SELECT id_proceso FROM DB_DOCUMENTO.admi_proceso WHERE EMPRESA_COD = 33
);

DELETE FROM DB_DOCUMENTO.admi_proceso WHERE EMPRESA_COD = 33;

DELETE FROM DB_DOCUMENTO.ADMI_CAB_ENUNCIADO WHERE  EMPRESA_COD = 33;

commit;
/