

/*
 * SCRIPT DCL DEL ESQUEMA DB_COMERCIAL. 
 * SCRIPT PARA REMOVER PERMISOS DE EJECUCIÓN DE PAQUETES Y TABLAS DEL ESQUEMA DB_COMERCIAL 
 * AL ESQUEMA NAF47_TNET
 * 
 */
revoke ALL PRIVILEGES on "DB_GENERAL"."ADMI_DEPARTAMENTO" from "NAF47_TNET" ;
revoke ALL PRIVILEGES on "DB_COMERCIAL"."INFO_EMPRESA_GRUPO" from "NAF47_TNET" ;
revoke ALL PRIVILEGES on "DB_COMERCIAL"."ADMI_PRODUCTO" from "NAF47_TNET" ;
/