
/*
 * SCRIPT DCL DEL ESQUEMA DB_COMERCIAL. 
 * SCRIPT PARA AGREGAR PERMISOS DE EJECUCIÓN DE PAQUETES DEL ESQUEMA DB_COMERCIAL 
 * AL ESQUEMA NAF47_TNET
 * 
 */

GRANT EXECUTE ON DB_COMERCIAL.cmkg_gestion_productos TO NAF47_TNET;
grant all  on DB_GENERAL.ADMI_DEPARTAMENTO to NAF47_TNET;
grant all  on DB_COMERCIAL.INFO_EMPRESA_GRUPO to NAF47_TNET;
grant all  on DB_COMERCIAL.ADMI_PRODUCTO to NAF47_TNET
/