/*
  ======================================================
  =========== SCRIPT DE REVERSO - SECUENCIAS ===========
  ======================================================
*/

DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_SOLUCION_REFERENCIA;
DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_SOLUCION_DET;
DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_SOLUCION_CAB;
DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_SERVICIO_RECURSO_DET;
DROP SEQUENCE DB_COMERCIAL.SEQ_INFO_SERVICIO_RECURSO_CAB;

/
