/**
 * @author Alex Arreaga <atarreaga@telconet.ec>
 * @version 1.0
 * @since 04-11-2021    
 * Se crea reverso de configuraciones para validaciones forma de pago.
 */




--SE RESTAURA  EL TIPO FDP(FORMA DE PAGO) DE LOS DOCUMENTOS REQUERIDOS EN CONTRATO CUANDO EL CLIENTE ES TIPO JURIDICO
UPDATE DB_GENERAL.admi_parametro_det  apd SET apd.valor1 = 'FOT,CED,CEDR,NBR,RUC,FDP'
WHERE  apd.ID_PARAMETRO_DET = (
SELECT apd.ID_PARAMETRO_DET FROM
DB_GENERAL.admi_parametro_cab apc
inner join DB_GENERAL.admi_parametro_det apd on apd.parametro_id=apc.id_parametro
where apc.NOMBRE_PARAMETRO = 'DOC_GENERACION_CONTRATO/ADENDUM'
AND  apd.DESCRIPCION ='JURIDICA'
);
    

--SE ELIMINA DETALLES DE PARAMETROS
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
	WHERE PARAMETRO_ID IN ( SELECT ID_PARAMETRO
	                        FROM DB_GENERAL.ADMI_PARAMETRO_CAB
	                        WHERE NOMBRE_PARAMETRO = 'PARAM_FLUJO_VALIDACIONES_FORMAS_PAGOS'
	                        AND ESTADO             = 'Activo');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE
NOMBRE_PARAMETRO = 'PARAM_FLUJO_VALIDACIONES_FORMAS_PAGOS';	


--ELINMINA LOS DOCUMENTOS SUBIDOS QUE ESTAN RELACIONADOS AL TIPO DOCUENTO
DELETE  FROM DB_COMUNICACION.INFO_DOCUMENTO WHERE TIPO_DOCUMENTO_GENERAL_ID  IN (
SELECT ID_TIPO_DOCUMENTO  FROM DB_GENERAL.ADMI_TIPO_DOCUMENTO_GENERAL  WHERE
 CODIGO_TIPO_DOCUMENTO IN ('ESCTA','VCOMP','DECTA','MBV','SPBAN')
);

--ELIMINA EL TIPO DOCUMENTO
DELETE  FROM   DB_GENERAL.ADMI_TIPO_DOCUMENTO_GENERAL  WHERE
 CODIGO_TIPO_DOCUMENTO IN ('ESCTA','VCOMP','DECTA','MBV','SPBAN');  

COMMIT;
/


