INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Sistema Controladora Radio Prod','https://sites.telconet.ec/controladoras-radio/','Ambiente controladora radio','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Ambiente controladora radio',1,NULL,NULL,NULL,NULL,NULL,NULL,'Sistema Controladora Radio Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/controladoras-radio/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo2 telcos','http://telcos2.telconet.ec/','nodo2 telcos','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo2 telcos',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo2 telcos',NULL,NULL,NULL,NULL,NULL,'^http://telcos2.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo7 telcos','http://telcos7.telconet.ec/','nodo7 telcos','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo7 telcos',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo7 telcos',NULL,NULL,NULL,NULL,NULL,'^http://telcos7.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos6 https','https://telcos6.telconet.ec/','nodo telcos6 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos6 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos6 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos6.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos5 https','https://telcos5.telconet.ec/','nodo telcos5 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos5 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos5 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos5.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo0 telcos','http://telcos0.telconet.ec/','nodo0 telcos','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo0 telcos',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo0 telcos',NULL,NULL,NULL,NULL,NULL,'^http://telcos0.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos2 https','https://telcos2.telconet.ec/','nodo telcos2 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos2 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos2 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos2.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Sistema Horas extras','https://sites.telconet.ec/horas-extras/','Ambiente Horas extras','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Ambiente Horas extras',1,NULL,NULL,NULL,NULL,NULL,NULL,'Sistema Horas extras',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/horas-extras/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos','http://telcos.telconet.ec/','nodo telcos','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos',NULL,NULL,NULL,NULL,NULL,'^http://telcos.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos3','http://telcos3.telconet.ec/','nodo telcos3','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos3',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos3',NULL,NULL,NULL,NULL,NULL,'^http://telcos3.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos8','http://telcos8.telconet.ec/','nodo telcos8','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos8',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos8',NULL,NULL,NULL,NULL,NULL,'^http://telcos8.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos3 https','https://telcos3.telconet.ec/','nodo telcos3 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos3 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos3 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos3.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos8 https','https://telcos8.telconet.ec/','nodo telcos8 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos8 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos8 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos8.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Telcos Prod','https://telcos.telconet.ec/','Telcos Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Telcos Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Telcos Prod',NULL,NULL,NULL,NULL,NULL,'^https://telcos.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Consumo Celular Prod','https://sites.telconet.ec/consumo-celular/','Consumo Celular Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Consumo Celular Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Consumo Celular Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/consumo-celular/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Pedidos Prod','https://sites.telconet.ec/pedidos/','Pedidos Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Pedidos Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Pedidos Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/pedidos/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'SQA Board Prod','https://sites.telconet.ec/sqa/','SQA Board Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'SQA Board Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'SQA Board Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/sqa/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Intranet Prod','https://intranet.telconet.net/','Intranet Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Intranet Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Intranet Prod',NULL,NULL,NULL,NULL,NULL,'^https://intranet.telconet.net/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Gestion Documental Prod','https://sites.telconet.ec/gestiondocumental/','Gestion Documental Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Gestion Documental Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Gestion Documental Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/gestiondocumental/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Sis Red Prod','https://sisred.telconet.net/','Sis Red Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Sis Red Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Sis Red Prod',NULL,NULL,NULL,NULL,NULL,'^https://sisred.telconet.net/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Citas Covid 19 Prod','https://sites.telconet.ec/citas-covid19/','Citas Covid 19 Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Citas Covid 19 Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Citas Covid 19 Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/citas-covid19/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Monitor Elementos Prod','https://sites.telconet.ec/monitor-elementos/','Monitor Elementos Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Monitor Elementos Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Monitor Elementos Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/monitor-elementos/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo4 telcos','http://telcos4.telconet.ec/','nodo4 telcos','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo4 telcos',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo4 telcos',NULL,NULL,NULL,NULL,NULL,'^http://telcos4.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo6 telcos','http://telcos6.telconet.ec/','nodo6 telcos','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo6 telcos',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo6 telcos',NULL,NULL,NULL,NULL,NULL,'^http://telcos6.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos5','http://telcos5.telconet.ec/','nodo telcos5','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos5',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos5',NULL,NULL,NULL,NULL,NULL,'^http://telcos5.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos1','http://telcos1.telconet.ec/','nodo telcos1','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos1',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos1',NULL,NULL,NULL,NULL,NULL,'^http://telcos1.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos0 https','https://telcos0.telconet.ec/','nodo telcos0 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos0 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos0 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos0.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos7 https','https://telcos7.telconet.ec/','nodo telcos7 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos7 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos7 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos7.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos4 https','https://telcos4.telconet.ec/','nodo telcos4 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos4 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos4 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos4.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'nodo telcos1 https','https://telcos1.telconet.ec/','nodo telcos1 https','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'nodo telcos1 https',1,NULL,NULL,NULL,NULL,NULL,NULL,'nodo telcos1 https',NULL,NULL,NULL,NULL,NULL,'^https://telcos1.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Aplicaciones','https://aplicaciones.telconet.ec/','Aplicaciones','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Aplicaciones',1,NULL,NULL,NULL,NULL,NULL,NULL,'Aplicaciones',NULL,NULL,NULL,NULL,NULL,'^https://aplicaciones.telconet.ec/?.*',NULL,NULL);

INSERT INTO admi_servicio_sso (ID_SERVICIO_SSO,NOMBRE_SERVICIO,SERVICE_TARGET,DESCRIPCION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,DEPARTAMENTO_RESPONSABLE,NOMBRE_RESPONSABLE,CORREO_RESPONSABLE,AUTORIZAR_CAS,TIPO_AUTENTICACION) VALUES 
(nextval('SEQ_ADMI_SERVICIO_SSO'),'Gestion Persona Prod','https://sites.telconet.ec/gestion-personal/','Ambiente Gestion Persona Prod','Activo','cas',CURRENT_DATE,'127.0.0.1',NULL,NULL,NULL,'SISTEMAS','Jessica Suarez','jmsuarez@telconet.ec',TRUE,'CAS');
INSERT INTO regexregisteredservice (EXPRESSION_TYPE,ID,ACCESS_STRATEGY,ATTRIBUTE_RELEASE,DESCRIPTION,EVALUATION_ORDER,EXPIRATION_POLICY,INFORMATIONURL,LOGO,LOGOUT_TYPE,LOGOUT_URL,MFA_POLICY,NAME,PRIVACYURL,PROXY_POLICY,PUBLIC_KEY,REQUIRED_HANDLERS,RESPONSETYPE,SERVICEID,THEME,USERNAME_ATTR) VALUES 
('regex',nextval('SEQ_REGX_REGIS_SERVICE'),NULL,NULL,'Ambiente Gestion Persona Prod',1,NULL,NULL,NULL,NULL,NULL,NULL,'Gestion Persona Prod',NULL,NULL,NULL,NULL,NULL,'^https://sites.telconet.ec/gestion-personal/?.*',NULL,NULL);

COMMIT;

/


