/*
 * DROP DE LOS PAQUETES DE DB_INFRAESTRUCTURA.
 */
DROP PACKAGE DB_INFRAESTRUCTURA.INKG_SOLUCIONES_CONSULTA;
DROP PACKAGE DB_INFRAESTRUCTURA.INKG_SOLUCIONES_TRANSACCION;
DROP PACKAGE DB_INFRAESTRUCTURA.INKG_ELEMENTO_TRANSACCION;
/
