
--------------------------------------------------------
--  CREACIÓN DE LA TABLA ADMI_GRUPO
--  Tabla encargada de almacenar grupos de monitoreo 
--------------------------------------------------------
CREATE TABLE DB_MONITOREO.ADMI_GRUPO (
    ID_GRUPO                NUMBER,
    NOMBRE                  VARCHAR2(20),
    FE_CREACION             TIMESTAMP    NOT NULL,
    USR_CREACION            VARCHAR2(30) NOT NULL,
    IP_CREACION             VARCHAR2(30) NOT NULL,
    FE_MODIFICACION         TIMESTAMP,
    IP_MODIFICACION         VARCHAR2(30),
    USR_MODIFICACION        VARCHAR2(30),
    ESTADO                  VARCHAR2(20) NOT NULL
) 
/
--COMENTARIO TABLA
COMMENT ON TABLE DB_MONITOREO.ADMI_GRUPO IS 'TABLA PARA ALMACENAR LOS NUEVOS REGISTROS DE CAMPOS DE LOS GRUPOS';

--COMENTARIOS COLUMNAS
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.ID_GRUPO                  IS 'ID DEL GRUPO';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.NOMBRE                    IS 'NOMBRE DEL GRUPO';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.FE_CREACION               IS 'FECHA DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.USR_CREACION              IS 'USUARIO DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.IP_CREACION               IS 'IP DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.FE_MODIFICACION           IS 'FECHA DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.IP_MODIFICACION           IS 'IP DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.USR_MODIFICACION          IS 'USUARIO DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.ADMI_GRUPO.ESTADO                    IS 'ESTADO DEL GRUPO';

--------------------------------------------------------
--  CREACION DE LA TABLA INFO_GRUPO_DETALLE
--  Tabla encargada de almacenar el detalle de elementos en un grupo
--------------------------------------------------------
CREATE TABLE DB_MONITOREO.INFO_GRUPO_DETALLE (
    ID_GRUPO_DETALLE        NUMBER,
    GRUPO_ID                NUMBER,
    ELEMENTO_ID             NUMBER,
    FE_CREACION             TIMESTAMP    NOT NULL,
    USR_CREACION            VARCHAR2(30) NOT NULL,
    IP_CREACION             VARCHAR2(30) NOT NULL,
    FE_MODIFICACION         TIMESTAMP,
    IP_MODIFICACION         VARCHAR2(30),
    USR_MODIFICACION        VARCHAR2(30),
    ESTADO                  VARCHAR2(20) NOT NULL
)
/

--COMENTARIO TABLA
COMMENT ON TABLE DB_MONITOREO.INFO_GRUPO_DETALLE IS 'TABLA PARA ALMACENAR LOS DETALLES LOS ELEMENTOS EN UN GRUPO';

--COMENTARIOS COLUMNAS
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.ID_GRUPO_DETALLE          IS 'ID DE LA TABLA';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.GRUPO_ID                  IS 'ID DEL GRUPO';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.ELEMENTO_ID               IS 'ID DEL ELEMENTO';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.FE_CREACION               IS 'FECHA DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.USR_CREACION              IS 'USUARIO DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.IP_CREACION               IS 'IP DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.FE_MODIFICACION           IS 'FECHA DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.IP_MODIFICACION           IS 'IP DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.USR_MODIFICACION          IS 'USUARIO DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_DETALLE.ESTADO                    IS 'ESTADO DEL DETALLE DEL GRUPO';

--------------------------------------------------------
--  CREACION DE LA TABLA INFO_GRUPO_USUARIO
--  Tabla encargada de almacenar el detalle de usuarios en un grupo
--------------------------------------------------------
CREATE TABLE DB_MONITOREO.INFO_GRUPO_USUARIO (
    ID_GRUPO_USUARIO        NUMBER,
    GRUPO_ID                NUMBER,
    USUARIO_ID              NUMBER,
    FE_CREACION             TIMESTAMP    NOT NULL,
    USR_CREACION            VARCHAR2(30) NOT NULL,
    IP_CREACION             VARCHAR2(30) NOT NULL,
    FE_MODIFICACION         TIMESTAMP,
    IP_MODIFICACION         VARCHAR2(30),
    USR_MODIFICACION        VARCHAR2(30),
    ESTADO                  VARCHAR2(20) NOT NULL
)
/
--COMENTARIO TABLA
COMMENT ON TABLE DB_MONITOREO.INFO_GRUPO_USUARIO IS 'TABLA PARA AlMACENAR EL DETALLE DE LOS USUARIOS EN UN GRUPO';

--COMENTARIOS COLUMNAS
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.ID_GRUPO_USUARIO          IS 'ID DE LA TABLA';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.GRUPO_ID                  IS 'ID DEL GRUPO';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.USUARIO_ID                IS 'ID DEL USUARIO';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.FE_CREACION               IS 'FECHA DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.USR_CREACION              IS 'USUARIO DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.IP_CREACION               IS 'IP DE CREACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.FE_MODIFICACION           IS 'FECHA DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.IP_MODIFICACION           IS 'IP DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.USR_MODIFICACION          IS 'USUARIO DE MODIFICACION';
COMMENT ON COLUMN DB_MONITOREO.INFO_GRUPO_USUARIO.ESTADO                    IS 'ESTADO DEL GRUPO';

--------------------------------------------------------
--  CREACIÓN DE INDEX ADMI_GRUPO_NOMBRE
--------------------------------------------------------
CREATE INDEX DB_MONITOREO.IDX_GRUPO_NOMBRE ON DB_MONITOREO.ADMI_GRUPO (NOMBRE); 

--------------------------------------------------------
--  CREACIÓN DE INDEX ADMI_GRUPO_PK
--------------------------------------------------------
CREATE UNIQUE INDEX DB_MONITOREO.IDX_GRUPO_ID ON DB_MONITOREO.ADMI_GRUPO (ID_GRUPO); 

--------------------------------------------------------
--  CREACIÓN DE INDEX INFO_GRUPO_DETALLE_PK
--------------------------------------------------------
CREATE UNIQUE INDEX DB_MONITOREO.IDX_GRUPO_DETALLE_ID ON DB_MONITOREO.INFO_GRUPO_DETALLE (ID_GRUPO_DETALLE); 

--------------------------------------------------------
--  CREACIÓN DE INDEX INFO_GRUPO_USUARIO_PK
--------------------------------------------------------
CREATE UNIQUE INDEX DB_MONITOREO.IDX_GRUPO_USUARIO_ID ON DB_MONITOREO.INFO_GRUPO_USUARIO (ID_GRUPO_USUARIO); 

------------------------------------------------------
--  CREACIÓN DE CONSTRAINTS PARA LA TABLA ADMI_GRUPO
--------------------------------------------------------
ALTER TABLE DB_MONITOREO.ADMI_GRUPO ADD CONSTRAINT PK_ID_ADMI_GRUPO PRIMARY KEY (ID_GRUPO); 

--------------------------------------------------------
--  CREACIÓN DE CONSTRAINTS PARA LA TABLA INFO_GRUPO_DETALLE
--------------------------------------------------------
ALTER TABLE DB_MONITOREO.INFO_GRUPO_DETALLE ADD CONSTRAINT PK_ID_GRUPO_DETALLE PRIMARY KEY (ID_GRUPO_DETALLE); 

--------------------------------------------------------
--  CREACIÓN DE CONSTRAINTS PARA LA TABLA INFO_GRUPO_USUARIO
--------------------------------------------------------
ALTER TABLE DB_MONITOREO.INFO_GRUPO_USUARIO ADD CONSTRAINT PK_ID_GRUPO_USUARIO PRIMARY KEY (ID_GRUPO_USUARIO); 

--------------------------------------------------------
--  CREACIÓN DE REFERENCIAS DE LA TABLA INFO_GRUPO_DETALLE
--------------------------------------------------------
ALTER TABLE DB_MONITOREO.INFO_GRUPO_DETALLE ADD CONSTRAINT FK_GRUPO_DETALLE_ID_GRUPO_ID FOREIGN KEY (GRUPO_ID) REFERENCES DB_MONITOREO.ADMI_GRUPO (ID_GRUPO) ENABLE;

--------------------------------------------------------
--  CREACIÓN DE REFERENCIAS DE LA TABLA INFO_GRUPO_USUARIO
--------------------------------------------------------
ALTER TABLE DB_MONITOREO.INFO_GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_GRUPO_ID FOREIGN KEY (GRUPO_ID) REFERENCES DB_MONITOREO.ADMI_GRUPO (ID_GRUPO) ENABLE;
