DROP SEQUENCE NAF47_TNET.SEQ_INFO_DOCUMENTO;
DROP TABLE NAF47_TNET.INFO_DOCUMENTO;

DROP SEQUENCE NAF47_TNET.SEQ_ADMI_TIPO_DOCUMENTO;
DROP TABLE NAF47_TNET.ADMI_TIPO_DOCUMENTO;

DROP SEQUENCE NAF47_TNET.SEQ_ADMI_HALLAZGO;
DROP TABLE NAF47_TNET.ADMI_HALLAZGO;

DROP SEQUENCE NAF47_TNET.SEQ_ADMI_TIPO_SANCION;
DROP TABLE NAF47_TNET.ADMI_TIPO_SANCION;

/
