CREATE    OR REPLACE VIEW "NAF47_TNET"."V_ARTICULOS_CARACTERISTICAS" ("NO_CIA", "NO_ARTI", "DESC_ARTICULO", "BODEGA", "MODELO", "MARCA", "DESC_BODEGA", "STOCK", "ESTADO_ARTI_ACTIVO", "ID_CANTON", "GRUPO", "SUBGRUPO") AS 
  SELECT
    DA.NO_CIA,
    DA.NO_ARTI,
    CASE
        WHEN INSTR(DA.DESCRIPCION, '"') > 0 THEN
            SUBSTR(DA.DESCRIPCION, 0, INSTR(DA.DESCRIPCION, '"') - 1)
        ELSE
            DA.DESCRIPCION
    END AS DESC_ARTICULO,
    MA.BODEGA,
    DA.MODELO,
    (
        SELECT
            M.DESCRIPCION
        FROM
            NAF47_TNET.MARCAS M
        WHERE
            M.CODIGO = DA.MARCA
            AND M.NO_CIA = DA.NO_CIA
    ) MARCA,
    BO.DESCRIPCION   DESC_BODEGA,
    NVL(MA.SAL_ANT_UN, 0) + NVL(MA.COMP_UN, 0) + NVL(MA.OTRS_UN, 0) - NVL(MA.VENT_UN, 0) - NVL(MA.CONS_UN, 0) STOCK,
    DA.IND_ACTIVO    ESTADO_ARTI_ACTIVO,
    BO.ID_CANTON,
    DA.DIVISION      AS GRUPO,
    DA.SUBDIVISION   AS SUBGRUPO
FROM
    NAF47_TNET.ARINBO   BO,
    NAF47_TNET.ARINDA   DA,
    NAF47_TNET.ARINMA   MA
WHERE
    MA.BODEGA = BO.CODIGO
    AND MA.NO_CIA = BO.NO_CIA
    AND MA.NO_ARTI = DA.NO_ARTI
    AND MA.NO_CIA = DA.NO_CIA;