CREATE    OR REPLACE VIEW "NAF47_TNET"."V_DEVOLUCIONES_DETALLE" ("EMPRESA_ID", "DEVOLUCIONES_ID", "ID_DEVOLUCIONES_DETALLE", "MOTIVO", "CANTIDAD_A_DEVOLVER", "DEVUELTO", "PRODUCTO_ESTADO", "ESTADO", "OBSERVACION", "PEDIDO_ID", "ID_PEDIDO_DETALLE", "EMPRESA_PRODUCTO_ID", "PRODUCTO_ID", "NOMBRE_PRODUCTO", "CANTIDAD_DESPACHADA", "CANTIDAD_PROCESADA", "CANTIDAD_SIN_PROCESAR", "EMPRESA_USR_ASIGNADO_ID", "USR_ASIGNADO", "USR_ASIGNADO_ID", "ESTADO_DET_PEDIDO", "ESTADO_DET_DEVOLUCION", "USR_ASIGNADO_TIPO", "NOMBRE_USR_ASIGNADO", "CANTON_ID", "NOMBRE_CANTON", "CLASIFICACION_ARTICULO", "MANEJA_SERIE", "NO_ARTI_USADO", "IND_MOV_KARDEX", "TIPO_ARTICULO") AS 
  SELECT E.CODIGO AS EMPRESA_ID,
         DD.DEVOLUCIONES_ID,
         DD.ID_DEVOLUCIONES_DETALLE,
         DD.MOTIVO,
         NVL(DD.CANTIDAD_A_DEVOLVER,0) AS CANTIDAD_A_DEVOLVER,
         NVL(DD.CANTIDAD_DEVUELTA,0) AS DEVUELTO,
         DD.PRODUCTO_ESTADO,
         DD.ESTADO,
         DD.OBSERVACION,
         PD.PEDIDO_ID,
         PD.ID_PEDIDO_DETALLE,
         EP.CODIGO AS EMPRESA_PRODUCTO_ID,
         PD.PRODUCTO_ID,
         PD.DESCRIPCION AS NOMBRE_PRODUCTO,
         PD.CANTIDAD_DESPACHADA,
         NVL(PD.CANTIDAD_DEVUELTA,0) AS CANTIDAD_PROCESADA,
         PD.CANTIDAD_DESPACHADA - NVL(PD.CANTIDAD_DEVUELTA,0) AS CANTIDAD_SIN_PROCESAR,
         EE.CODIGO AS EMPRESA_USR_ASIGNADO_ID,
         PD.USR_ASIGNADO,
         PD.USR_ASIGNADO_ID,
         PD.ESTADO AS ESTADO_DET_PEDIDO,
         DD.ESTADO AS ESTADO_DET_DEVOLUCION,
         DECODE(P.USR_ASIGNADO_TIPO,'EMP','Empleado','CON','Contratista') AS USR_ASIGNADO_TIPO,
         --
         (SELECT VE.NOMBRE
          FROM NAF47_TNET.V_EMPLEADOS_EMPRESAS VE
          WHERE VE.NO_CIA = EE.CODIGO
          AND VE.NO_EMPLE = PD.USR_ASIGNADO_ID) AS NOMBRE_USR_ASIGNADO,
         --
         (SELECT OG.CANTON_ID
          FROM NAF47_TNET.V_EMPLEADOS_EMPRESAS VE,
               DB_COMERCIAL.INFO_OFICINA_GRUPO OG
          WHERE VE.OFICINA = OG.ID_OFICINA
          AND VE.NO_EMPLE = PD.USR_ASIGNADO_ID
          AND VE.NO_CIA = EE.CODIGO) AS CANTON_ID,
         --
         (SELECT C.NOMBRE_CANTON
          FROM NAF47_TNET.V_EMPLEADOS_EMPRESAS VE,
               DB_COMERCIAL.INFO_OFICINA_GRUPO OG,
               DB_GENERAL.ADMI_CANTON C
          WHERE VE.OFICINA = OG.ID_OFICINA
          AND VE.NO_CIA = OG.EMPRESA_ID
          AND OG.CANTON_ID = C.ID_CANTON
          AND VE.NO_EMPLE = PD.USR_ASIGNADO_ID
          AND VE.NO_CIA = EE.CODIGO) AS NOMBRE_CANTON,
         --
         (SELECT DA.TIPO_ASTERISCO
          FROM NAF47_TNET.ARINDA DA
          WHERE DA.NO_ARTI = PD.PRODUCTO_ID
          AND DA.NO_CIA = EP.CODIGO) AS CLASIFICACION_ARTICULO,
         --
         (SELECT DA.IND_REQUIERE_SERIE
          FROM NAF47_TNET.ARINDA DA
          WHERE DA.NO_ARTI = PD.PRODUCTO_ID
          AND DA.NO_CIA = EP.CODIGO) AS MANEJA_SERIE,
         --
         (SELECT DA.NO_ARTI_USADO
          FROM NAF47_TNET.ARINDA DA
          WHERE DA.NO_ARTI = PD.PRODUCTO_ID
          AND DA.NO_CIA = EP.CODIGO) AS NO_ARTI_USADO,
         --
         (SELECT DA.IND_MOV_KARDEX
          FROM NAF47_TNET.ARINDA DA
          WHERE DA.NO_ARTI = PD.PRODUCTO_ID
          AND DA.NO_CIA = EP.CODIGO) AS IND_MOV_KARDEX,
         --
         (SELECT DA.TIPO_ARTICULO
          FROM NAF47_TNET.ARINDA DA
          WHERE DA.NO_ARTI = PD.PRODUCTO_ID
          AND DA.NO_CIA = EP.CODIGO) AS TIPO_ARTICULO
  FROM DB_COMPRAS.ADMI_EMPRESA EP,
       DB_COMPRAS.ADMI_EMPRESA EE,
       DB_COMPRAS.ADMI_DEPARTAMENTO AD,
       DB_COMPRAS.ADMI_EMPRESA E,
       DB_COMPRAS.INFO_PEDIDO P,
       DB_COMPRAS.INFO_PEDIDO_DETALLE PD,
       DB_COMPRAS.INFO_DEVOLUCIONES D,
       DB_COMPRAS.INFO_DEVOLUCIONES_DETALLE DD
  WHERE PD.PRODUCTO_EMPRESA_ID = EP.ID_EMPRESA
  AND AD.EMPRESA_ID = EE.ID_EMPRESA
  AND P.DEPARTAMENTO_ID = AD.ID_DEPARTAMENTO
  AND D.EMPRESA_ID = E.ID_EMPRESA
  AND PD.PEDIDO_ID = P.ID_PEDIDO
  AND DD.PEDIDO_DETALLE_ID = PD.ID_PEDIDO_DETALLE
  AND DD.DEVOLUCIONES_ID = D.ID_DEVOLUCIONES;