CREATE    OR REPLACE VIEW "NAF47_TNET"."V_DESCRIPCION_CARACTERISTICA" ("ID_CARACTERISTICA", "DESCRIPCION", "ESTADO") AS 
  SELECT A.ID_CARACTERISTICA,
         (SELECT LISTAGG(B.DESCRIPCION, '-')  WITHIN GROUP (ORDER BY B.NIVEL) 
            FROM ARIN_CARACTERISTICA B
           WHERE B.ESTADO = 'A'
           START WITH B.ID_CARACTERISTICA = A.ID_CARACTERISTICA
         CONNECT BY PRIOR B.ID_CARACTERISTICA_PADRE = B.ID_CARACTERISTICA ) DESCRIPCION,
         A.ESTADO
    FROM ARIN_CARACTERISTICA A
   WHERE A.ULTIMO_NIVEL = 'S';