CREATE    OR REPLACE VIEW "NAF47_TNET"."V_PEDIDOS_COMPRA" ("ID_PEDIDO_DETALLE", "PRODUCTO_EMPRESA_ID", "PRODUCTO_ID", "DESCRIPCION", "CANTIDAD_COMPRAR", "USR_ASIGNADO_ID", "NOMBRE_ASIGNADO", "ID_PEDIDO", "FECHA", "USR_JEFE_ID", "NOMBRE_JEFE", "DEPARTAMENTO_ID", "NOMBRE_DEPARTAMENTO", "ID_EMPRESA") AS 
  SELECT PD.ID_PEDIDO_DETALLE,
         EP.CODIGO PRODUCTO_EMPRESA_ID,
         PD.PRODUCTO_ID,
         PD.DESCRIPCION,
         (NVL(PD.CANTIDAD,0) -NVL(PD.CANTIDAD_DESPACHADA,0)) CANTIDAD_COMPRAR,
         PD.USR_ASIGNADO_ID,
         (SELECT VE.NOMBRE FROM V_EMPLEADOS_EMPRESAS VE WHERE VE.NO_EMPLE = PD.USR_ASIGNADO_ID AND VE.NO_CIA = EP.CODIGO) NOMBRE_ASIGNADO,
         P.ID_PEDIDO,
         TRUNC(P.FE_CREACION) FECHA,
         P.USR_JEFE_ID,
         (SELECT VE.NOMBRE FROM V_EMPLEADOS_EMPRESAS VE WHERE VE.NO_EMPLE = P.USR_JEFE_ID AND VE.NO_CIA = E.CODIGO) NOMBRE_JEFE,
         P.DEPARTAMENTO_ID,
         D.NOMBRE NOMBRE_DEPARTAMENTO,
         E.CODIGO ID_EMPRESA
    FROM DB_COMPRAS.INFO_PEDIDO P,
         DB_COMPRAS.INFO_PEDIDO_DETALLE PD,
         DB_COMPRAS.ADMI_DEPARTAMENTO D,
         DB_COMPRAS.ADMI_EMPRESA E,
         --DB_COMPRAS.INFO_PEDIDO_TIPO T,
         DB_COMPRAS.ADMI_EMPRESA EP
   WHERE P.ID_PEDIDO = PD.PEDIDO_ID
     AND P.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO
     AND D.EMPRESA_ID = E.ID_EMPRESA
     AND PD.PRODUCTO_EMPRESA_ID = EP.ID_EMPRESA
     --AND P.PEDIDO_TIPO_ID = T.ID_PEDIDO_TIPO
     AND P.PEDIDO_TIPO IN ('Sol','Ins')
     AND P.ESTADO IN ('Autorizado','Recomendado','Despacho Parcial','Despacho Parcial/Recomendado')
     AND PD.ESTADO IN ('Autorizado','Despacho Parcial','Por Comprar')
     AND PD.ES_COMPRA = 'S';