CREATE TABLE DB_COMPRAS.INFO_TENDER_CAB (
    ID_TENDER_CAB   NUMBER NOT NULL,
    CODIGO_TENDER   VARCHAR2(100),
    CATEGORIA_ID    VARCHAR2(100),
    CATEGORIA_DESC  VARCHAR2(200),
    TITULO          VARCHAR2(450),
    DESCRIPCION     VARCHAR2(1000),
    VALOR           NUMBER(19, 2) DEFAULT 0.0 NOT NULL,
    FE_ENVIO        TIMESTAMP,
    FE_VENCIMIENTO  TIMESTAMP,
    TIPO_UNIDAD     VARCHAR2(10) DEFAULT 'UNIT',
    USER_KATUK      VARCHAR2(100),
    DETALLE_KATUK   CLOB,
    ESTADO          VARCHAR2(30) NOT NULL,
    USR_CREACION    VARCHAR2(30) NOT NULL,
    FE_CREACION     TIMESTAMP NOT NULL,
    USR_ULT_MOD     VARCHAR2(30),
    FE_ULT_MOD      TIMESTAMP,
    CONSTRAINT PK_ID_TENDER_CAB PRIMARY KEY ( ID_TENDER_CAB )
);

CREATE SEQUENCE DB_COMPRAS.SEQ_INFO_TENDER_CAB MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."ID_TENDER_CAB" IS
    'Clave primaria de la tabla';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."CODIGO_TENDER" IS
    'Código del tender que retorna la publicación de katuk';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."CATEGORIA_ID" IS
    'Id de la categoría del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."CATEGORIA_DESC" IS
    'Descripción  de la categoría del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."TITULO" IS
    'Titulo del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."DESCRIPCION" IS
    'Descripción del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."VALOR" IS
    'Valor total del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."FE_ENVIO" IS
    'Fecha de envío del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."FE_VENCIMIENTO" IS
    'Fecha de vencimiento del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."TIPO_UNIDAD" IS
    'Tipo de unidad del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."USER_KATUK" IS
    'Usuario id que retorna la publicación de katuk';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."DETALLE_KATUK" IS
    'Detalle de cada modificación de la licitación en el sistema katuk';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."ESTADO" IS
    'Estado del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."USR_CREACION" IS
    'Usuario que ingresó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."FE_CREACION" IS
    'Fecha de creación del registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."USR_ULT_MOD" IS
    'Usuario que modificó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_CAB"."FE_ULT_MOD" IS
    'Fecha de última modificación del registro';

CREATE TABLE DB_COMPRAS.INFO_TENDER_DET_SOL (
    ID_TENDER_DET_SOL     NUMBER NOT NULL,
    TENDER_CAB_ID         NUMBER NOT NULL,
    SOLICITUD_DETALLE_ID  NUMBER NOT NULL,
    CODIGO                VARCHAR2(15) NOT NULL,
    CANTIDAD              NUMBER,
    PROYECTO_ID           NUMBER,
    PUNTO_ID              NUMBER,
    SERVICIO_ID           NUMBER,
    ESTADO                VARCHAR2(30) NOT NULL,
    USR_CREACION          VARCHAR2(30) NOT NULL,
    FE_CREACION           TIMESTAMP NOT NULL,
    USR_ULT_MOD           VARCHAR2(30),
    FE_ULT_MOD            TIMESTAMP,
    CONSTRAINT PK_ID_TENDER_DET_SOL PRIMARY KEY ( ID_TENDER_DET_SOL ),
    CONSTRAINT FK_TENDER_SOL_CAB_ID FOREIGN KEY ( TENDER_CAB_ID )
        REFERENCES DB_COMPRAS.INFO_TENDER_CAB ( ID_TENDER_CAB ),
    CONSTRAINT FK_SOLICITUD_DETALLE FOREIGN KEY ( SOLICITUD_DETALLE_ID )
        REFERENCES DB_COMPRAS.INFO_SOLICITUD_DETALLE ( ID_SOLICITUD_DETALLE )
);

CREATE SEQUENCE DB_COMPRAS.SEQ_INFO_TENDER_DET_SOL MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."ID_TENDER_DET_SOL" IS
    'Clave primaria de la tabla';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."TENDER_CAB_ID" IS
    'Referencia a la cabecera del tender a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."SOLICITUD_DETALLE_ID" IS
    'Referencia a la solicitud de órden de compra a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."CODIGO" IS
    'Código del artículo(No_arti)';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."CANTIDAD" IS
    'Cantidad del artículo';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."PROYECTO_ID" IS
    'Referencia al proyecto a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."PUNTO_ID" IS
    'Referencia al punto a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."SERVICIO_ID" IS
    'Referencia al servicio a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."ESTADO" IS
    'Estado del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."USR_CREACION" IS
    'Usuario que ingresó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."FE_CREACION" IS
    'Fecha de creación del registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."USR_ULT_MOD" IS
    'Usuario que modificó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_SOL"."FE_ULT_MOD" IS
    'Fecha de última modificación del registro';

CREATE TABLE DB_COMPRAS.INFO_TENDER_DET (
    ID_TENDER_DET   NUMBER NOT NULL,
    TENDER_CAB_ID   NUMBER NOT NULL,
    SUBCAT_ID       VARCHAR2(100),
    SUBCAT_DESC     VARCHAR2(200),
    CODIGO          VARCHAR2(15) NOT NULL,
    DESCRIPCION     VARCHAR2(100) NOT NULL,
    CANTIDAD        NUMBER DEFAULT 0 NOT NULL,
    VALOR_UNITARIO  NUMBER(19, 2) DEFAULT 0.0 NOT NULL,
    SUBTOTAL        NUMBER(19, 2) DEFAULT 0.0 NOT NULL,
    ESTADO          VARCHAR2(30) NOT NULL,
    USR_CREACION    VARCHAR2(30) NOT NULL,
    FE_CREACION     TIMESTAMP NOT NULL,
    USR_ULT_MOD     VARCHAR2(30),
    FE_ULT_MOD      TIMESTAMP,
    CONSTRAINT PK_ID_TENDER_DET PRIMARY KEY ( ID_TENDER_DET ),
    CONSTRAINT FK_TENDER_CAB_ID FOREIGN KEY ( TENDER_CAB_ID )
        REFERENCES DB_COMPRAS.INFO_TENDER_CAB ( ID_TENDER_CAB )
);

CREATE SEQUENCE DB_COMPRAS.SEQ_INFO_TENDER_DET MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."ID_TENDER_DET" IS
    'Clave primaria de la tabla';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."TENDER_CAB_ID" IS
    'Referencia a la cabecera del tender a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."SUBCAT_ID" IS
    'Id Sub Categoría del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."SUBCAT_DESC" IS
    'Descripción Sub Categoría del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."CODIGO" IS
    'Código del artículo(No_arti)';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."DESCRIPCION" IS
    'Descripción del artículo(Desc_arti)';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."CANTIDAD" IS
    'Cantidad del artículo';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."VALOR_UNITARIO" IS
    'Valor unitario del artículo';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."SUBTOTAL" IS
    'Subtotal del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."ESTADO" IS
    'Estado del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."USR_CREACION" IS
    'Usuario que ingresó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."FE_CREACION" IS
    'Fecha de creación del registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."USR_ULT_MOD" IS
    'Usuario que modificó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET"."FE_ULT_MOD" IS
    'Fecha de última modificación del registro';

CREATE TABLE DB_COMPRAS.INFO_TENDER_ASIGNACION (
    ID_TENDER_ASIGNACION  NUMBER NOT NULL,
    TENDER_CAB_ID         NUMBER NOT NULL,
    LOGIN_ASIGNADO        VARCHAR2(30) NOT NULL,
    FE_ASIGNA_INI         TIMESTAMP NOT NULL,
    FE_ASIGNA_FIN         TIMESTAMP,
    OBSERVACION           VARCHAR2(1000),
    ESTADO                VARCHAR2(30) NOT NULL,
    USR_CREACION          VARCHAR2(30) NOT NULL,
    FE_CREACION           TIMESTAMP NOT NULL,
    USR_ULT_MOD           VARCHAR2(30),
    FE_ULT_MOD            TIMESTAMP,
    CONSTRAINT PK_ID_TENDER_ASIGNACION PRIMARY KEY ( ID_TENDER_ASIGNACION ),
    CONSTRAINT FK_TENDER_ASIGNACION_CAB_ID FOREIGN KEY ( TENDER_CAB_ID )
        REFERENCES DB_COMPRAS.INFO_TENDER_CAB ( ID_TENDER_CAB )
);

CREATE SEQUENCE DB_COMPRAS.SEQ_INFO_TENDER_ASIGNACION MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY
1 NOCACHE;

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."ID_TENDER_ASIGNACION" IS
    'Clave primaria de la tabla';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."TENDER_CAB_ID" IS
    'Referencia a la cabecera del tender a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."LOGIN_ASIGNADO" IS
    'Login de la persona asignada, para la gestión del tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."FE_ASIGNA_INI" IS
    'Fecha de cuando se asignó el tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."FE_ASIGNA_FIN" IS
    'Fecha de cuando se reasignó el tender';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."OBSERVACION" IS
    'Observación de la asignación';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."ESTADO" IS
    'Estado de la asignación';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."USR_CREACION" IS
    'Usuario que ingresó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."FE_CREACION" IS
    'Fecha de creación del registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."USR_ULT_MOD" IS
    'Usuario que modificó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_ASIGNACION"."FE_ULT_MOD" IS
    'Fecha de última modificación del registro';

CREATE TABLE DB_COMPRAS.INFO_TENDER_EXEC (
    ID_TENDER_EXEC    NUMBER NOT NULL,
    SOLICITUD_ID      NUMBER,
    FE_EJECUCION_INI  TIMESTAMP NOT NULL,
    FE_EJECUCION_FIN  TIMESTAMP,
    ESTADO_EJECUCION  VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_ID_TENDER_EXEC PRIMARY KEY ( ID_TENDER_EXEC ),
    CONSTRAINT FK_SOLICITUD_ID FOREIGN KEY ( SOLICITUD_ID )
        REFERENCES DB_COMPRAS.INFO_SOLICITUD ( ID_SOLICITUD )
);

CREATE SEQUENCE DB_COMPRAS.SEQ_INFO_TENDER_EXEC MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_EXEC"."ID_TENDER_EXEC" IS
    'Clave primaria de la tabla';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_EXEC"."SOLICITUD_ID" IS
    'Indicador de la última solicitud que se ejecutó(DB_COMPRAS.INFO_SOLICITUD)';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_EXEC"."FE_EJECUCION_INI" IS
    'Fecha inicial de ejecución';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_EXEC"."FE_EJECUCION_FIN" IS
    'Fecha final de ejecución';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_EXEC"."ESTADO_EJECUCION" IS
    'Estado de ejecución';

CREATE TABLE DB_COMPRAS.INFO_TENDER_DET_PROV (
    ID_TENDER_DET_PROV  NUMBER NOT NULL,
    TENDER_CAB_ID       NUMBER NOT NULL,
    ESTADO              VARCHAR2(30) NOT NULL,
    USR_CREACION        VARCHAR2(30) NOT NULL,
    FE_CREACION         TIMESTAMP NOT NULL,
    USR_ULT_MOD         VARCHAR2(30),
    FE_ULT_MOD          TIMESTAMP,
    CONSTRAINT INFO_TENDER_DET_PROV PRIMARY KEY ( ID_TENDER_DET_PROV ),
    CONSTRAINT FK_TENDER_PROV_CAB_ID FOREIGN KEY ( TENDER_CAB_ID )
        REFERENCES DB_COMPRAS.INFO_TENDER_CAB ( ID_TENDER_CAB )
);

CREATE SEQUENCE DB_COMPRAS.SEQ_INFO_TENDER_DET_PROV MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY
1 NOCACHE;

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."ID_TENDER_DET_PROV" IS
    'Clave primaria de la tabla';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."TENDER_CAB_ID" IS
    'Referencia a la cabecera del tender a la cual pertenece';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."ESTADO" IS
    'Estado del proveedor';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."USR_CREACION" IS
    'Usuario que ingresó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."FE_CREACION" IS
    'Fecha de creación del registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."USR_ULT_MOD" IS
    'Usuario que modificó el registro';

COMMENT ON COLUMN "DB_COMPRAS"."INFO_TENDER_DET_PROV"."FE_ULT_MOD" IS
    'Fecha de última modificación del registro';

COMMIT;
/