BEGIN 
dbms_scheduler.create_job('"JOB_REGULARIZA_INTERFACE"',
job_type=>'PLSQL_BLOCK', job_action=>
'BEGIN
     PRO_REGULARIZA_INTERFACE;
END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('02-JUL-2015 11.00.00.000000000 PM -05:00','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=DAILY; BYDAY=SUN; BYHOUR=22'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Job utilizado para regularizaci�n de data tecnica de interfaces de SPLITTERS'
);
sys.dbms_scheduler.set_attribute('"JOB_REGULARIZA_INTERFACE"','NLS_ENV','NLS_LANGUAGE=''AMERICAN'' NLS_TERRITORY=''AMERICA'' NLS_CURRENCY=''$'' NLS_ISO_CURRENCY=''AMERICA'' NLS_NUMERIC_CHARACTERS=''.,'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD-MON-RR'' NLS_DATE_LANGUAGE=''AMERICAN'' NLS_SORT=''BINARY'' NLS_TIME_FORMAT=''HH.MI.SSXFF AM'' NLS_TIMESTAMP_FORMAT=''DD-MON-RR HH.MI.SSXFF AM'' NLS_TIME_TZ_FORMAT=''HH.MI.SSXFF AM TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD-MON-RR HH.MI.SSXFF AM TZR'' NLS_DUAL_CURRENCY=''$'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.set_attribute('"JOB_REGULARIZA_INTERFACE"','logging_level',DBMS_SCHEDULER.LOGGING_FULL);
dbms_scheduler.enable('"JOB_REGULARIZA_INTERFACE"');
COMMIT; 
END; 
/ 