BEGIN 
dbms_scheduler.create_job('"JOB_FIN_CHOFER_PROVISIONAL"',
job_type=>'PLSQL_BLOCK', job_action=>
'DECLARE
  Pv_MensajeError VARCHAR2(50) := '''';
BEGIN
  DB_COMERCIAL.COMEK_TALLER_MOVILIZACION.COMEKP_FIN_CHOFER_PROVISIONAL(Pv_MensajeError);
END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('03-AUG-2016 10.03.34.000000000 PM -05:00','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=DAILY;BYHOUR=7,15,16,17,23;BYMINUTE=1;BYSECOND=0'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Se finalizan todas las asignaciones de choferes provisionales que ya hayan cumplido su respectivo tiempo de asignaci�n'
);
sys.dbms_scheduler.set_attribute('"JOB_FIN_CHOFER_PROVISIONAL"','NLS_ENV','NLS_LANGUAGE=''SPANISH'' NLS_TERRITORY=''SPAIN'' NLS_CURRENCY=''�'' NLS_ISO_CURRENCY=''SPAIN'' NLS_NUMERIC_CHARACTERS='',.'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD/MM/RR'' NLS_DATE_LANGUAGE=''SPANISH'' NLS_SORT=''SPANISH'' NLS_TIME_FORMAT=''HH24:MI:SSXFF'' NLS_TIMESTAMP_FORMAT=''DD/MM/RR HH24:MI:SSXFF'' NLS_TIME_TZ_FORMAT=''HH24:MI:SSXFF TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD/MM/RR HH24:MI:SSXFF TZR'' NLS_DUAL_CURRENCY=''�'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.enable('"JOB_FIN_CHOFER_PROVISIONAL"');
COMMIT; 
END; 
/ 