BEGIN 
dbms_scheduler.create_job('"JOB_CATALOGOS_MOBILE"',
job_type=>'PLSQL_BLOCK', job_action=>
'DECLARE
                      Lv_Error VARCHAR2(2000);
                      BEGIN
                          DB_COMERCIAL.CMKG_CATALOGOS_MOBILE.P_GENERA_JSON_CATALOGOS(''18'', NULL, Lv_Error) ;
                          DB_COMERCIAL.CMKG_CATALOGOS_MOBILE.P_GENERA_JSON_CATALOGOS(''33'', NULL, Lv_Error) ;
                      END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('14-MAY-2023 02.04.17.976053000 AM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=HOURLY; INTERVAL=2'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Proceso para generar catalogos de TM-COMERCIAL.'
);
sys.dbms_scheduler.set_attribute('"JOB_CATALOGOS_MOBILE"','NLS_ENV','NLS_LANGUAGE=''SPANISH'' NLS_TERRITORY=''SPAIN'' NLS_CURRENCY=''�'' NLS_ISO_CURRENCY=''SPAIN'' NLS_NUMERIC_CHARACTERS='',.'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD/MM/RR'' NLS_DATE_LANGUAGE=''SPANISH'' NLS_SORT=''SPANISH'' NLS_TIME_FORMAT=''HH24:MI:SSXFF'' NLS_TIMESTAMP_FORMAT=''DD/MM/RR HH24:MI:SSXFF'' NLS_TIME_TZ_FORMAT=''HH24:MI:SSXFF TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD/MM/RR HH24:MI:SSXFF TZR'' NLS_DUAL_CURRENCY=''�'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.enable('"JOB_CATALOGOS_MOBILE"');
COMMIT; 
END; 
/ 