BEGIN 
dbms_scheduler.create_job('"JOB_MIGRA_INFO_DASHBOARD"',
job_type=>'PLSQL_BLOCK', job_action=>
'DECLARE
  --
  PV_PREFIJOEMPRESA VARCHAR2(2);
  PD_FECHAINICIO    TIMESTAMP;
  PV_MENSAJEERROR   VARCHAR2(200);
  LN_DIA_ACTUAL     NUMBER;
  LN_ULTIMO_DIA_MES NUMBER;
  --
BEGIN
  --
  PV_PREFIJOEMPRESA := ''TN'';
  PD_FECHAINICIO    := SYSDATE-1;
  LN_DIA_ACTUAL     := TO_NUMBER(TO_CHAR(SYSDATE-1, ''DD''), ''99'');
  LN_ULTIMO_DIA_MES := TO_NUMBER(TO_CHAR(LAST_DAY(SYSDATE-1), ''DD''), ''99'');
  --
  DB_COMERCIAL.COMEK_TRANSACTION.P_MIGRA_INFORMACION_DASHBOARD( PV_PREFIJOEMPRESA => PV_PREFIJOEMPRESA,
                                                                PD_FECHAINICIO => PD_FECHAINICIO,
                                                                PV_MENSAJEERROR => PV_MENSAJEERROR );
  IF LN_DIA_ACTUAL = LN_ULTIMO_DIA_MES THEN
    --
    UPDATE DB_COMERCIAL.INFO_DASHBOARD_SERVICIO
    SET PROCESADO = ''S''
    WHERE PROCESADO = ''N'';
    COMMIT;
    --
  END IF;
  --
END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('03-AUG-2017 09.20.41.691161000 AM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=DAILY;INTERVAL=1; BYHOUR=0; BYMINUTE=0;BYSECOND=0'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'JOB QUE MIGRA LA INFORMACION DE LAS ORDENES DE SERVICIOS A LA TABLA DB_COMERCIAL.INFO_DASHBOARD_SERVICIO'
);
sys.dbms_scheduler.set_attribute('"JOB_MIGRA_INFO_DASHBOARD"','NLS_ENV','NLS_LANGUAGE=''AMERICAN'' NLS_TERRITORY=''AMERICA'' NLS_CURRENCY=''$'' NLS_ISO_CURRENCY=''AMERICA'' NLS_NUMERIC_CHARACTERS=''.,'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD-MON-RR'' NLS_DATE_LANGUAGE=''AMERICAN'' NLS_SORT=''BINARY'' NLS_TIME_FORMAT=''HH.MI.SSXFF AM'' NLS_TIMESTAMP_FORMAT=''DD-MON-RR HH.MI.SSXFF AM'' NLS_TIME_TZ_FORMAT=''HH.MI.SSXFF AM TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD-MON-RR HH.MI.SSXFF AM TZR'' NLS_DUAL_CURRENCY=''$'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.set_attribute('"JOB_MIGRA_INFO_DASHBOARD"','logging_level',DBMS_SCHEDULER.LOGGING_RUNS);
dbms_scheduler.enable('"JOB_MIGRA_INFO_DASHBOARD"');
COMMIT; 
END; 
/ 