ALTER TABLE DB_SSO.ADMI_SERVICIO_SSO DROP COLUMN TIPO_AUTENTICACION;

ALTER TABLE DB_SSO.ADMI_SERVICIO_SSO DROP COLUMN DEPARTAMENTO_RESPONSABLE;

ALTER TABLE DB_SSO.ADMI_SERVICIO_SSO DROP COLUMN NOMBRE_RESPONSABLE;

ALTER TABLE DB_SSO.ADMI_SERVICIO_SSO DROP COLUMN CORREO_RESPONSABLE;

ALTER TABLE DB_SSO.ADMI_SERVICIO_SSO DROP COLUMN AUTORIZAR_CAS;

/
