BEGIN 
dbms_scheduler.create_job('"JOB_GENERACION_RESUMEN_SLA"',
job_type=>'PLSQL_BLOCK', job_action=>
'DECLARE   
						   BEGIN						   
							DB_SOPORTE.SPKG_GENERACION_SLA.P_GENERACION_RESUMEN_SLA(ADD_MONTHS(TRUNC(SYSDATE,''MM''),-1),ADD_MONTHS(LAST_DAY(TRUNC(SYSDATE)),-1));
						   END;'
, number_of_arguments=>0,
start_date=>TO_TIMESTAMP_TZ('05-FEB-2023 09.53.33.816646000 AM AMERICA/GUAYAQUIL','DD-MON-RRRR HH.MI.SSXFF AM TZR','NLS_DATE_LANGUAGE=english'), repeat_interval=> 
'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=0;BYMINUTE=30;BYSECOND=0'
, end_date=>NULL,
job_class=>'"DEFAULT_JOB_CLASS"', enabled=>FALSE, auto_drop=>FALSE,comments=>
'Proceso para realiza el c�lculo masivo del SLA mensual para clientes de TN y MD'
);
sys.dbms_scheduler.set_attribute('"JOB_GENERACION_RESUMEN_SLA"','NLS_ENV','NLS_LANGUAGE=''AMERICAN'' NLS_TERRITORY=''AMERICA'' NLS_CURRENCY=''$'' NLS_ISO_CURRENCY=''AMERICA'' NLS_NUMERIC_CHARACTERS=''.,'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD-MON-RR'' NLS_DATE_LANGUAGE=''AMERICAN'' NLS_SORT=''BINARY'' NLS_TIME_FORMAT=''HH.MI.SSXFF AM'' NLS_TIMESTAMP_FORMAT=''DD-MON-RR HH.MI.SSXFF AM'' NLS_TIME_TZ_FORMAT=''HH.MI.SSXFF AM TZR'' NLS_TIMESTAMP_TZ_FORMAT=''DD-MON-RR HH.MI.SSXFF AM TZR'' NLS_DUAL_CURRENCY=''$'' NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE''');
dbms_scheduler.set_attribute('"JOB_GENERACION_RESUMEN_SLA"','logging_level',DBMS_SCHEDULER.LOGGING_FULL);
dbms_scheduler.enable('"JOB_GENERACION_RESUMEN_SLA"');
COMMIT; 
END; 
/ 
