          
          --- INSERT PARA REGISTRAR FERIADOS LOCALES
          
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '2', '11', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '15', null, null);
          
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '2', '14', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '21', null, null);

          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '2', '17', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '20', null, null);
          
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '3', '31', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '05', null, null);
          
          -----CAÑAR - AZOGUEZ ---------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '4', '17', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '03', '01', null);
          -----Chimborazo-     RIOBAMBA -----
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '4', '21', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '06', '01', null);
          ------Orellana - Francisco de Orellana	------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '4', '21', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '22', '03', null);
          -----EL ORO-----
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '4', '24', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '07', null, null);
          -----Pastaza- Puyo-----
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '5', '12', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '16', '04', null);
          -------Los Rios- Babahoyo-------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '5', '26', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '12', '01', null);
          --------Imbabura----
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '6', '26', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '10', null, null);
          -----EL ORO- Machala-----
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '6', '26', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '07', '01', null);
          -----SANTO DOMINGO- SANTO DOMINGO-----
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '7', '3', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '23', '23', null);
          -----Manabi-chone------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '7', '24', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '13', '03', null);
          ------Orellana-------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '7', '31', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '22', null, null);
          ------Esmeraldas-------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '8', '4', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '08', null, null);
          ------Manabi - chone -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '8', '7', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '13', '03', null);
           ------GUAYAS - MILAGRO -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '9', '18', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '09', '10', null);
           ------ Zamora Chinchipe - Zamora -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '10', '6', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '19', '01', null);
           ------Los Rios - Quevedo -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '10', '6', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '12', '05', null);
          ------Manabi - chone -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '10', '30', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '13', '03', null);
           ------Cañar - Azogues -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '11', '6', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '03', '01', null);
           ------Santo Domingo -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '11', '6', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '23', null, null);
           ------Morona Santiago -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '11', '10', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '14', null, null);
           ------Pastaza -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '11', '10', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '16', null, null);
           ------ Zamora Chinchipe -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '11', '10', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '19', null, null);
           ------ Napo - Tena -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '11', '17', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '15', '01', null);
           ------ Tungurahua - Baños -------
          insert into DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET, PARAMETRO_ID, DESCRIPCION, VALOR1, VALOR2, VALOR3, VALOR4, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION, USR_ULT_MOD, FE_ULT_MOD, IP_ULT_MOD,  VALOR5, EMPRESA_COD, VALOR6, VALOR7, OBSERVACION)
          values (DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,1334,'MES_DIAS_FERIADO', '12', '15', '2023', null, 'Activo', 'ksolis', sysdate, '127.0.0.1', null, null, null, '313', 10, '18', '02', null);


          COMMIT;

          /