/*
 * SCRIPT DCL DEL ESQUEMA DB_INFRAESTRUCTURA. 
 */
GRANT EXECUTE ON DB_INFRAESTRUCTURA.INKG_SOLUCIONES_TRANSACCION TO DB_COMERCIAL;
GRANT EXECUTE ON DB_INFRAESTRUCTURA.INKG_ELEMENTO_TRANSACCION   TO DB_COMERCIAL;
/
