/*
 * SCRIPT DCL DE REVERSO DEL ESQUEMA DB_INFRAESTRUCTURA. 
 */
REVOKE EXECUTE ON DB_INFRAESTRUCTURA.INKG_SOLUCIONES_TRANSACCION TO DB_COMERCIAL;
REVOKE EXECUTE ON DB_INFRAESTRUCTURA.INKG_ELEMENTO_TRANSACCION   TO DB_COMERCIAL;
/
